### PR TITLE
Use a larger -rpcclienttimeout for slow performance measurements

### LINKED ISSUE #2238: Fix Buildbot hanging during performance benchmarks
During the merge run-up to 1.0.8, the performance benchmarks on https://ci.z.cash/ started hanging during `solveequihash`. At the time I though this was just related to the various other ongoing Buildbot problems, but now I think it is a separate issue that appears to have been caused by merging #2176 ([before](https://ci.z.cash/builders/zcashperformance/builds/175), [after](https://ci.z.cash/builders/zcashperformance/builds/176)). My current thinking is that it is hanging because it's the first benchmark that amounts to an RPC call taking over half an hour to return (though I don't yet know whether that is a significant number - it could be anything over 10 minutes).

### PR DESCRIPTION
**Pull request by str4d**
Closes #2238.

### CODE REVIEW

**Comment by str4d** [comment]
This only touches the performance benchmark script, and [has been tested](https://ci.z.cash/builders/zcashperformance/builds/192) to ensure it fixes the problem. Self-ACK because this needs to be in now before anything else, to fix performance metrics collection.

@zkbot r+

**Comment by str4d** [comment]
@zkbot force

**Comment by str4d** [comment]
Hmm... @ebfull or @ageis could you see why Homu isn't merging this? And maybe review at the same time :stuck_out_tongue_winking_eye:

**Comment by ageis** [comment]
@zkbot force

**Comment by ageis** [comment]
@zkbot force

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot retry

**Pull request merged**
