### PR TITLE
Enforce standard transaction rules on testnet

### LINKED ISSUE #1582: Enforce standard transaction rules on testnet
This will make testnet behave much more similarly to mainnet, allowing users to find issues with transaction propagation due to failing to follow standard rules.

### PR DESCRIPTION
**Pull request by str4d**
Closes #1582

### CODE REVIEW

**Comment by str4d** [comment]
Testing so we can see what breaks.

@zkbot try

**Comment by daira** [comment]
ACK. @zkbot r+

**Comment by str4d** [comment]
Hmm, Buildbot isn't building this because the commit id didn't change (because I expected everything to break).

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot force

**Comment by daira** [comment]
Oh, is there a bug where zkbot try followed by zkbot r+ on the same commit doesn't work?

**Comment by str4d** [comment]
Yes. It works for Homu, but Buildbot doesn't detect anything because it has already seen the commit id.

**Comment by str4d** [comment]
@zkbot force

**Pull request merged**
