### PR TITLE
Write R1CS output to file in GenerateParams.

### PR DESCRIPTION
**Pull request by ebfull**
Not urgent. This is how the constraint system is communicated to the MPC.

### CODE REVIEW

**Comment by daira** [comment]
utACK.

**Comment by daira** [comment]
Incidentally, it will be necessary for others to be able to do this to verify our parameter generation, so it should be documented (also to avoid people being confused by what this utility does).

**Comment by bitcartel** [comment]
utACK

**Comment by ebfull** [comment]
Can this be merged now?

**Comment by ageis** [comment]
ACK

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
