### PR TITLE
rename HaveJoinSplitRequirements for Sapling

### PR DESCRIPTION
**Pull request by arielgabizon**
The method also checks condition for Sapling spends whilst the method name implies otherwise

### CODE REVIEW

**Comment by daira** [comment]
I think `HaveShieldedRequirements` would be a better name. Presumably we might have other terminology for post-Sapling additions.

**Comment by arielgabizon** [comment]
Renamed as @daira requested (in code comments still left "joinsplits and spends" for clarity)

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by daira** [comment]
@zkbot retry

**Pull request merged**
