### PR TITLE
Rust build fixes

### PR DESCRIPTION
**Pull request by str4d**
Fixes cross-compilation, along with some minor adjustments to the Makefile integration.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot try

**Comment by mdr0id** [comment]
Does this PR also include cross windows fixes?

**Comment by str4d** [comment]
@mdr0id yes, I confirmed that `HOST=x86_64-w64-mingw32 ./zcutil/build.sh` works for this branch.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
