### PR TITLE
Closes #3182 - Least Authority Issue D

### LINKED ISSUE #3182: Least Authority Issue D: Undefined behavior in ​CBaseDataStream::read
Undefined behaviour when null pointer is passed in as an argument.

Partly mitigated by upstream commit https://github.com/bitcoin/bitcoin/commit/f478d98fe49d3c0c0f2c79b3f8d9dbfc1aafd407

### PR DESCRIPTION
**Pull request by bitcartel**
Prevent undefined behaviour when null pointer is passed in as parameter to function

Includes a backport of bitcoin/bitcoin#10250.

### CODE REVIEW

**Comment by bitcartel** [comment]
Rebased on master after #3180 was merged.

**Comment by str4d** [comment]
@zkbot try

**Comment by daira** [comment]
Test failure does not appear to be related, at first sight. @zkbot retry

**Comment by bitcartel** [comment]
I see this error, will investigate:
```
(leave) Call to r1cs_ppzksnark_verifier_process_vk	[0.0030s x1.00]	(1524314099.1322s x0.00 from start)
******unknown location(0): fatal error: in "coins_tests/ccoins_serialization": std::ios_base::failure: CBaseDataStream::read(): cannot read from null pointer
test/coins_tests.cpp(806): last checkpoint
**(enter) Call to r1cs_ppzksnark_verifier_process_vk	[  
```

**Comment by bitcartel** [comment]
Pushed fix, read can be called with null ptr and zero length, where behaviour is to expect void return if length is zero, rather than an exception being thrown. So we move the null ptr check to after the zero length check i.e. if the length to read is > 0, we expect the ptr to be non-null.

**Comment by bitcartel** [comment]
@zkbot try

**Comment by mdr0id** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
