### PR TITLE
Dependency Updates

### PR DESCRIPTION
**Pull request by defuse**
This updates:

- Boost from 1.66.0 to 1.69.0
- OpenSSL From 1.1.0h to 1.1.1a
- Proton from 0.17.0 to 0.26.0
- Rust from 1.28.0 to 1.32.0

### CODE REVIEW

**Comment by daira** [comment]
NACK for the e7fdbfd90c6372bb5a0529557960ad0277bf874a commit since [it would break RPC tests on macOS](https://github.com/zcash/zcash/issues/3808#issuecomment-457888595).

**Comment by defuse** [comment]
This is ready for review. I rebased on top of the current master and removed the commit @daira NACKed (#3799 will fix it for me). It's best to review `depends/patches/proton/minimal-build.patch` on its own, otherwise you're looking at a diff between two diffs. I may not have properly redone the patching work that was done in https://github.com/zcash/zcash/pull/2280, since I don't fully understand the motivation aside from fixing the one build issue. I would prefer to keep the patch small (or even remove it if possible) so that updating Proton is easier in the future. Someone should download the tarballs from a different vantage point and verify that the hashes match. Here are the URLs to save you time:

- https://www.openssl.org/source/openssl-1.1.1a.tar.gz
- https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.bz2
- https://archive.apache.org/dist/qpid/proton/0.26.0/qpid-proton-0.26.0.tar.gz
- https://static.rust-lang.org/dist/rust-1.32.0-x86_64-unknown-linux-gnu.tar.gz
- https://static.rust-lang.org/dist/rust-1.32.0-x86_64-apple-darwin.tar.gz
- https://static.rust-lang.org/dist/rust-1.32.0-x86_64-pc-windows-gnu.tar.gz

You might also want to look over my summaries of the changelogs in #3786 to see if I've missed any changes that will negatively impact us somehow. I'm not up to speed on our conventions for commit messages or how the PR title / first comment should be, so feel free to be pedantic about that.

Once merged, `https://z.cash/depends-sources/` needs to be updated with the new files.

This doesn't quite close #3786, since there are still other dependencies that haven't been updated and I haven't determined whether there are any security fixes in those ones. This fixes #3816.

**Comment by str4d** [comment]
ACK up to f3d99770b5fb9cb41cff650655f0d649cc2b8ca4 - I have verified the hashes on my machine.

NACK aa99366faca021d79db1b5799e8b24d5dd112410 - CI fails specifically on the Proton-enabled builder, and passes on the other builders.

btest:
```
unknown location(0): fatal error: in "Alert_tests/AlertApplies": Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::signals2::no_slots_error>
std::exception::what: boost::signals2::no_slots_error
test/alert_tests.cpp(283): last checkpoint: "AlertApplies" fixture ctor
```

```
Running stage no-dot-so
=======================
libqpid-proton-cpp.so.12
libqpid-proton-core.so.10
libqpid-proton.so.11
libqpid-proton-core.so.10.6.0
libqpid-proton-cpp.so.12.3.0
libqpid-proton-core.so
libqpid-proton-cpp.so
libqpid-proton-proactor.so.1.3.4
libqpid-proton-proactor.so.1
libqpid-proton.so.11.7.0
libqpid-proton-proactor.so
libqpid-proton.so
FAIL.
------------------------
Finished stage no-dot-so
```

RPC tests failed due to low disk space; I assume related to the btest failures (which maybe generated coredumps?)

**Comment by str4d** [comment]
For those who don't want to go searching through Buildbot's logs, here is the part where Proton gets built:

[3809-proton-build-log.txt](https://github.com/zcash/zcash/files/2822911/3809-proton-build-log.txt)

**Comment by defuse** [comment]
I fixed the proton patch to not build the `.so` files, and now the `no-dot-so` test passes (I squashed all the proton commits into one and forced pushed). I'm not able to reproduce the btest failures locally on any of my VMs (including a Debian 8 one). The first error we see is...

```
*****unknown location(0): fatal error: in "Alert_tests/AlertApplies": Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::signals2::no_slots_error>
std::exception::what: boost::signals2::no_slots_error
test/alert_tests.cpp(283): last checkpoint: "AlertApplies" fixture ctor
```

...and the following ones all look like...

```
unknown location(0): fatal error: in "Alert_tests/AlertNotify": std::runtime_error: CDBEnv::MakeMock: Already initialized
test/alert_tests.cpp(324): last checkpoint: "AlertNotify" fixture ctor
```

After looking at [this code](https://github.com/zcash/zcash/blob/master/src/wallet/db.cpp#L119) this suggests an exception is being thrown in [`TestingSetup::TestingSetup()`](https://github.com/zcash/zcash/blob/master/src/test/test_bitcoin.cpp#L88) in/after the call to `bitdb.MakeMock()` or in [the ReadAlerts : public TestingSetup constructor](https://github.com/zcash/zcash/blob/master/src/test/alert_tests.cpp#L249), and `TestingSetup::~TestingSetup()` isn't getting run which would explain the subsequent "MakeMock Already initialized" errors. The `TestingSetup` constructor creates some database files on disk so perhaps the disk was already full by then, but that doesn't explain why it's presenting as a `boost::signals2::no_slots_error`. I'll see if I can figure it out but in the meantime maybe we can retry the build.

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
For the v2.0.4 release, we had to patch this PR to fix build issues.  See #3918 and #3919.

**Pull request merged**
