### PR TITLE
Relay blocks when pruning

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from https://github.com/bitcoin/bitcoin/pull/6148

Part of #2074.

### CODE REVIEW

**Comment by tedy27** [comment]
Relay blocks when pruning #2815
str4d:2074-relay-pruning

**Comment by bitcartel** [comment]
I'm moving this back to the "In Review" column.

It would be prudent to make sure the extended qa test `pruning.py` passes, both with and without this PR.

**Comment by arielgabizon** [comment]
I get exactly same error on master though

**Comment by bitcartel** [comment]
As discussed with @arielgabizon the pruning test is not run on CI but if it were it would fail unless we add a runtime option to set the MAX_REORG_LENGTH (fairly easy) or update the test so that the reorg of 288 blocks is <100 blocks (complicated).

**Comment by bitcartel** [comment]
Infrastructure issue with mac builder. @zkbot retry

**Comment by bitcartel** [comment]
Looks like a transient failure of some sort on one of the builders.  Or the test is bad? (cc @str4d @Eirik0)
```
[ RUN      ] WalletTests.ClearNoteWitnessCache
wallet/gtest/test_wallet.cpp:1536: Failure
Value of: (bool) saplingWitnesses[1]
  Actual: true
Expected: false
wallet/gtest/test_wallet.cpp:1547: Failure
Value of: (bool) saplingWitnesses[1]
  Actual: true
Expected: false
[  FAILED  ] WalletTests.ClearNoteWitnessCache (4 ms)
```
The main debian 8 builder passed, so will try again.
@zkbot retry

**Pull request merged**
