### PR TITLE
Update copyright year to 2022

### PR DESCRIPTION
**Pull request by sandakersmann**
Update copyright year to 2022

### CODE REVIEW

**Comment by sandakersmann** [comment]
@str4d Merge before release?

**Comment by nuttycom** [comment]
Ideally this would fix the copyright notices in a bunch more places; since seeing this PR I've noticed a lot of headers where the copyright dates are wrong that this PR doesn't address.

**Comment by sandakersmann** [comment]
This PR did not aim at correcting all copyright headers.

**Comment by str4d** [comment]
Correct, I do not like those kinds of large-scale PRs, because they interfere with backports (which is also why most file headers have been left as-is). Automated PRs would be preferred in this case.

**Review by str4d — COMMENTED** [review]
Post-hoc ACK

**Pull request merged**
