### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by oxarbitrage**
Closes https://github.com/zcash/zcash/issues/4012

Equivalent to bitcoin/bitcoin/pull/9822

### CODE REVIEW

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
This RPC test failure occurs on all builders:
```
=== Running testscript paymentdisclosure.py ===
: Error opening block database.
Please restart with -reindex to recover.
```

I looked at `paymentdisclosure.py` and it's not obvious what the problem is.

**Comment by oxarbitrage** [comment]
Thank you @daira . While trying to find what was causing the issue i found the upstream commit where the delete was made: https://github.com/bitcoin/bitcoin/commit/4b183d33f3647714bb6eb39e1d1c3e54d2b2aaec

The `create_directories` need to stay, readded now at https://github.com/zcash/zcash/pull/4245/commits/c0d5b872774a7c108b3b5d586d23c6e59953a824

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
