### PR TITLE
Equihash.cpp: Consistent whitespace

### PR DESCRIPTION
**Pull request by paragonie-scott**
Low-hanging fruit/boyscouting: Consistent whitespace should make it a little easier for auditors to read, which in turn should increase the likelihood of any mistakes getting caught.

### CODE REVIEW

**Comment by ebfull** [comment]
ACK

**Comment by str4d** [comment]
I'm NACK on this because a) C++ style generally has no whitespace between operators in this kind of arithmetic, and b) it's going to cause a bunch of conflicts with the optimisation branch. But I can live with b) if I am overruled on a), so I will defer to @nathan-at-least on this :)

**Comment by ebfull** [comment]
C++ style is wrong if whitespace like this is frowned upon, in my opinion.

**Comment by defuse** [comment]
I'm thought the no-whitespace version was more common but I just looked in `sha256.cpp` and `secp256k1.c` and the style there is consistent with this PR.

**Comment by daira** [comment]
I have no opinion on the whitespace issue per se (the only rule I insist on is that whitespace be consistent with operator precedence, e.g. "a+b * c" would be forbidden). However, I think we should merge this only after the optimisation branch has landed.

**Comment by paragonie-scott** [comment]
Sure. Feel free to close this PR but make a congruent change in the optimization branch, if that's preferable.

**Comment by ebfull** [comment]
PRs like this are very valuable for keeping the code cleaner and more accessible to new contributors, but at this time it's a little contentious with other changes we're making, so I'm closing.

**Comment by paragonie-scott** [comment]
:+1: Understood. I hope my proposal will be useful now and in the future in making the code easier to audit.

**Pull request closed without merging**
