### PR TITLE
Enable high-priority alerts to put the RPC into safe mode

### LINKED ISSUE #1106: Make alerts able to put nodes into safe mode
https://en.bitcoin.it/wiki/Alert_system#Safe_mode

### PR DESCRIPTION
**Pull request by str4d**
This reverts the changes in 986b5e257e2bb9d7aaed5111ca335732f8808b2d and adds a priority check.

Continuation of #1337
Closes #1106

### CODE REVIEW

**Comment by bitcartel** [comment]
Testing this now.  Please rebase branch on master.  Thanks.

**Comment by str4d** [comment]
Rebased. I've also updated the test data with new alerts that should enable and then disable safe mode, but have not added tests that use them yet.

**Comment by str4d** [comment]
@bitcartel tested a40034f7d6cb894f8d7899bc8411142305f836ae on the testnet and both he and I verified that alerts could enable and then disable safe mode.

I have force-pushed this PR to amend the testing commit. Currently it does not work as expected, and I am not sure why. My guess is that existing tests (and/or mine) aren't cleaning up after themselves, but there also seems to be something strange WRT deserialization of alerts...

**Comment by bitcartel** [comment]
This should help...

`BOOST_CHECK_EQUAL(GetWarnings("rpc"), "");` fails because the global variable has been set somewhere else, and on entering the test it has not been set back to "".

`BOOST_CHECK_EQUAL(alerts[5].strRPCError, "RPC disabled");` fails because alerts[5] is in its initial state. All fields are empty.  They only get populated after calling processAlert ` alerts[5].ProcessAlert(alertKey, false);`

In `GetWarnings` in `main.cpp` rpc error message does not get updated because alerts[6] has a priority of 100 which is too low, so the previous message still holds.
> if (alert.nPriority >= ALERT_PRIORITY_SAFE_MODE) {
  strRPC = alert.strRPCError;

**Comment by str4d** [comment]
Force-pushed to amend (only) the test commit. Test now works :smile: 

Ready for ACK / merging.

**Comment by bitcartel** [comment]
Test works now.  ACK.

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by str4d** [comment]
Failed because of buildserver issues.

@zkbot retry

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot retry

**Pull request merged**
