### PR TITLE
Fix broken pipe error on some platforms when running qa test wallet_protectcoinbase.py

### LINKED ISSUE #2263: RPC test: FAIL: wallet_protectcoinbase.py
When I run the RPC test I receive the following error and the test is unable to continue:

```
 File "/home/ces/zcash/qa/rpc-tests/test_framework/test_framework.py", line 134, in main
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 0.00000053 more to avoid creating invalid change output 0.00000001 (dust threshold is 0.00000054)
    stop_nodes(self.nodes)
  waiting for async operation opid-9ce296ee-1fb9-435e-8ebf-f9beeca4942a
  File "/home/ces/zcash/qa/rpc-tests/test_framework/util.py", line 224, in stop_nodes
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 10000.0001
  waiting for async operation opid-ed59042c-52cd-4197-884c-52476f3401f8
  ...returned status: failed
  ...returned error: Insufficient protected funds, have 9.9998, need 10000.0001
  Unexpected exception caught during testing: global name 'BrokenPipeError' is not defined
  Stopping nodes
```

Please advice on how to solve this issue.

Thank you.

### PR DESCRIPTION
**Pull request by bitcartel**
Closes #2263.

### CODE REVIEW

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@str4d Is this hanging?  How can I see what's happening in CI?

**Comment by bitcartel** [comment]
@zkbot force

**Comment by str4d** [comment]
If you went to https://ci.z.cash/#/builders/6/builds/25 you'd have seen that it was hanging on "waiting for workers to be available". I stopped `pr-try` manually, which revealed that there was an issue with AWS credentials (IDK why). The reason this PR hasn't been updated is because stopping `pr-try` or `pr-merge` manually doesn't return the right thing for Homu to detect (it needs them to finish with "error" rather than "cancelled").

**Comment by str4d** [comment]
@zkbot clear

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
Yep, I saw 25 but hadn't come across "workers to be available" before.  I tried @zkbot force but that doesn't seem to do anything.

**Comment by str4d** [comment]
@bitcartel For future reference, using zkbot's handle in any message will be detected by Homu - you just caused Homu to fail the try by using `force` :stuck_out_tongue:

**Comment by bitcartel** [comment]
@str4d Yes, I typed @ by accident, and then edited to [at] but too late.

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by str4d** [comment]
Problem was a clock sync issue between the CI server and AWS.

@zkbot retry

**Comment by bitcartel** [comment]
@str4d Results look good.  Pass for debian 8, debian 8 ktichen sink and ubuntu.  The other unsupported CI builders failed for other unrelated reasons.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
