### PR TITLE
Fix race condition in rpc-tests/wallet_protectcoinbase.py. closes #1597

### LINKED ISSUE #1597: !!! FAIL: wallet_protectcoinbase.py !!!
=== Running testscript wallet_protectcoinbase.py ===
  File "/home/zcashminer/zcash/qa/rpc-tests/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/home/zcashminer/zcash/qa/rpc-tests/wallet_protectcoinbase.py", line 81, in run_test
    assert_equal(Decimal(resp["private"]), Decimal('29.9999'))
  File "/home/zcashminer/zcash/qa/rpc-tests/test_framework/util.py", line 342, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
  Initializing test directory /tmp/testRHuMc1
  Mining blocks...
  waiting for async operation opid-a6dea533-4f60-4c88-b4eb-19b94bc99305
  ...returned status: success
  Assertion failed: 0.00 != 29.9999
  Stopping nodes
  Cleaning up
  Failed
!!! FAIL: wallet_protectcoinbase.py !!!

### PR DESCRIPTION
**Pull request by str4d**
Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by str4d** [comment]
ACK

@zkbot r+

**Comment by str4d** [comment]
@zkbot force

**Comment by bitcartel** [comment]
@daira Can you expand on the race condition i.e. what prompted this PR?  Looking at the other .py tests, typically sync_all() is invoked after a call to generate().  Thanks.

**Comment by daira** [comment]
The test waits for the ``z_sendmany`` to succeed locally on node 0 and then tells node 1 to mine a block, but because there's no synchronization barrier between those, it is possible for the mined block not to include the z_sendmany transaction.

**Comment by bitcartel** [comment]
@daira Right.  By the way, z_sendmany is used in two other tests, so this problem could also appear there:
```
wallet_nullifiers.py:        myopid = self.nodes[0].z_sendmany(mytaddr, recipients)
wallet_nullifiers.py:        myopid = self.nodes[0].z_sendmany(myzaddr0, recipients)
wallet_nullifiers.py:        myopid = self.nodes[2].z_sendmany(myzaddr, recipients)
wallet_nullifiers.py:        myopid = self.nodes[1].z_sendmany(myzaddr, recipients)
wallet_protectcoinbase.py:        myopid = self.nodes[0].z_sendmany(mytaddr, recipients)
wallet_protectcoinbase.py:        # check balances (the z_sendmany consumes 3 coinbase utxos)
wallet_protectcoinbase.py:        myopid = self.nodes[0].z_sendmany(myzaddr, recipients)
wallet.py:        myopid = self.nodes[2].z_sendmany(mytaddr, recipients)
wallet.py:        myopid = self.nodes[2].z_sendmany(myzaddr, recipients)
```

**Comment by daira** [comment]
@bitcartel thanks, please review #1599.

**Pull request merged**
