### PR TITLE
Replace "Bitcoin" with "Zcash" in thread names and error messages

### PR DESCRIPTION
**Pull request by jasondavies**
Part of #1756.

### CODE REVIEW

**Comment by daira** [comment]
See also #2150.

**Comment by str4d** [comment]
I have opened #2564 to pull in bitcoin/bitcoin#6504; this PR should be rebased on master once that merges.

**Comment by jasondavies** [comment]
Rebased on master.

**Comment by jasondavies** [comment]
Rebased on master.

**Comment by jasondavies** [comment]
Rebased.

**Comment by str4d** [comment]
ACK. Thanks for keeping up with the rebases @jasondavies :smile:

@zkbot r+

**Pull request merged**
