### PR TITLE
Initialise walletdb system in a temp dir for all gtests

### PR DESCRIPTION
**Pull request by str4d**
Replaces #1767.

### CODE REVIEW

**Comment by ebfull** [comment]
Yup, this makes sense.

ACK

@zkbot r+

**Comment by bitcartel** [comment]
The wallet writes files to whatever directory is set in the config option -datadir.  Does setting the temp path in bitdb.open() override this?

**Comment by str4d** [comment]
The wallet writes to whatever directory is set in that config option, *the first time the wallet opens a file within the process*. After that, it always writes to that same directory, regardless of the config option.

**Comment by bitcartel** [comment]
Hmm.  I built this PR and ran the test `./zcash-gtest --gtest_filter="wallet_zkeys_tests.*"` and it created a file in the testnet3 folder `~/.zcash/testnet3/debug.log`

**Comment by str4d** [comment]
That's strange... I built this PR and ran `./zcash-gtest` and then killed it just after the `wallet_zkeys_tests` had run, and observed that files were written to `/tmp/random-dir/*`

**Comment by str4d** [comment]
Also, the unit tests have just passed, without us having cleared out the `~/.zcash` dir on the latent slave (and it hadn't been destroyed by Buildbot as it is still running grind). So I'm personally satisfied it worked, and am inclined to suggest that the test @bitcartel ran above was still somehow on the old `zcash-gtest`, for which the observed behaviour would be expected.

**Comment by bitcartel** [comment]
Let's both try on a clean build again.

**Comment by bitcartel** [comment]
Ok, here are the results.  Clean build.

./zcash-gtest --gtest_filter="wallet_zkeys_tests.*"
writes to ~/.zcash/testnet3/debug.log

 ./zcash-gtest
[ctrl-c] after wallet_zkeys_tests runs and interrupt another test:
writes to ~/.zcash/debug.log

**Comment by str4d** [comment]
Okay, so it's *not* writing to `wallet.dat` or `wallet_crypted.dat` either time, which is what this PR fixed. But it looks like I should have left the `-datadir` setting inside those tests anyway to ensure the debug.log wasn't being written to as well.

**Comment by bitcartel** [comment]
#1767 exists so that `the wallet_zkey_tests stop writing to ~/.zcash/wallet.dat and ~/.zcash/wallet_crypted.dat` but I'm not sure that is true, so I'm going to build 1.0.0 and test again.

**Comment by str4d** [comment]
I just re-added the code I removed in this PR from `test_wallet_zkeys` and re-ran the tests.

./zcash-gtest --gtest_filter="wallet_zkeys_tests.*"
does not write to ~/.zcash/testnet3/debug.log

./zcash-gtest
[ctrl-c] after wallet_zkeys_tests runs and interrupt another test:
writes to ~/.zcash/debug.log

Contents is same as you give above.

**Comment by bitcartel** [comment]
Running 1.0.0 (delete .zcash first):

./zcash-gtest --gtest_filter="wallet_zkeys_tests.*"
nothing is written to .zcash

./zcash-gtest
[ctrl-c] after wallet_zkeys_tests runs and interrupt another test:
nothing is written to .zcash

Can you try 1.0.0?  Thanks.

**Comment by str4d** [comment]
I get the same behaviour as you for 1.0.0. It's definitely something introduced into master since then; most likely #1753 (which was the last PR we merged before having CI issues).

**Comment by bitcartel** [comment]
Can zbkot revert this commit?  Meanwhile we can try to figure out which commit causes the write to .zcash, and then debug that particular one?

**Comment by ebfull** [comment]
Please make a ticket regarding the issue being experienced, so that we can fix it after the 1.0.1 release. As long as the problem doesn't interfere with tests on CI, it should not block us.

**Comment by bitcartel** [comment]
But as it stands, with this PR, someone could run the test and it would write over their files.

**Comment by str4d** [comment]
Incorrect; this PR fixed the issue with wallet.dat being written over. A different commit caused other files to be written to, but as it appears the only file written to is `debug.log`, it's not a blocker IMHO (but I'm bisecting right now anyway to see if I can find it in next 5 mins).

**Comment by bitcartel** [comment]
Agreed, this PR is not writing over files, but is instread trying to fix a problem introduced post 1..0.0.

I think writing over debug.log is a blocker.

**Comment by str4d** [comment]
Just confirmed via bisection that the problem started in 548bbd95f019cb59924419945528906507b2f122

**Pull request merged**
