### PR TITLE
Tweak KDF for JoinSplit change outputs to prevent information leakage from payment disclosure

### LINKED ISSUE #2102: "KDF Tweak" method of preventing information leakage from payment disclosure
(This is an alternative to #2037.)

The proposed design for payment disclosure (#2036) reveals both outputs of a given JoinSplit, which is an information leak. It's sufficient to ensure that the second output is only used for change (which is the case for our current and [proposed](https://github.com/zcash/zcash/issues/1360) multijoinsplit construction algorithms), and to solve this information leak only for change payments.

In #2037, it was proposed to do this by having a secret change address for each "ordinary" address, which would have the effect of making one of the inputs to the KDF for the change payment a secret. This would prevent an adversary from being able to derive the secret key K<sup>enc</sup><sub>i</sub> for the change payment. (See section 4.10.1 of the protocol spec, where pk<sub>enc,i</sub> is a KDF input.) However, this has two main disadvantages:
* It is conceptually more complex, both at the protocol level and for end-users, to have separate change addresses rather than just sending change back to the original address. If we tried to hide the fact that there is a separate change address from end-users (whether by deriving the change spending key from the original spending key, or bundling them together), there would inevitably be abstraction leaks.
* When scanning transactions, a wallet must trial-decrypt for each spending key it holds, which would be double the number of keys in this approach, and therefore double the number of Curve25519 multiplications. This is important because scanning is already a significant performance bottleneck (see e.g. #1749).

@ebfull suggested the following clever idea: instead of using a separate change address, we can tweak the KDF so that in the case of a change payment, it takes sk<sub>enc,i</sub> as an input instead of pk<sub>enc,i</sub>. (For example, use Blake2b-256("ZcashKDF" || (i-1) || [0]<sup>8</sup> || "Change", hSig || sharedSecret<sub>i</sub> || epk || sk<sub>enc,i</sub>).) This has the effect that even if esk is known (e.g. from a payment disclosure), the change note ciphertext can only be decrypted with knowledge of the viewing key sk<sub>enc,i</sub>. The wallet would then trial-decrypt each note ciphertext with both KDFs, but only one address and one Curve25519 multiplication (per JoinSplit per address) would be needed.

### PR DESCRIPTION
**Pull request by str4d**
Closes #2102.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by daira** [comment]
Woah that was quick :-) Note that we haven't decided on this approach yet (but it is good to have a prototype implementation anyway).

**Comment by daira** [comment]
Needs rebasing and tests.

**Comment by str4d** [comment]
Rebased to fix merge conflicts. Still needs tests, and discussion in light of https://github.com/zcash/zcash/issues/2036#issuecomment-282357855.

**Comment by str4d** [comment]
@daira tests added for the note encryption / decryption changes. The existing RPC tests should be sufficient to ensure that `z_sendmany` calls with change outputs are usable.

**Comment by ebfull** [comment]
As is, it would seem this _always_ increases the number of trial decryptions. Do we have benchmarks which can allow us to see the effect of this?

**Comment by str4d** [comment]
Good point - we do not currently have benchmarks of that. I'll bump this into 1.0.14 and open an issue for creating them.

**Comment by str4d** [comment]
Dropping from 1.0.14 due to blocking issue being dropped.

**Comment by daira** [comment]
I don't think we should make this change given the low reward/risk benefit; instead we should concentrate on supporting Sapling payment disclosures.

**Comment by daira** [comment]
This can be closed because we're definitely not changing the Sprout protocol at this point.

**Pull request closed without merging**
