### PR TITLE
Fix the path to the example configuration

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by daira** [comment]
ACK. This is just a documentation string change and is obviously correct, so @zkbot r+

**Comment by daira** [comment]
Oh wait, I shouldn't be merging anything until after the release on Monday. @zkbot abort

**Comment by daira** [comment]
@zkbot r-

**Comment by daira** [comment]
@zkbot force

**Comment by elopio** [comment]
:) @zkbot pay attention!
Thanks @daira.

**Comment by daira** [comment]
"zkbot r-" silently aborts the merge but the test run continues, which is what confused me.

**Comment by daira** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot force

**Comment by str4d** [comment]
@ageis @ebfull ping, seems that state for this PR is invalid.

**Comment by str4d** [comment]
@zkbot retry

**Comment by str4d** [comment]
Ah, I see, it thought it was in a failed state because the test run continued.

**Comment by elopio** [comment]
Thanks for the merge! And sorry for the big mess on this simple change :)

**Pull request merged**
