### PR TITLE
Release v4.1.1

### PR DESCRIPTION
**Pull request by nuttycom**
Optimize release build
----------------------
The release build now sets CLAGS/CXXFLAGS to use the -O3 optimization
option, which turns on more optimization flags than the previously used
-O1. This produces a faster build, addressing a performance regression in 
v4.1.0.

Correctly report Founders' Reward amount in `getblocktemplate`
--------------------------------------------------------------
This release correctly returns the `foundersreward` field from `getblocktemplate`
output pre-Canopy and removes the field post-Canopy. (The Founders' Reward will
expire exactly as Canopy activates, as specified in [ZIP 207](https://zips.z.cash/zip-0207).)
To obtain information about funding stream amounts, use `getblocksubsidy HEIGHT`,
passing in the height returned by the `getblocktemplate` API.

### CODE REVIEW

**Comment by therealyingtong** [comment]
utACK. I verified that the release height is 1044500 (approx 20:50 UTC, 16 Nov 2020).

**Review by str4d — APPROVED** [review]
utACK.

**Review by therealyingtong — APPROVED** [review]

**Review by defuse — APPROVED** [review]
utACK

**Comment by nuttycom** [comment]
r+

**Comment by nuttycom** [comment]
@zkbot r+

**Review by daira — COMMENTED** [review]
Post-hoc ACK

**Pull request merged**
