### PR TITLE
Only check cache validity for witnesses being decremented

### PR DESCRIPTION
**Pull request by str4d**
Fixes the bug resulting from #1904.

### CODE REVIEW

**Comment by str4d** [comment]
@bitcartel both cache validity checks are conditional now.

**Comment by bitcartel** [comment]
Same error.

**Comment by ebfull** [comment]
```c++
                     for (std::pair<const uint256, CWalletTx>& wtxItem : mapWallet) {
                         for (mapNoteData_t::value_type& item : wtxItem.second.mapNoteData) {
                             CNoteData* nd = &(item.second);
                             // Check the validity of the cache
                             assert(nWitnessCacheSize >= nd->witnesses.size());
                             if (nd->witnessHeight < pindex->nHeight &&
                                     nd->witnesses.size() > 0) {
                                 nd->witnesses.front().append(note_commitment);
                             }
                         }
```

It's this assertion that needs to be made conditional by this PR now, I think.

**Comment by str4d** [comment]
Force-pushed to update the commit. All witness cache validity assertions are now conditional on block height.

**Comment by ebfull** [comment]
@bitcartel can you try to reindex again?

**Comment by Psixa18** [comment]
Release 1.0.4 fast or just release as it is right now, please, do not overdue more! I have impression like you don't even realize how important the fixed Z transactions are for the market, miners and Zcash itself, briefly for Zcash value! zk-SNARK is a masterpiece crown, without it nobody can see who is the real king!

**Comment by bitcartel** [comment]
@str4d @ebfull Reindexing with PR and PR rebased on master now complete. No assertions. ACK.

**Comment by ebfull** [comment]
I'm happy!

@zkbot r+

**Comment by str4d** [comment]
Darn, my page didn't refresh and notify me of this - I'd have said to wait, as I am still working on a test for this, and in doing so I have found another bug. I'll open another PR with those.

**Pull request merged**
