### PR TITLE
Add example mock test of CheckTransaction

### LINKED ISSUE #862: Add exemplary test of ``CheckTransaction`` using mock-based unit testing
This should test a *few* important cases, but does not need to be exhaustive. For this ticket we just want a few cases that we will later see with coverage analysis. Some proposals:

* a transaction with 0 JoinSplits and 0 inputs - should not verify
* a transaction with 0 JoinSplits, 1 "standard" txin, and 1 "standard" txout - should verify
* a transaction with 1 JoinSplit valid JoinSplit and 0 txin/txout.

Note that these tests should use mocks so that:

a. they don't rely on any globals,
b. the test is single-threaded,
c. no I/O occurs.

In particular, for example, the last test case above should verify that a mocked spent-serials map has been updated with the new spent serials without relying on or mutating the actual ``pool.mapSerials``.

### PR DESCRIPTION
**Pull request by defuse**
Closes #862.

### CODE REVIEW

**Comment by ebfull** [comment]
This is cool! ACK. Let's wait to merge this in though.

Do we have a ticket for removing the `PerformPourVerification` method of `CValidationState` (which I added in order to selectively disable that verification in transaction_tests and sighash_tests?)

**Comment by str4d** [comment]
ACK!

**Comment by daira** [comment]
ACK

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot retry

**Pull request merged**
