### PR TITLE
Dockerfile and supervise/runit wrapper script

### PR DESCRIPTION
**Pull request by sneak**
This is a branch that adds a Dockerfile and a startup script to run the daemon inside a docker container.

### CODE REVIEW

**Comment by ITH4Coinomia** [comment]
@sneak Seems dockerfile still needs some update. Can you assign me this task if you're not working for this PR?

**Comment by daira** [comment]
Concept ACK.

**Comment by daira** [comment]
@ITH4Coinomia only members of the zcash github organisation or the original submitter of a PR can be assigned to it, but please feel free to work on this.

**Comment by ageis** [comment]
This is a "build and then run Zcash" Dockerfile, not an "install and run Zcash" Dockerfile. I would much prefer to see the binary obtained from our apt repository.

**Comment by sneak** [comment]
That defeats much of the purpose of using Docker. I can install your repo and download your binaries. I would like to be able to generate a container from source, so I can trust it. This allows me to build a container from a specific commit, easily reproduced.

**Comment by ageis** [comment]
@sneak Fair point, you're right. This is good to have. I built your Dockerfile and I got an error when I tried to attach to it:

```
addnode=159.203.242.63
/usr/local/bin/zcashd: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
./run: line 18: shasum: command not found
dd: error writing 'standard output': Broken pipe
rpcuser=rpcuser
```

Please add `libgomp1`, to your build deps, it's part of the runtime dependencies for zcashd.

**Comment by ageis** [comment]
Also, `shasum` is provided by `libdigest-sha-perl`, but `sha256sum` is in coreutils. We fixed this in `zcutil/fetch-params.sh` a while back, so please rebase on master.

**Comment by pklingem** [comment]
I rebased this against master on my machine and get the following errors when building:

```
{standard input}: Assembler messages:
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libbitcoin_server_a-metrics.Tpo .deps/libbitcoin_server_a-metrics.Po
mv -f .deps/libbitcoin_server_a-miner.Tpo .deps/libbitcoin_server_a-miner.Po
mv -f .deps/libbitcoin_server_a-main.Tpo .deps/libbitcoin_server_a-main.Po
make[2]: Leaving directory '/usr/local/src/zcash/src'
make[1]: *** [all-recursive] Error 1
Makefile:5320: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/usr/local/src/zcash/src'
make: *** [all-recursive] Error 1
Makefile:626: recipe for target 'all-recursive' failed
Command exited with non-zero status 2
521.47user 77.50system 6:48.50elapsed 146%CPU (0avgtext+0avgdata 1459208maxresident)k
0inputs+0outputs (11275major+36217724minor)pagefaults 0swaps
The command '/bin/sh -c mkdir -p /etc/zcash &&     ln -s /etc/zcash $HOME/.zcash-params &&     cd /usr/local/src/zcash &&     bash ./zcutil/fetch-params.sh &&     chmod a+rx /etc/zcash &&     chmod a+r /etc/zcash/* &&     time ./zcutil/build.sh -j$(nproc) &&     make install &&     cp -av ./depends/x86_64-unknown-linux-gnu/bin/* /usr/local/bin &&     rm /var/lib/zcash/.zcash-params &&     cd / &&     rm -rf /usr/local/src/zcash &&     rm -rf /var/lib/zcash/.ccache' returned a non-zero code: 2
```

**Comment by pklingem** [comment]
please ignore previous comment, I bumped my memory and it build successfully.

**Comment by daira** [comment]
This is now obsolete, according to @mdr0id.

**Comment by str4d** [comment]
This was superceded by #4455.

**Pull request closed without merging**
