### PR TITLE
Set release CFLAGS/CXXFLAGS to use -O3.

### PR DESCRIPTION
**Pull request by daira**
Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Review by str4d — APPROVED** [review]
utACK. I did test this change myself locally to `linux.mk` and confirmed it changes the flags output from `./configure`.

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
Transient failure (RPC test hang in prioritisetransaction.py, only on the Debian 9 builder).

**Comment by daira** [comment]
@zkbot retry

**Pull request merged**
