### PR TITLE
Have make clean delete fuzzing-related directories

### PR DESCRIPTION
**Pull request by defuse**

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot r+

**Comment by daira** [comment]
Probably a transient failure. @zkbot retry

**Comment by ebfull** [comment]
```
ccache: error: /home/zcbbworker/.ccache/ccache.conf: No such file or directory
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
Makefile:3436: recipe for target 'libbitcoin_server_a-sendalert.o' failed
make[2]: *** [libbitcoin_server_a-sendalert.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-deprecation.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
make[2]: Leaving directory '/home/zcbbworker/ubuntu1804-docker/ubuntu1804-k8s-big/build/src'
Makefile:6226: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/zcbbworker/ubuntu1804-docker/ubuntu1804-k8s-big/build/src'
make[1]: *** [all-recursive] Error 1
Makefile:633: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by mdr0id** [comment]
@zkbot retry

**Pull request merged**
