### PR TITLE
Refactor wallet note code for testing

### PR DESCRIPTION
**Pull request by str4d**
Part of #1329

### CODE REVIEW

**Comment by str4d** [comment]
This hasn't been compiled or tested yet (because my dev laptop is busy regenerating miner test blocks). If no one tries it in the next five or so hours, I will check it then (and force-push to replace the commits with working ones if there are any problems).

**Comment by str4d** [comment]
@ebfull compiles and tests pass :smile:

**Comment by ebfull** [comment]
ACK this is what I was picturing!

@zkbot r+

**Comment by str4d** [comment]
Rebased on latest and edited the second commit (that added tests) to pick up @bitcartel's `GetTxid() -> GetHash()` PR.

@zkbot r+

**Pull request merged**
