### PR TITLE
Update payment-api.md

### PR DESCRIPTION
**Pull request by bitcartel**
Add z_getoperationresult to documentation.

@ebfull This document might be updated again with a few notes, so let's merge closer to release.  Thanks.

### CODE REVIEW

**Comment by bitcartel** [comment]
@ebfull Change of plan... can we get this merged now, need to send link out to some folk.  Thanks and self-ACK.

**Comment by nathan-at-least** [comment]
ACK.

**Comment by ebfull** [comment]
ACK

@zkbot r+

**Comment by daira** [comment]
Post-hoc ACK.

**Pull request merged**
