### PR TITLE
Fix MacOS tests

### PR DESCRIPTION
**Pull request by str4d**
Includes code cherry-picked from upstream PR bitcoin/bitcoin#8270.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
Transient failure on one of the supported builders.

Looks like most of the errors are fixed. I need to do some more investigation into why `sec-hard` is still not detecting the binary type. And FWICT the RPC test failures are due to performance / memory limitations of the worker.

**Comment by str4d** [comment]
Simple `sec-hard` fix: I forgot to index into the tuple that `struct.unpack` returns.

@zkbot try

**Comment by str4d** [comment]
Uncovered another necessary `sec-hard` change.

@zkbot try

**Comment by str4d** [comment]
Okay, the only CI stage now failing is the RPC tests. It looks like the newer MacOS worker being set up encounters build issues due to using a newer LLVM, so we won't be able to immediately use it to run the RPC tests. So I'm happy to have this reviewed and merged as-is.

**Comment by bitcartel** [comment]
@str4d Who should be assigned as reviewer?  I skimmed the changes and "it looks fine" but I'm not testing on actual Mac hardware.

**Comment by ebfull** [comment]
Also LGTM but cannot test.

**Comment by mdr0id** [comment]
@str4d Currently running tests on native MacOSX (``Darwin mdevs-MacBook-Air.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64``), and build is stable/runs.

Minor issues found:

- dependency check doesn't validate missing pyblake2, zmq modules, prior to execution

- the #! change for python2 threw a fit, essentially due to a invalid path:
      resolved via `sudo ln -sf /usr/bin/python2.7 /usr/local/bin/python2`, otherwise ALL rpc tests fail per 
      full_test_suite.py execution
- some of the code appears to use old versions of modules that use `self.nodes` where nodes is no longer an attribute of X object.

Below is the RPC log output (rpc-tests.sh):
```
Tests completed: 48
successes 29; failures: 19

Failing tests: wallet_protectcoinbase.py wallet_mergetoaddress.py wallet_nullifiers.py listtransactions.py mempool_resurrect_test.py txn_doublespend.py txn_doublespend.py --mineblock getchaintips.py mempool_spendcoinbase.py mempool_reorg.py mempool_tx_expiry.py httpbasics.py proxy_test.py nodehandling.py blockchain.py zcjoinsplit.py zcjoinsplitdoublespend.py reorg_limit.py zmq_test.py
```
Otherwise majority of the tests did successfully run and pass. I am running the test suite again to get a full pass/fail list.

**Comment by mdr0id** [comment]
Seeing a few tests hang/fail for http related reasons, but making some progress:

```
Tests completed: 48
successes 39; failures: 9

Failing tests: wallet_protectcoinbase.py wallet_shieldcoinbase.py wallet_mergetoaddress.py wallet.py wallet_nullifiers.py mempool_nu_activation.py mempool_tx_expiry.py zcjoinsplit.py zkey_import_export.py

```

**Comment by str4d** [comment]
Note that because we can't see those RPC test failures in CI at the moment,
I'd prefer that we merge this PR as-is. Then once the new CI worker is up,
we can make another PR with the RPC test fixes.

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
