### PR TITLE
Add UniValue as subtree

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6637
- bitcoin/bitcoin#6239
- bitcoin/bitcoin#6379
- bitcoin/bitcoin#6456
- bitcoin/bitcoin#6788

### CODE REVIEW

**Comment by str4d** [comment]
Based on #1990, merge that first.

**Comment by str4d** [comment]
Note that commit 9ef5b78c1998509b8f1ccd76f0aee15140e384be (the UniValue version being squashed in) is the head of the branch I created for https://github.com/jgarzik/univalue/pull/35 (ie. UniValue 1.0.3 + the `size_t` patch).

**Comment by str4d** [comment]
Commands used to add UniValue as a subtree:

```
git remote add univalue_str4d https://github.com/str4d/univalue.git
git fetch univalue_str4d
git subtree add --prefix=src/univalue --squash univalue_str4d size_t
```

**Comment by daira** [comment]
ACK on the last three, Zcash-specific, commits.

**Comment by bitcartel** [comment]
Updated test which failed.

**Comment by bitcartel** [comment]
ACK

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
