### PR TITLE
Update debian/compat to version 13

### PR DESCRIPTION
**Pull request by janisozaur**
Compat version 13 is currently the recommended one.

An important change introduced in 10 was change of default to target parallel builds

https://github.com/Debian/debhelper/blob/5d1bb29841043d8e47ebbdd043e6cd086cad508e/debhelper.pod#compatibility-levels

### CODE REVIEW

**Comment by nuttycom** [comment]
@mdr0id @charlieok can you please review this?

**Review by charlieok — APPROVED** [review]
utACK

**Comment by janisozaur** [comment]
Shellcheck failed, but i can't see any correlation between my commit and that failure. Is there anything I should do?

**Comment by charlieok** [comment]
Yeah I don't see a correlation either. Not sure

**Comment by mdr0id** [comment]
utACK. The shellcheck error is something mentioned earlier today in the github action shared runner ubuntu22.04 update

**Pull request merged**
