### PR TITLE
Implement ZIP 216 consensus rules

### PR DESCRIPTION
**Pull request by str4d**
In addition to the specified consensus rules, we unconditionally enable
ZIP 216 in the following situations:

- Wallet code
  - Transaction building
  - Nullifiers for wallet notes
- Tests
- Benchmarks

Closes zcash/zcash#5201.

### CODE REVIEW

**Comment by str4d** [comment]
The actual consensus fix is in https://github.com/zkcrypto/jubjub/pull/46. Since that PR changes the default to the post-ZIP 216 behaviour, this PR (and https://github.com/zcash/librustzcash/pull/396 which it uses) expose flags to switch the behaviour in consensus-critical APIs. Non-consensus usage of `jubjub::*Point::from_bytes` will default to post-ZIP 216 behaviour.

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
I forgot to fix the API usage in one of the Rust tests.

@zkbot try

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
