### PR TITLE
Fix for centos and mac

### PR DESCRIPTION
**Pull request by xaoseric**
Added fetch-params-mac.sh for mac users, and changed shasum to sha256sum redhat based os fix

### CODE REVIEW

**Comment by daira** [comment]
Changing to ``sha256sum`` will fix some platforms and break others (see #776 and https://github.com/zcash/zcash/issues/1053#issuecomment-228526561). We should instead try ``sha256sum`` and fall back to ``shasum -a 256`` (as @ebfull originally suggested in https://github.com/zcash/zcash/pull/776#issuecomment-196099265 ).

**Comment by xaoseric** [comment]
@daira the fetch-params-mac.sh file solves that issue as Ubuntu and Debian already have sha256sum support. https://github.com/zcash/zcash/pull/1537/commits/8a8fdeb1b83473da20d79bcd44ba77e0cb0e4b0a

**Comment by xaoseric** [comment]
@daira i did try playing around with your suggestion, couldn't get it to work though, so if you want to take a look at it, feel free

**Comment by daira** [comment]
```
SHA256CMD="$(command -v sha256sum || echo shasum)"
SHA256ARGS="$(command -v sha256sum >/dev/null || echo -a 256)"
"$SHA256CMD" $SHA256ARGS filename
```

(It's harder with the correct quoting; if we assumed that the path to ``sha256sum`` had no special characters then it would be simpler.)

**Comment by daira** [comment]
Superceded by #1628.

**Pull request closed without merging**
