### PR TITLE
Fix the SIGHASH_SINGLE bug by checking for `1` return value

### LINKED ISSUE #1078: Fix the SIGHASH_SINGLE bug
If you try to do `SIGHASH_SINGLE` in an input for which there is no corresponding (same-index) output, then `SignatureHash` returns `1`. It is a known bug that at least some places (e.g. `CheckSig`) don't check for this error code, and so the bug is baked into Bitcoin's consensus rules. *Our new code* (JoinSplits) is checking for the error code when we call SignatureHash, which is inconsistent with those parts of Bitcoin. Fortunately, there are no bugs introduced by that since we always use `SIGHASH_ALL` for JoinSplits (so restricting the signature type was a good call!).

Should we fix the bug? There are only 2 calls (excluding ones in tests) that would need to have an error check added, but by fixing it we risk breaking Bitcoin tools which expect the bug to be present.

Here's the relevant code from `SignatureHash`:

```
uint256 SignatureHash(const CScript& scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType)
{
    static const uint256 one(uint256S("0000000000000000000000000000000000000000000000000000000000000001"));
    if (nIn >= txTo.vin.size() && nIn != NOT_AN_INPUT) {
        //  nIn out of range
        return one;
    }

    // Check for invalid use of SIGHASH_SINGLE
    if ((nHashType & 0x1f) == SIGHASH_SINGLE) {
        if (nIn >= txTo.vout.size()) {
            //  nOut out of range
            return one;
        }
    }
...
```

### PR DESCRIPTION
**Pull request by defuse**
Competes with #1079. Closes #1078.

### CODE REVIEW

**Comment by defuse** [comment]
I think those are the only two calls that need to have checks added. If we're going to merge this someone should carefully verify that. We could also get rid of the in-band signalling entirely and replace it with an exception.

**Comment by daira** [comment]
This looks okay, but I would prefer to remove the in-band signaling.

**Comment by defuse** [comment]
@daira: The alternative of removing in-band signalling is in #1088

**Comment by defuse** [comment]
This breaks tests right now

**Comment by defuse** [comment]
Also, I forgot to remove the other checks for one

**Comment by defuse** [comment]
Ugh, I made those comments on the wrong PR.

**Comment by ebfull** [comment]
Can this be closed in favor of #1088?

**Comment by defuse** [comment]
Closed in favor of #1088.

**Pull request closed without merging**
