### PR TITLE
remove virtual from class that is neither sub- nor super-

### PR DESCRIPTION
**Pull request by zancas**
Fixes: #4329

### CODE REVIEW

**Comment by zancas** [comment]
I have _only_ validated by runnning `make` and `./qa/zcash/full_test_suite.py btest`.

**Comment by zancas** [comment]
@oxarbitrage thoughts?

**Comment by daira** [comment]
Shrug, it's correct as-is. I'd rather we focus on things that are actually incorrect or error-prone.

**Comment by zancas** [comment]
Acknowledged.

**Pull request closed without merging**
