### PR TITLE
Partial revert of "Update links"

### PR DESCRIPTION
**Pull request by daira**
This partially reverts commit f459e43dc9f61979bc46ea143853cdf5e0241506. See #4904.

In summary, the rationale is that:
* Some of the changed files are from subtrees, which should be updated upstream.
* The licensing of four of the files under `build-aux/m4` is complicated and so changes to them should have required review with that in mind: https://github.com/zcash/zcash/blob/5b97cd27f83a95e4b9a3d50c3d198ad22f27df70/COPYING#L38-L44
* The changes to `contrib/debian/copyright` must also be reverted because those are in copies of specific versioned licenses.

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by rex4539** [comment]
> * Some of the changed files are from subtrees, which should be updated upstream.

https://github.com/bitcoin-core/secp256k1/pull/858
https://github.com/google/leveldb/pull/862
https://github.com/bitcoin-core/ctaes/pull/20

**Comment by str4d** [comment]
The leftover changes can be reviewed here: https://github.com/zcash/zcash/compare/83a4ae49b61f54455ae6f07a20c281364e1d4786...daira:daira-partial-revert-4904

**Review by str4d — APPROVED** [review]
ACK, I'm happy with the remaining changes.

**Comment by nuttycom** [comment]
@zkbot r+

**Comment by daira** [comment]
Nitpick: a comment typo was introduced in https://github.com/zcash/zcash/compare/83a4ae49b61f54455ae6f07a20c281364e1d4786...daira:daira-partial-revert-4904#diff-7dc86b52ccf856f995b8e8ae932dd893aeae83577d290beab7558a74969483d5R2

**Comment by str4d** [comment]
Transient failure. This PR can be retried as-is, or r+ed if the typo is fixed.

**Comment by daira** [comment]
I will fix the typo.

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
> > * Some of the changed files are from subtrees, which should be updated upstream.
> 
> [bitcoin-core/secp256k1#858](https://github.com/bitcoin-core/secp256k1/pull/858)
> [google/leveldb#862](https://github.com/google/leveldb/pull/862)
> [bitcoin-core/ctaes#20](https://github.com/bitcoin-core/ctaes/pull/20)

All of these have now been merged to the respective upstreams. (They may not yet have been included in releases.)

**Pull request merged**
