### PR TITLE
Bitcoin 0.12 cleanup PRs 2

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6631
- bitcoin/bitcoin#6664
  - Only the first commit (we already had the second through bitcoin/bitcoin#6825).
- bitcoin/bitcoin#6669
- bitcoin/bitcoin#6887
  - Only the non-QT parts.
- bitcoin/bitcoin#6962
- bitcoin/bitcoin#6822
  - Only first and third commits (we already had the second through an earlier PR).
- bitcoin/bitcoin#7136
  - Excludes Travis CI changes, and fixes to documents we don't have anymore.
- bitcoin/bitcoin#7084
- bitcoin/bitcoin#7509
- bitcoin/bitcoin#7617
- bitcoin/bitcoin#7726

Part of #2074.

### CODE REVIEW

**Comment by str4d** [comment]
This PR only requires one review, as it's all general changes that don't affect consensus or risk user funds.

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot retry

**Comment by str4d** [comment]
The retry will fail, because the test failed due to the "absurdly high fee" bound being altered (and changing the error message). When the retry fails, I'll push the fix and re-r+.

**Comment by str4d** [comment]
Fix pushed.

@zkbot r+

**Pull request merged**
