### PR TITLE
Add univalue crash test case.

### LINKED ISSUE #1122: Test Bitcoin's JSON deserialization with large amounts of data
Write a unit test in `src/gtest` to try to crash bitcoin's JSON deserialization code by sending it lots of data. The goal here is to reproduce a crash/failure that @bitcartel observed in the past (not while working on Zcash).

### PR DESCRIPTION
**Pull request by defuse**
Closes #1122. The point of this test was to try to reproduce a crash @bitcartel observed in the past. The test *does not* reproduce that crash, so **by accepting this PR we are giving up on trying to reproduce that crash.**

### CODE REVIEW

**Comment by bitcartel** [comment]
Could this be an encoding issue of some sort?

Passes:
const char *json_test_string_good = "{\"year\": 2016}";

Throws "couldn't parse the JSON" exception.  Replace 'ü' with 'u' and it works fine.
const char *json_test_string_bad = "{\"city\": \"Nürnberg\"}";

**Comment by defuse** [comment]
@bitcartel: Removing non-ASCII characters fixed the issue.

**Comment by defuse** [comment]
The test passes now, and the crash @bitcartel observed isn't reproduced. Unless @bitcartel has any other ideas, I think we should merge this and close #1122, meaning we're giving up on reproducing it.

**Comment by ebfull** [comment]
ACK+cov (no negative coverage impact is possible with this PR)

**Comment by bitcartel** [comment]
I don't think this should be merged because (1) the test data file I supplied is 2.31 MB in size which will impact git cloning (2) we now know the issue was related to non-ASCII characters in the the test data.

How about keeping/merging the test where we just use a few strings with non-ascii data (take from the test data file)?  Could be expanded to include UTF-8 and Unicode bytes to confirm behaviour.

**Comment by bitcartel** [comment]
@defuse Do you have time to add #1122 as a test and see if upstream has resolved this issue?  Thanks.

**Comment by ebfull** [comment]
@bitcartel Can this be closed now with the merge of #1313?

**Comment by ebfull** [comment]
I've closed this because we've switched to the `master` branch and reset homu.

**Pull request closed without merging**
