### PR TITLE
Release v5.1.0

### LINKED ISSUE #5973: Release v5.1.0
This release adds functionality that was missed in v5.0.0.

### PR DESCRIPTION
**Pull request by str4d**
Closes #5973.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK. I checked the release height.

**Review by daira — APPROVED** [review]
reACK dda0f792774bd2a9ec99ed326d2d3685c5a865d3

**Review by therealyingtong — APPROVED** [review]
utACK

**Pull request merged**
