### PR TITLE
Revert "Headers-first fix" to avoid a memory usage regression on IBD

### LINKED ISSUE #6268: Peak memory usage during initial block download causes OOM on 4GB machine
The steady-state memory utilization has been decreased by https://github.com/zcash/zcash/pull/6192, but initial block download on a 4GB machine still reproducibly fails with a kernel-delivered OOM kill:

```
Thank you for running a mainnet zcashd v5.3.0 node!
You're helping to strengthen the network and contributing to a social good :)

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.

     Downloading blocks | 19217 (1743840 headers) / ~1895760 (1%)
                        | [                                                  ]
           Next upgrade | Overwinter at block height 347500, in around 569 days
            Connections | 8
  Network solution rate | 43.819 MSol/s


Since starting this node 38 minutes, 5 seconds ago:
- You have validated 207387 transactions!

[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]
Killed
sasha_work@ibd-4gb-test-sasha:~/zcash$ 
```

```
2022-11-29T02:59:21.418407Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000001a4ec5b60203ad66ba1cb182358af44bf46ff069d9423c8a8ac41bda height=19213 bits=486582560 log2_work=45.56408 tx=131280 date=2016-11-30 05:17:46 progress=0.003452 cache=138.7MiB(65619tx)
2022-11-29T02:59:24.655578Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000002de5bcca31f042ccf17c8b6f18e34100864aec85052c4e12fb03cd97 height=19214 bits=486581581 log2_work=45.564265 tx=131282 date=2016-11-30 05:19:14 progress=0.003452 cache=138.7MiB(65620tx)
2022-11-29T02:59:24.846216Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000604ca0a57c62d30bfc2ebb4cb6fab6db4c1b48a2383ec3887366fc08 height=19215 bits=486583648 log2_work=45.564441 tx=131291 date=2016-11-30 05:10:05 progress=0.003452 cache=138.7MiB(65627tx)
2022-11-29T02:59:25.419974Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000049901e77b0f08be13c1b35381a277f481ac5e098fc416d1d270047e height=19216 bits=486583471 log2_work=45.564617 tx=131293 date=2016-11-30 05:24:12 progress=0.003452 cache=138.7MiB(65629tx)
2022-11-29T03:15:28.288206Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000ebb0ba310736eb3f881d505a2885bc43e44f5adb77e7ec40e8818ec height=19217 bits=486584411 log2_work=45.56479 tx=131295 date=2016-11-30 05:12:55 progress=0.003452 cache=138.7MiB(65631tx)
2022-11-29T03:16:28.125668Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000008544a65858de44919f99e89a3f52282572f99178e7226f4f83887cd7 height=19218 bits=486584637 log2_work=45.564962 tx=131296 date=2016-11-30 05:25:48 progress=0.003452 cache=138.7MiB(65632tx)
2022-11-29T03:19:07.810979Z  INFO main: ping timeout: 1201.417193s
2022-11-29T03:21:26.812092Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000d15854bdd6ce5bcb0197aaf4694d3bd30242250e797efcc930529ba height=19219 bits=486585467 log2_work=45.565131 tx=131304 date=2016-11-30 05:29:11 progress=0.003452 cache=138.7MiB(65633tx)
```

Here's the full log without the `ProcessNewBlock`s:
```
2022-11-29T02:38:31.621434Z  INFO main: Zcash version v5.3.0-60a43b96c
2022-11-29T02:38:31.623482Z  INFO Init: main: InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2022-11-29T02:38:31.626893Z  INFO Init: main: Using the 'shani(1way,2way)' SHA256 implementation
2022-11-29T02:38:31.644783Z  INFO Init: main: Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
2022-11-29T02:38:31.644828Z  INFO Init: main: Default data directory /home/sasha_work/.zcash
2022-11-29T02:38:31.644850Z  INFO Init: main: Using data directory /home/sasha_work/.zcash
2022-11-29T02:38:31.644876Z  INFO Init: main: Using config file /home/sasha_work/.zcash/zcash.conf
2022-11-29T02:38:31.644900Z  INFO Init: main: Using at most 125 connections (1024 file descriptors available)
2022-11-29T02:38:31.656629Z  INFO Init: main: Using 16 MiB out of 16 requested for signature cache, able to store 524288 elements
2022-11-29T02:38:31.663669Z  INFO Init: main: Using 8 MiB out of 8 requested for Sapling bundle cache, able to store 262144 elements
2022-11-29T02:38:31.670129Z  INFO Init: main: Using 8 MiB out of 8 requested for Orchard bundle cache, able to store 262144 elements
2022-11-29T02:38:31.670177Z  INFO Init: main: Using 0 threads for script verification
2022-11-29T02:38:31.671649Z  INFO main: scheduler thread start
2022-11-29T02:38:31.671694Z  INFO main: metrics-ui thread start
2022-11-29T02:38:31.672722Z  INFO Init: main: Loading Sapling (Spend) parameters from /home/sasha_work/.zcash-params/sapling-spend.params
2022-11-29T02:38:31.672740Z  INFO Init: main: Loading Sapling (Output) parameters from /home/sasha_work/.zcash-params/sapling-output.params
2022-11-29T02:38:31.672745Z  INFO Init: main: Loading Sapling (Sprout Groth16) parameters from /home/sasha_work/.zcash-params/sprout-groth16.params
2022-11-29T02:38:35.658252Z  INFO Init: main: Loading Orchard parameters
2022-11-29T02:38:46.924168Z  INFO Init: main: Loaded proof system parameters in 15.251353s seconds.
2022-11-29T02:38:46.929765Z  INFO Init: main: HTTP: creating work queue of depth 16
2022-11-29T02:38:46.930078Z  INFO Init: main: No rpcpassword set - using random cookie authentication
2022-11-29T02:38:46.930207Z  INFO Init: main: Generated RPC authentication cookie /home/sasha_work/.zcash/.cookie
2022-11-29T02:38:46.930247Z  INFO Init: main: HTTP: starting 4 worker threads
2022-11-29T02:38:46.933705Z  INFO Init: main: Using wallet wallet.dat
2022-11-29T02:38:46.933804Z  INFO Init: main: CDBEnv::Open: LogDir=/home/sasha_work/.zcash/database ErrorFile=/home/sasha_work/.zcash/db.log
2022-11-29T02:38:46.944823Z  INFO Init: main: Bound to [::]:8233
2022-11-29T02:38:46.944877Z  INFO Init: main: Bound to 0.0.0.0:8233
2022-11-29T02:38:46.944989Z  INFO Init: main: Cache configuration:
2022-11-29T02:38:46.945024Z  INFO Init: main: * Using 2.0MiB for block index database
2022-11-29T02:38:46.945049Z  INFO Init: main: * Using 120.0MiB for chain state database
2022-11-29T02:38:46.945070Z  INFO Init: main: * Using 328.0MiB for in-memory UTXO set
2022-11-29T02:38:46.946458Z  INFO Init: main: Opening LevelDB in /home/sasha_work/.zcash/blocks/index
2022-11-29T02:38:46.955479Z  INFO Init: main: Opened LevelDB successfully
2022-11-29T02:38:46.955590Z  INFO Init: main: Opening LevelDB in /home/sasha_work/.zcash/chainstate
2022-11-29T02:38:46.965050Z  INFO Init: main: Opened LevelDB successfully
2022-11-29T02:38:46.965118Z  INFO Init: main: LoadBlockIndexDB: last block file = 0
2022-11-29T02:38:46.965162Z  INFO Init: main: LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2022-11-29T02:38:46.965185Z  INFO Init: main: Checking all blk files are present...
2022-11-29T02:38:46.965206Z  INFO Init: main: LoadBlockIndexDB: transaction index disabled
2022-11-29T02:38:46.965225Z  INFO Init: main: LoadBlockIndexDB: insight explorer disabled
2022-11-29T02:38:46.965245Z  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled
2022-11-29T02:38:46.966835Z  INFO Init: main: Initializing databases...
2022-11-29T02:38:46.966920Z  INFO Init: main: Pre-allocating up to position 0x1000000 in blk00000.dat
2022-11-29T02:38:46.978323Z  INFO Init: main:  block index              33ms
2022-11-29T02:38:46.992855Z  INFO Init: main: nFileVersion = 5030050
2022-11-29T02:38:46.992928Z  INFO Init: main: Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total
2022-11-29T02:38:46.992951Z  INFO Init: main: ZKeys: 0 plaintext, 0 encrypted, 0 w/metadata, 0 total
2022-11-29T02:38:46.996336Z  INFO Init: main: Performing wallet upgrade to 60000
2022-11-29T02:38:47.588396Z  INFO Init: main: CWallet::NewKeyPool wrote 100 new keys
2022-11-29T02:38:47.606595Z  INFO Init: main:  wallet                  627ms
2022-11-29T02:38:47.607998Z  INFO main: txnotify thread start
2022-11-29T02:38:47.609532Z  INFO main: UpdateTip: new best hash=00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08 height=0 bits=520617983 log2_work=13 tx=1 date=2016-10-28 07:56:00 progress=0.000000 cache=0.0MiB(0tx)
2022-11-29T02:38:47.616086Z  INFO Init: main: mapBlockIndex.size() = 1
2022-11-29T02:38:47.616100Z  INFO Init: main: nBestHeight = 0
2022-11-29T02:38:47.616104Z  INFO Init: main: setKeyPool.size() = 100
2022-11-29T02:38:47.616107Z  INFO Init: main: mapWallet.size() = 0
2022-11-29T02:38:47.616110Z  INFO Init: main: mapAddressBook.size() = 1
2022-11-29T02:38:47.616398Z ERROR Init: main: Read: Failed to open file /home/sasha_work/.zcash/peers.dat
2022-11-29T02:38:47.616435Z  INFO Init: main: Invalid or missing peers.dat; recreating
2022-11-29T02:38:47.616494Z  INFO main: torcontrol thread start
2022-11-29T02:38:47.619317Z ERROR Init: main: Read: Failed to open file /home/sasha_work/.zcash/banlist.dat
2022-11-29T02:38:47.619331Z  INFO Init: main: Invalid or missing banlist.dat; recreating
2022-11-29T02:38:47.622371Z  INFO main: dnsseed thread start
2022-11-29T02:38:47.622414Z  INFO main: Loading addresses from DNS seeds (could take a while)
2022-11-29T02:38:47.624185Z  INFO main: addcon thread start
2022-11-29T02:38:47.624551Z  INFO main: net thread start
2022-11-29T02:38:47.624581Z  INFO main: opencon thread start
2022-11-29T02:38:47.624617Z  INFO main: msghand thread start
2022-11-29T02:38:48.667889Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=0.0.0.0:0, peer=1
2022-11-29T02:38:49.138347Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:45676, peer=2
2022-11-29T02:38:50.117363Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:55602, peer=3
2022-11-29T02:38:50.704739Z  INFO main: 60 addresses found from DNS seeds
2022-11-29T02:38:50.704757Z  INFO main: dnsseed thread exit
2022-11-29T02:38:50.781092Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:51078, peer=4
2022-11-29T02:38:52.841194Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:36356, peer=5
2022-11-29T02:38:54.623242Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:36916, peer=7
2022-11-29T02:38:59.088870Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:40632, peer=6
2022-11-29T02:39:03.725970Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895006, us=34.168.227.145:39934, peer=8
2022-11-29T02:54:55.852763Z  INFO main: Peer=6 is stalling block download, disconnecting
2022-11-29T02:55:09.259109Z  INFO main: connect() to 23.129.64.222:8233 failed after select(): Connection refused (111)
2022-11-29T02:55:10.276904Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895023, us=34.168.227.145:44536, peer=9
2022-11-29T02:56:54.894421Z  INFO main: Peer=9 is stalling block download, disconnecting
2022-11-29T02:57:09.519016Z  INFO main: connect() to 23.129.64.218:8233 failed after select(): Connection refused (111)
2022-11-29T02:57:33.561560Z  INFO main: receive version message: /MagicBean:5.3.0/: version 170100, blocks=1895026, us=34.168.227.145:59896, peer=10
2022-11-29T03:19:07.810979Z  INFO main: ping timeout: 1201.417193s
sasha_work@ibd-4gb-test-sasha:~/zcash$ 
```

### PR DESCRIPTION
**Pull request by daira**
Reverts #6231. Fixes #6268.

### CODE REVIEW

**Comment by softminus** [comment]
This _drastically_ reduces memory usage, at least during the beginning part of IBD
(I stopped it after `2022-12-03T03:20:24.054957Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000399fef0697a89dec74cffb4a2962e5ef4e0f56023c06918eca74240 height=222722 bits=471062695 log2_work=52.139439 tx=1597170 date=2017-11-20 06:17:44 progress=0.041880 cache=101.4MiB(3476tx)`):
Screenshot 2022-12-02 at 20 38 03
Screenshot 2022-12-02 at 20 42 49

**Comment by daira** [comment]
OK, this confirms that #6231 was a regression.

I suggest we should immediately put out a 5.3.2 hotfix that reverts #6231. Headers-first is really not so critical an optimization that we can't just revert it.

Then we can decide how / whether to reimplement the "headers-first" behaviour in a way that avoids the memory regression, on a more considered basis.

**Comment by miodragpop** [comment]
Wouldn't leaving headers-first behavior, but controlled via config option, be smarter than just dismissing it? You'll stay short for a valuable feedback about it's impact on sync times if nodes can't even try it (those with enough resources that is).

**Comment by daira** [comment]
> Wouldn't leaving headers-first behavior, but controlled via config option, be smarter than just dismissing it? You'll stay short for a valuable feedback about it's impact on sync times if nodes can't even try it (those with enough resources that is).

Since the only difference between v5.3.1 and v5.3.2 will be the reversion, users who want to try out headers-first can just do so using v5.3.1.

There's no justification for adding a config option for this long term. We want the headers-first behaviour unconditionally, once we have time to ensure that it doesn't regress memory usage. We have time to get it right without needing an option in v5.4.0. Adding a config option for the hotfix would be riskier than just reverting #6231 (what if we make a mistake?) and would take longer.

**Review by nuttycom — APPROVED** [review]
utACK. I verified that this reversion restores the codebase to not include the changes introduced by https://github.com/zcash/zcash/pull/6231/files

**Review by sellout — APPROVED** [review]
utACK. Compared side-by-side with original change, and I also agree that reversion is the correct hotfix.

**Comment by softminus** [comment]
Confirming that this lets initial block download complete (starting off with an empty datadir and blank config file) on a machine with 4GB of memory without an OOM! (it took a while because of the shielded-transaction-heavy blocks)

**Pull request merged**
