### PR TITLE
Set wget retry options for fetching parameters

### LINKED ISSUE #1196: Fetch-params.sh failed to download key because it doesn't retry for some HTTP status codes
Script failed to download the verification key during a build test:

http://ci.leastauthority.com:8010/builders/zcash/builds/285/steps/fetch-params.sh%20%28optional%29/logs/stdio

By default, wget will retry a download 20 times but not when it receives a fatal error, such as 404 or 500.  Updating the wget options could help e.g. http://superuser.com/questions/493640/how-to-retry-connections-with-wget

### PR DESCRIPTION
**Pull request by ageis**
This will retry upon refused connections and similar errors, wait 1 second before the next retry, time out after 10 seconds if no data is received or the connection times out, plus try an infinite number of times.

Resolves #1196.

### CODE REVIEW

**Comment by daira** [comment]
The only thing I'd question here is the infinite retries. If it fails, say, 50 times then it's not going to work at all, right? (Unless the network connection is down and comes back up, but the user would probably prefer to manually retry in that case.)

**Comment by bitcartel** [comment]
The default number of retries for wget is 20 which I think is acceptable.  Infinite retries could block the buildbot server.  We might also want to set/increase the timeout and read-timeout in case the user is on a mobile network: http://superuser.com/a/689340

**Comment by ageis** [comment]
@bitcartel I focused on timeout because "it's equivalent to specifying --dns-timeout, --connect-timeout, and --read-timeout, all at the same time." and I don't want these options to become too complex or long. Will increase it and update the retries.

**Comment by ageis** [comment]
How's this? 30 second timeout, 3 seconds wait before each try, 20 tries (default).

**Comment by bitcartel** [comment]
ACK

**Comment by daira** [comment]
ACK

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
