### PR TITLE
Test an assertion failure in the listaddresses RPC

### PR DESCRIPTION
**Pull request by defuse**

### CODE REVIEW

**Review by str4d — APPROVED** [review]
utACK

**Comment by str4d** [comment]
The one failing tests looks transient (it is unrelated to this PR, and passed on all but one CI builder).

**Review by defuse — COMMENTED** [review]
utACK

**Comment by daira** [comment]
Reminder that if a PR changes functionality (in this case the `listaddresses` RPC), the PR title shouldn't describe it solely in terms of a test change.

**Review by daira — COMMENTED** [review]
Post-hoc utACK

**Pull request merged**
