### PR TITLE
Make shielded requirements error "debug" level rather than an error.

### PR DESCRIPTION
**Pull request by ebfull**
These errors are getting annoying; they're not actually "errors" for the user it's displayed for, so let's make them debug events.

### CODE REVIEW

**Review by steven-ecc — APPROVED** [review]
utACK

**Review by steven-ecc — DISMISSED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK

**Review by str4d — APPROVED** [review]
utACK

**Pull request merged**
