### PR TITLE
When rewinding, remove insufficiently-validated blocks

### LINKED ISSUE #3100: Overwinter: after a block rewind, syncing to the correct branch can fail, and reindex is required
We found an issue in a recent test of activating Overwinter on Testnet, specifically with block rewinding.

Background:

Testnet
- Sprout nodes (running 1.0.15)
- Overwinter nodes (running custom 1.0.15 called 'Federer' set to activate at block 200000 instead of the scheduled 207500)

Test 1 (Success)
Both branches of the fork mine blocks successfully.  We stop a Sprout
node and launch a Federer node using the datadir of the Sprout node.  As
expected we see a message asking us to perform a reindex since the
Sprout chain is >= 100 blocks ahead of the fork point.

Test 2 (Failed)
Both branches of the fork mine blocks successfully but we stop the
Federer mining early (it was around 25 blocks).  We stop and launch a
Sprout node using the datadir of the Federer node.  It rewinds to block
199999 but cannot sync with the Sprout chain, because block 200000 was
previously invalidated by the Federer node and assigned the state:
BLOCK_FAILED_VALID | BLOCK_VALID_TREE.

We believe this issue is because we have not changed the block header
format from Sprout and the Overwinter network upgrade.  So peers
advertising the same protocol version stay connected and send block
headers to each other which validate fine, but the blocks are not valid
as they use different transaction formats.

See here for more info:

https://chat.zcashcommunity.com/channel/zcash-dev?msg=29QaGdz9nSFZsmDQy

https://chat.zcashcommunity.com/channel/zcash-dev?msg=z4ph6M5GgJkdea4FC

### PR DESCRIPTION
**Pull request by str4d**
If a block is insufficiently-validated against a particular branch ID, then we
cannot guarantee that even the block header will be valid under the actual
consensus rules the node will want to apply. Instead require that the blocks are
completely re-validated, by removing them from the block index (which is
equivalent to reducing their validity to BLOCK_VALID_UNKNOWN).

Closes #3100.

### CODE REVIEW

**Comment by str4d** [comment]
Related to #3100, which is tangentially similar.

**Comment by str4d** [comment]
That's what I was blocking on - trying to figure out a nice way to test it. I think I'll have to do the not-so-nice thing where we emulate the "switching clients" behaviour by stopping and starting nodes in an RPC test.

**Comment by str4d** [comment]
I have (what I believe is) an RPC test for `RewindBlockIndex`, and it shows a bug in this PR. Do not merge yet.

**Comment by str4d** [comment]
This PR now has an RPC test that fails before the fix, and passes afterwards.

**Comment by str4d** [comment]
Force-pushed to fix PyFlakes warning 😄

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
