### PR TITLE
Add buster to the list of suites used by gitian

### PR DESCRIPTION
**Pull request by charlieok**
Revision of this earlier PR, based from commit a88a98af235a2eb83e2fcdb18d26714d0cb1a1ad
https://github.com/zcash/zcash/pull/5314

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

**Comment by charlieok** [comment]
successfully built stretch (debian 9) and buster (debian 10) binaries

**Comment by daira** [comment]
Should we add `bullseye`, when #5323 is merged?

**Comment by charlieok** [comment]
I encountered lxc-related errors when attempting to do the same with `bullseye`

**Comment by charlieok** [comment]
also, I think 5323 is fairly independent of the this change.

**Review by str4d — APPROVED** [review]
utACK

**Pull request merged**
