### PR TITLE
Remove hardfork from special testnet difficulty rules

### LINKED ISSUE #1131: Remove block-based hardfork in testnet
https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/pow.cpp#L36

### PR DESCRIPTION
**Pull request by str4d**
Closes #1131

### CODE REVIEW

**Comment by str4d** [comment]
This needs to be merged in the next release that resets the testnet blockchain.

**Comment by ebfull** [comment]
ACK `9e0713f`

**Comment by bitcartel** [comment]
ACK `9e0713f`

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
