### PR TITLE
Integrate production Founders' Reward keys

### LINKED ISSUE #870: Integrate production Founders' Reward keys into ChainParams.
The plan is to pay the Founders' reward to a transparent multisig address. The one used on the testnet is just temporary. Because it will receive 10% of the eventual monetary base, the keys for this address need to be particularly securely generated and stored (maybe in hardware wallets?) See also https://github.com/zcash/zcash/issues/125#issuecomment-196629653 , which suggests paying to different addresses (baked in at the start) in subintervals of the 4-year reward period.

### PR DESCRIPTION
**Pull request by str4d**
Also removes the Founders' Reward override from #1398.

Closes #870

### CODE REVIEW

**Comment by ebfull** [comment]
ACK

**Comment by ebfull** [comment]
@zkbot r+

**Comment by str4d** [comment]
Self-ACK

**Comment by str4d** [comment]
@zkbot retry

**Comment by str4d** [comment]
Rebased to remove the regtest genesis block change, because Bitcoin's RPC test *framework* (not any specific test) has an unspecified dependency on the specific value of nTime for the regtest genesis block.

Self-ACK because the rebase only removed genesis-block-related changes from the PR, and in particular did not alter the Founders' Reward commits.

@zkbot r+

**Comment by daira** [comment]
Post-hoc ACK (did not check the addresses against the fr-pubkeys repo; I assume that's already been done).

**Pull request merged**
