### PR TITLE
Backport RPC test harness PRs

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:
- https://github.com/bitcoin/bitcoin/pull/6548
- https://github.com/bitcoin/bitcoin/pull/6804
  - Just the coverage backend, not the flag to enable it for all RPC tests.
- https://github.com/bitcoin/bitcoin/pull/7744
- https://github.com/bitcoin/bitcoin/pull/9832
  - Excludes `wallet-hd.py` change (missing bitcoin/bitcoin#8309).

Part of #2074.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
Fixed some pyflakes-detected bugs; I tweaked the individual commits to address them. I also ran a couple of the RPC tests locally to check that they passed.

@zkbot try

**Comment by mdr0id** [comment]
@rex4539 Is it possible to check this PR on your Mac when you get a cycle? It would be very much appreciated. 

Otherwise, so far looks good modulo Windows. The only thing that might cause an issue was `dev/null` paths, but this PR appears to remove them anyway.

**Comment by rex4539** [comment]
```
Tests completed: 73
successes 73; failures: 0
```

**Comment by str4d** [comment]
@mdr0id yep, the backported PRs included the change that you had already made for Windows support, as well as a subsequent change that removes them entirely.

**Comment by mdr0id** [comment]
@zkbot r+

**Comment by str4d** [comment]
Looks like a transient failure.

@zkbot retry

**Pull request merged**
