### PR TITLE
Closes #1680, temporary fix for rpc deadlock inherited from upstream.

### LINKED ISSUE #1680: zcashd thread deadlock
Zcashd experiences thread hangs under load and RPC becomes totally unresponsive.  Must be killed with -9 and restarted. I've attached to zcashd with gdb and dumped a stack trace of all threads:

http://pastebin.com/raw/Y1sGruD8

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by ebfull** [comment]
Let's have a ticket regarding re-enabling this (and other things mentioned in the comments) and reference the ticket from the comments in this PR.

**Comment by bitcartel** [comment]
@ebfull Added ticket #1856 to comments.  Please review and ACK.

**Comment by ebfull** [comment]
ACK

@zkbot r+

**Comment by str4d** [comment]
@bitcartel per [the test failure](https://ci.z.cash/builders/zcash/builds/205/steps/rpc-tests.sh/logs/stdio), the RPC test `httpbasics.py` needs updating.

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
