### PR TITLE
Increase block size limit to 2MB.

### LINKED ISSUE #765: 2 MB blocksize
In the Great Bitcoin Schism, both sides are converging on 2 MB blocks being okay, and the current remaining disagreements are about when to schedule a hard-fork upgrade of Bitcoin from 1 MB blocks to 2 MB blocks (sooner vs. later, before or after rolling out segwit, and possibly with some kind of user voting protocol to do "market research" about whether the users want it).

I think Zcash should start life with 2 MB blocksize. We can take the patch being maintained by Bitcoin Classic.

I've asked our Technical Advisory Board about this (in addition to asking about https://github.com/zcash/zcash/issues/764, since this and that compound with one another), and none of them raised a warning flag.

### PR DESCRIPTION
**Pull request by ebfull**
http://gavinandresen.ninja/a-guided-tour-of-the-2mb-fork

Closes #765.

### CODE REVIEW

**Comment by nathan-at-least** [comment]
I want us to think more carefully about also changing sigop limits before accepting this. On my reading list: http://diyhpl.us/wiki/transcripts/scalingbitcoin/alternatives-to-block-size-as-aggregate-resource-limits/

**Comment by nathan-at-least** [comment]
Can we add a performance test that creates and verifies a transaction of maximum possible size?

Thinking about this more, even if it is a DoS vector, I might be comfortable releasing a resource limit after our 1.0 launch.

**Comment by nathan-at-least** [comment]
NACK (temporary)

@sean and I decided the DoS vector is worrisome, so we want to postpone this patch until we have performance tests for those vectors and the baseline measurements. I'll file a ticket for those performance measurements.

**Comment by zookozcash** [comment]
Grumble grumble. Fine, but do me a favor and include estimation of the costs of generating that DoS-block while you're at it. ;-)

**Comment by nathan-at-least** [comment]
Testing ticket is #971, @zookozcash I'll respond to your request there.

**Comment by defuse** [comment]
ACK on the approach (I checked the places where the constants are used and compared it to the Bitcoin-XT patch).

**Comment by ebfull** [comment]
Not blocking this on #1046.

@zkbot r+

**Comment by str4d** [comment]
I thought the idea was to merge #1046 first so we could observe the benchmark changes of this PR landing, but okay.

**Comment by ebfull** [comment]
Hm, I thought we just wanted to *have* the measurement so we could assess changes to the difficulty adjustment algorithm or block time interval.

**Comment by str4d** [comment]
Per @nathan-at-least in #971:

> With these in place, we can track performance changes as we change limit constants or introduce new limits.

The limits he refers to are block size limits, not the difficulty adjustment algorithm or block time interval (which has no impact on the time to create or validate a large transaction).

**Comment by str4d** [comment]
Also:

> Before we land #962 (which closes #765), let's add two performance tests:

But too late now. I *could* try and fake that data by rebasing #1046 to just before this PR merged and then manually uploading the resulting measurements after manually running them on the CI server, but then they won't actually correspond to a "real" commit id...

**Comment by str4d** [comment]
(I'd also have to fake the data for *this* PR too, because the CI server isn't even running the tests in #1046 yet...)

**Comment by str4d** [comment]
Note that manually faking this data would only benefit the benchmark graphs. It would leave the benchmark graphss inconsistent with the log output of the CI server, so e.g. the per-run timing data, and the massif logs, would not be stored anywhere and would be lost.

We will not have this data before the next release, because doing this faking is going to take up more of my time than I have available for at least the next few weeks.

**Pull request merged**
