### PR TITLE
Check chainValueZat when checking value pool monitoring

### PR DESCRIPTION
**Pull request by str4d**
Addresses https://github.com/zcash/zcash/pull/2795#discussion_r157343660

### CODE REVIEW

**Comment by arcalinea** [comment]
Looks simple enough, but I got what looks like an unrelated build error on this branch?
```
Zcash/zcash/src/gtest/test_metrics.cpp:96: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
gtest/zcash_gtest-test_random.o:/Zcash/zcash/src/gtest/test_random.cpp:8: more undefined references to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' follow
```

**Comment by str4d** [comment]
We need to add this to a dev guide somewhere: do a `make clean` and try
again. It's caused my mismatched Google Test libraries and headers, which
happens when switching between older and newer branches.

**Comment by arcalinea** [comment]
Ah ok, there's actually a Troubleshooting wiki I can add this to.

**Comment by arcalinea** [comment]
```
=== Running testscript wallet_protectcoinbase.py ===
Traceback (most recent call last):
  File "Zcash/zcash/qa/rpc-tests/wallet_protectcoinbase.py", line 9, in <module>
    from test_framework.mininode import COIN
  File "Zcash/zcash/qa/rpc-tests/test_framework/mininode.py", line 33, in <module>
    from pyblake2 import blake2b
ImportError: No module named pyblake2
!!! FAIL: wallet_protectcoinbase.py !!!
````

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
