### PR TITLE
Generalize NU peer management test and make it include Blossom and Heartwood

### PR DESCRIPTION
**Pull request by daira**

### CODE REVIEW

**Comment by daira** [comment]
I suggest reviewing with "Hide whitespace changes" set; that produces a more coherent diff.

**Comment by daira** [comment]
@zkbot r+

**Comment by str4d** [comment]
Failed due to pyflakes errors (unused imports).

**Comment by daira** [comment]
Review needed for the pyflakes fix.

**Comment by ebfull** [comment]
@zkbot r+

**Comment by mdr0id** [comment]
TIL: dataclasses :nerd_face:

**Comment by ebfull** [comment]
```
=== Running testscript p2p_nu_peer_management.py ===
  File "/home/zcbbworker/debian9-docker/debian9-k8s-big/build/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/zcbbworker/debian9-docker/debian9-k8s-big/build/qa/rpc-tests/p2p_nu_peer_management.py", line 122, in run_test
    assert_equal((10+e)*len(EPOCHS[e:]), len(self.nodes[0].getpeerinfo()))
  File "/home/zcbbworker/debian9-docker/debian9-k8s-big/build/qa/rpc-tests/test_framework/util.py", line 537, in assert_equal
    raise AssertionError("(left == right)%s\n  left: <%s>\n right: <%s>" % (message, str(expected), str(actual)))
Initializing test directory /tmp/test7r02n3cn
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
Upgrade Overwinter active
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170003
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170002
Upgrade Sapling active
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170006
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170008
MiniNode: Connecting to Bitcoin Node IP # 127.0.0.1:11340 using version 170010
Assertion failed: (left == right)
  left: <36>
 right: <34>
Stopping nodes
Cleaning up
Failed
!!! FAIL: p2p_nu_peer_management.py (17s) !!!
```

**Comment by daira** [comment]
Can reproduce. Looks to be a race condition (the RHS of the assertion is also sometimes 35).

**Comment by daira** [comment]
So, I fixed the race condition, but it still occasionally fails because node 0 doesn't record a "Version must be %d or greater" reject message for all the peers that we expect. I don't know why not.

**Comment by daira** [comment]
Oops, deleted the branch accidentally, and GitHub won't let me reopen this PR (even though the branch now exists again). I'll open a new one.

**Pull request closed without merging**
