### PR TITLE
Closes #1371 by updating signed message

### LINKED ISSUE #1371: Change strMessageMagic to "Zcash Signed Message:\n";
https://github.com/zcash/zcash/blob/master/src/main.cpp#L93

This is used by the signmessage and verifymessage RPC commands. See also https://github.com/trezor/trezor-mcu/commit/e0e190b3dc29bcb0f6ab9699c439fe7bfbcde370#diff-7764c71ab044fb40d606b78c4ba329e1R31 (Trezor firmware update).

Ref #826.

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by str4d** [comment]
utACK (but it's trivial).

Are there any hard-coded tests that need updating?

**Comment by bitcartel** [comment]
Couldn't find any.  I just ran test_bitcoin and zcash_gtest to make sure and they both passed.

**Comment by daira** [comment]
utACK. Should we have a test? (I don't consider it critical.)

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
love you @zkbot

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Pull request merged**
