### PR TITLE
Add -Wformat -Wformat-security to the build.

### LINKED ISSUE #915: Re-enable --enable-hardening security features
When we added the `-O0` flag to disable optimization, that disabled `FORTIFY_SOURCE` security features. You can see the warnings saying it requires optimization to be enabled in the build output. We have to re-enable optimization (and make sure `--enable-hardening` is on) before we release 1.0.

### PR DESCRIPTION
**Pull request by defuse**
Closes #915.

### CODE REVIEW

**Comment by daira** [comment]
utACK. Should have no effect on coverage.

**Comment by defuse** [comment]
NACK: I should have added this to `configure.ac` so that it also gets added to the libzcash build.

**Comment by daira** [comment]
@defuse This can still get into z9 if you make that change now; otherwise not.

**Comment by defuse** [comment]
WTF, something really weird happened with GitHub when I rebased. It says the commit was authored by zkbot and `doc/payment-api.md` is shown in the diff? I'll just recreate the PR

**Comment by defuse** [comment]
Superseded by #1300.

**Pull request closed without merging**
