### PR TITLE
Pass parameter paths as native strings to librustzcash

### PR DESCRIPTION
**Pull request by str4d**
Fixes a user-reported crash when starting on Windows with a Cyrillic non-UTF-8 locale.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
Rust dependency issue.
```
Building librustzcash...
mkdir -p /home/zcbbworker/latent-0/debian8/build/depends/work/build/x86_64-unknown-linux-gnu/librustzcash/0.1-15ffc5364ae/.
cd /home/zcbbworker/latent-0/debian8/build/depends/work/build/x86_64-unknown-linux-gnu/librustzcash/0.1-15ffc5364ae/.; PATH="/home/zcbbworker/latent-0/debian8/build/depends/x86_64-unknown-linux-gnu/native/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"   cd librustzcash && cargo build --frozen --release        && cd ..
/bin/sh: 1: cargo: not found
funcs.mk:257: recipe for target '/home/zcbbworker/latent-0/debian8/build/depends/work/build/x86_64-unknown-linux-gnu/librustzcash/0.1-15ffc5364ae/./.stamp_built' failed
make: *** [/home/zcbbworker/latent-0/debian8/build/depends/work/build/x86_64-unknown-linux-gnu/librustzcash/0.1-15ffc5364ae/./.stamp_built] Error 127
make: Leaving directory '/home/zcbbworker/latent-0/debian8/build/depends'
```

**Comment by str4d** [comment]
Pushed a commit that fixes the CI problem. @radix42 confirmed the fix locally.

@bitcartel that is likely due to the bug I just fixed, which mean that your system Rust installation was being used. If it's an older version than 1.28.0, I would not be surprised there are errors.

**Comment by ebfull** [comment]
re-ACK

**Pull request merged**
