### PR TITLE
Include Orchard bundle in transaction dynamic usage

### PR DESCRIPTION
**Pull request by str4d**
This was missed in #5202.

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

**Comment by str4d** [comment]
I'm going to hold off merging this, as it's low-priority and other PRs will be bumping the orchard crate revision.

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
Rebased to fix conflict. We can merge this now that the `orchard` crate version has been bumped.

@zkbot r+

**Pull request merged**
