### PR TITLE
Remove CheckProofOfWork errors from logs

### PR DESCRIPTION
**Pull request by oxarbitrage**
To fix https://github.com/zcash/zcash/issues/4029 bitcoin patch(https://github.com/bitcoin/bitcoin/pull/7459) was ported.

### CODE REVIEW

**Comment by ebfull** [comment]
utACK

**Comment by str4d** [comment]
Note: in future please cherry-pick commits from upstream where possible, for more accurate attribution. I'm not going to block this PR on doing so.

**Comment by oxarbitrage** [comment]
Got it, will do that. thanks @str4d

**Comment by mdr0id** [comment]
@zkbot r+

**Pull request merged**
