### PR TITLE
Update RPC test_framework to allow execution on Windows with Python 2.7

### PR DESCRIPTION
**Pull request by mdr0id**
Using https://github.com/zcash/zcash/pull/3780, this allows a user to run the RPC stack in a native Windows environment. Once reviewed/approved, this will serve as the Python2.7 snapshot so we can begin updating the entire RPC stack to Python3+ conventions.

### CODE REVIEW

**Comment by mdr0id** [comment]
@zkbot try

**Comment by daira** [comment]
What's the status of this PR?

**Comment by mdr0id** [comment]
This can be appended to #4236. I need to go sanity check these minor fixes still allow RPCs to run gracefully on a native Windows host. Also need to see what upstream is currently doing.

**Comment by mdr0id** [comment]
Closing due to Python 2 EOS. Other PRs are now in master that are upholding Python3 conventions

**Pull request closed without merging**
