### PR TITLE
Remove OpenSSL

### LINKED ISSUE #145: Remove OpenSSL dependency. Ref: NCC-2016-007
I hear bitcoin-core plans to remove OpenSSL as a dependency (at least in the consensus path) as it migrates to libsecp256k1.  I _think_ it may be using the latter today for signatures and openssl for verification in a recent release or dev branch.

To close this ticket, find and document answers to these questions:
- Does upstream `v0.10.0` use `libsecp256k1` for signatures in production?
- Does upstream `v0.10.0` use `libsecp256k1` for verification in production?
- How certain is the plan to rely entirely on `libsecp256k1` for sig/verify?
- Are there already (upstream) dev branches or patches which do so?
- If upstream does this, will it still use OpenSSL for other purposes?

-and finally:
- Does ZC-specific code use OpenSSL for anything?

### PR DESCRIPTION
**Pull request by str4d**
Includes changes cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#7095
- bitcoin/bitcoin#11024
- bitcoin/bitcoin#17165
  - Only the commit removing SSL lib detection (we have long since removed the rest).
- bitcoin/bitcoin#17265
  - We had already migrated away from OpenSSL for randomness.
- bitcoin/bitcoin#17515
  - Only the second commit.

Closes #145.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
Blocking this PR on https://github.com/zcash/zcash/pull/4643, which makes some changes that remove merge conflicts I'd rather not unpick.

**Comment by str4d** [comment]
@zkbot try

**Comment by daira** [comment]
https://github.com/zcash/zcash/pull/4484#issuecomment-622391495

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by str4d** [comment]
ACK the commits pushed by @daira.

**Review by daira — APPROVED** [review]
utACK (but I can't review my own changes, i.e. the last 5 commits).

**Comment by daira** [comment]
@nuttycom can you also review the last 4 commits?

**Review by nuttycom — APPROVED** [review]
utACK of last 4 commits.

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
tenor (1)

**Comment by daira** [comment]
This broke the native macOS build: #4755. I'm on it.

**Pull request merged**
