### PR TITLE
[WIP] googlemock test script

### PR DESCRIPTION
**Pull request by nathan-at-least**

### CODE REVIEW

**Comment by defuse** [comment]
Note that #895 includes this stuff instead of being a PR on top of this stuff, since that would have shown up as a PR in @nathan-at-least's repository instead of this one and we'd lose track of it.

**Comment by defuse** [comment]
@nathan-at-least: I got confused by this PR and based my branch on top of it, when this stuff (or the equivalent) is already in `.latest`. Can it be closed?

**Comment by ebfull** [comment]
This is already merged into master AFAIK, @nathan-at-least I will close this PR soon unless you object.

**Comment by ebfull** [comment]
Closing this as I mentioned.

**Pull request closed without merging**
