### PR TITLE
Fix the use of 0 as expiryheight in createrawtransaction, to disable expiry

### LINKED ISSUE #4132: Unable to disable Transaction expiry
Hi,

Is there a way to set  `expiryheight` to be unlimited when generating a zcash transaction through the rpc or in the daemon config file?

It says [here](https://github.com/zcash/zips/blob/master/zip-0203.rst#specification) that this is possible by setting the expiration to be `0`, but I couldn’t find how to configure this.

I tried to call the `createrawtransaction` rpc method by passing `0` as below:

`raw_tx = self.rpc.createrawtransaction(in_txn, outputs, 0, 0)`

But it looks like the minimum for the expiryheight in the createrawtransaction is `4`. 
I think this where the error that I am hitting is thrown,

https://github.com/zcash/zcash/blob/424d8b1af52d0c84812de69657b4a596afd7c22e/src/rpc/rawtransaction.cpp#L546

and this is due to the fact that `TX_EXPIRING_SOON_THRESHOLD` is set to `3` and passing `expiryheight` as `0` to disable the transaction expiry doesn't seem to be possible. 

Passing the `-txexpirydelta=0` when starting the node doesn't seem to work either, it accepts at least `4`

### PR DESCRIPTION
**Pull request by daira**
fixes #4132

### CODE REVIEW

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
Unexplained failure on the kitchensink builder :-/

```
mv -f wallet/test/.deps/test_test_bitcoin-wallet_tests.Tpo wallet/test/.deps/test_test_bitcoin-wallet_tests.Po
Makefile:5235: recipe for target 'test/test_test_bitcoin-rpc_wallet_tests.o' failed
make[2]: *** [test/test_test_bitcoin-rpc_wallet_tests.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/admin/latent/debian8-kitchensink/build/src'
```

@zkbot retry

**Comment by str4d** [comment]
We are holding off merging this until #4060 is merged (as this PR is simpler to re-review after a rebase).

**Comment by Eirik0** [comment]
@zkbot r+

**Pull request merged**
