### PR TITLE
Update timedata.cpp to fix error message string from bitcoin core to zcash

### PR DESCRIPTION
**Pull request by amgadabdelhafez**
Changing error message string from bitcoin core to zcash. fixes issue #2336

### CODE REVIEW

**Comment by arcalinea** [comment]
Could you actually capitalize the z in "Zcash"?

Thanks @amgadabdelhafez !

**Comment by amgadabdelhafez** [comment]
Z Capitalized. :)

**Comment by nathan-at-least** [comment]
@zkbot r+

**Comment by nathan-at-least** [comment]
@zkbot retry

**Pull request merged**
