### PR TITLE
Track the correct change witness across chained joinsplits when notes are shuffled

### PR DESCRIPTION
**Pull request by bitcartel**
https://github.com/zcash/zcash/pull/1797#issuecomment-258912128

### CODE REVIEW

**Comment by bitcartel** [comment]
@daira This PR is for #1819

**Comment by ebfull** [comment]
ACK I helped @bitcartel work through this.

I really think this code needs to be refactored eventually with some kind of transaction builder abstraction.

**Comment by ebfull** [comment]
This can be `r+`'d anytime @bitcartel, but can you check that `GenIdentity` is not made stale code by this PR? I can't remember.

**Comment by str4d** [comment]
utACK. Nice work @bitcartel and @ebfull!

**Comment by bitcartel** [comment]
@ebfull `GenIdentity` is still used in `gtest/test_random.cpp`.

I'm not going to `r+` this just yet, want to run more tests.

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
