### PR TITLE
Release process for z8.  Issue #1140.

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by str4d** [comment]
LGTM

**Comment by nathan-at-least** [comment]
ACK.

Were there no changes to the process that need to be reflected in `./doc/release-process.md`?

**Comment by bitcartel** [comment]
Following same process as outlined in document.

**Comment by bitcartel** [comment]
ACK
@zbkot r+

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by ebfull** [comment]
Post hoc ACK

**Pull request merged**
