### PR TITLE
Unwind #1144 txid malleability

### PR DESCRIPTION
**Pull request by bitcartel**
This PR unwinds #1144, retaining GetTxid() as an alias for GetHash() to avoid having to rename across many files and any code in progress.

The txid gtest has been updated to verify that GetTxid() returns the same result as GetHash().

Both zcash-gtest and test_bitcoin pass.

Reviewers: It's easiest to review the 5 commits in chronological order.  Each commit is quite small.  Test files that have been rolled back (bloom_tests, script_invalid, script_valid) appear to be a big change, so it's easier to diff against the commit mentioned in the log.

### CODE REVIEW

**Comment by nathan-at-least** [comment]
ACK on diff review; I didn't do test coverage review.

Also, I haven't decided if we do want to roll this back; I'm still learning about the security findings.

**Comment by nathan-at-least** [comment]
We've decided to merge this for Beta 1 and roll back this feature.

**Comment by ebfull** [comment]
I want us to get rid of the `GetTxid`/`GetHash` dichotomy and do a complete revert of #1144. It's not too tricky to see that the revert was done properly, just a git diff is needed.

**Comment by bitcartel** [comment]
@ebfull I can add a commit to refactor GetTxid() calls as GetHash() and then remove that method completely.  Is that ok?

**Comment by ebfull** [comment]
@bitcartel That would be fine with me! :)

**Comment by bitcartel** [comment]
Note that the source tree will contain three references to a method getTxID() used by the QT gui.  The capitalization is different from the method we removed.

**Comment by ebfull** [comment]
We're gonna wait until the last second to merge this that way our work on `latest` for the RPC can play nicely with the testnet before beta.

**Comment by daira** [comment]
utACK+cov.

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
Thanks!

@zkbot r+

**Pull request merged**
