### PR TITLE
Delete SignatureHash from python script framework

### PR DESCRIPTION
**Pull request by oxarbitrage**
Fixes https://github.com/zcash/zcash/issues/4004

Code is not used anywhere.

### CODE REVIEW

**Comment by str4d** [comment]
Concept ACK, but let's wait until #4236 is in; if this were to conflict, this PR should be easier to rebase than the other way around.

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Pyflakes failures - there are imports that are no longer used after this code is removed.

**Comment by rex4539** [comment]
```
qa/rpc-tests/test_framework/script.py:14: 'test_framework.mininode.CTransaction' imported but unused
qa/rpc-tests/test_framework/script.py:14: 'test_framework.mininode.CTxOut' imported but unused
qa/rpc-tests/test_framework/script.py:14: 'test_framework.mininode.hash256' imported but unused
```

**Comment by oxarbitrage** [comment]
Thank you guys, please retry when possible.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
