### PR TITLE
Remove redundant HaveJoinSplitRequirements function call

### LINKED ISSUE #2972: Optimise calls to HaveJoinSplitRequirements
Currently we call `HaveJoinSplitRequirements` both in `CheckTxInputs` (which is called by `ContextualCheckInputs`), and directly inside `AcceptToMemoryPool` and `ConnectBlock`. This means that the check inside `CheckTxInputs` should never fail, assuming there are no other call paths and we are locking correctly. We should check this, and if we can then we should remove redundant calls.

### PR DESCRIPTION
**Pull request by evanlimanto**
Fixes #2972.

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot try

**Comment by daira** [comment]
Test failure (due to pyflakes warnings) seems unrelated to this PR. @zkbot retry

**Comment by daira** [comment]
Needs three ACKs since this is critical consensus code.

**Comment by bitcartel** [comment]
Will review but prioritising some other tickets first.

**Comment by bitcartel** [comment]
Concept NACK.  `CheckTxInputs` is called by test `coins_tests.cpp` where:

1. `HaveJoinSplitRequirements` is called once and therefore not redundant
2. Tests expect both success and failure, and in future, a developer could add tests when input data has invalid joinsplits.

**Comment by daira** [comment]
Closing per Simon's concept NACK.

**Pull request closed without merging**
