### PR TITLE
Fix naming inconsistency

### PR DESCRIPTION
**Pull request by rex4539**
Closes https://github.com/zcash/zcash/issues/3486

### CODE REVIEW

**Comment by Eirik0** [comment]
@zkbot r+

**Comment by rex4539** [comment]
`./zcutil/fetch-params.sh: line 161: cannot create temp file for here-document: No space left on device`

**Comment by Eirik0** [comment]
The failure cannot be related to the changes.

**Comment by Eirik0** [comment]
@zkbot retry

**Comment by Eirik0** [comment]
@zkbot retry

**Pull request merged**
