### PR TITLE
Add googlemock 1.7.0 dependency.

### LINKED ISSUE #891: Integrate googlemock into depends build
Add google mock (which I incorrectly thought came with googletest 1.7.0) into our depends build.

### PR DESCRIPTION
**Pull request by nathan-at-least**
closes #891. supercedes #909 which had spurious debug makefile stuff accidentally included.

### CODE REVIEW

**Comment by ebfull** [comment]
ACK

**Comment by daira** [comment]
ACK

**Comment by daira** [comment]
@zkbot r+ b6aa043d1f085ff34486a22e9ad63d1401fc74fa

**Comment by ebfull** [comment]
I added `googlemock-1.7.0.tar.gz` to our depends-sources mirror.

**Comment by nathan-at-least** [comment]
Good catch @ebfull! (We have a test that should have noticed that in buildbot.)

**Pull request merged**
