### PR TITLE
Make it possible to run operations under valgrind

### PR DESCRIPTION
**Pull request by defuse**
If we merge this then we can add this to buildbot and get basic assurances from valgrind. Ideally we want to run the whole test suite under valgrind, too, but this is good for now.

### CODE REVIEW

**Comment by defuse** [comment]
In my pairing with @str4d we added this to buildbot (not deployed yet). This PR is ready to go in.

**Comment by str4d** [comment]
ACK!

**Comment by str4d** [comment]
Note that the buildbot config currently only runs the valgrind tests; it doesn't parse anything out of the logs for uploading to the speed server. It is certainly possible to add that later though, once we know what we actually want to track.

**Comment by ebfull** [comment]
ACK

**Comment by str4d** [comment]
Woo, two ACKs!

@zkbot r+

**Pull request merged**
