### PR TITLE
Require zcash.conf to start zcashd

### LINKED ISSUE #2002: If zcashd finds no config file, exit with user friendly message.
Also, provide a config file with all of the default options commented out with explanations of the option's effect.

### PR DESCRIPTION
**Pull request by str4d**
Closes #2002.

### CODE REVIEW

**Comment by bitcartel** [comment]
ACK

**Comment by ebfull** [comment]
ACK

@zkbot r+

**Comment by ebfull** [comment]
Wallet tests in gtest are failing, so... this restriction on the zcash.conf must be interfering with tests or test initialization?

**Comment by str4d** [comment]
The tests that failed pass locally for me. So there's an environmental effect.

**Comment by str4d** [comment]
Confirmed: it's a regression in an earlier PR. This PR and the next one failed in the same way, because the build worker hasn't been idle long enough to be shut down and wiped.

**Comment by str4d** [comment]
@zkbot retry

**Pull request merged**
