### PR TITLE
Replace libsodium BLAKE2b usage with blake2b_simd crate

### PR DESCRIPTION
**Pull request by str4d**
Extracted from zcash/zcash#4654.

Also fixes a bug in the `tracing::Span` C++ class.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by ebfull** [comment]
ACK

**Review by therealyingtong — APPROVED** [review]
utACK

**Comment by str4d** [comment]
Rebased on master to fix a merge conflict in `Cargo.toml` due to #4720 being merged.

**Review by daira — APPROVED** [review]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient failure.

@zkbot retry

**Comment by daira** [comment]
That's odd: failed twice on `sapling_rewind_check`, but on different builders. Must be a nondeterministic test.

**Comment by str4d** [comment]
@zkbot retry

**Pull request merged**
