### PR TITLE
Rename OrchardMerkleTree -> OrchardMerkleFrontier

### PR DESCRIPTION
**Pull request by nuttycom**
Also removes IncrementalSinsemillaTree; this will be replaced by
a more full-featured OrchardWallet type which embeds the
incremental merkle tree used in wallet operations.

### CODE REVIEW

**Comment by nuttycom** [comment]
Bump the rebuild; transient failure.

**Comment by str4d** [comment]
This needs to be rebased on master now that #5373 has been merged (which renamed a file that this PR renames). I also don't think it needs to target `feature/wallet_orchard`, since it's renaming code that has already merged to master. We should instead target master, get this merged, and then merge master back into `feature/wallet_orchard` (which we need to do anyway as we merged a typo-fixing PR that has trivial conflicts).

**Comment by nuttycom** [comment]
@str4d good points, this has now been rebased and retargeted to master.

**Review by str4d — APPROVED** [review]
utACK

**Pull request merged**
