### PR TITLE
v1.0.0-beta2

### LINKED ISSUE #1479: Release beta 2
Follow https://github.com/zcash/zcash/blob/master/doc/release-process.md

Beta guide ready for update: https://github.com/zcash/zcash/wiki/Beta-2-Guide

### PR DESCRIPTION
**Pull request by str4d**
Closes #1479

### CODE REVIEW

**Comment by arcalinea** [comment]
ACK

**Comment by arcalinea** [comment]
zkbot r+

**Comment by arcalinea** [comment]
@zkbot r+

**Comment by ageis** [comment]
ACK @zkbot r+

**Pull request merged**
