### PR TITLE
metrics: Add gauge for the height to which the wallet is synced

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK

**Comment by str4d** [comment]
[Rebased on `master`](https://github.com/zcash/zcash/compare/0bc228a732061c8a7824a77e12b6c2906b18cbf7..39401964d26d4e65f19d63f12f8278d12120a86a) to fix merge conflict in release notes.

**Review by daira — APPROVED** [review]
utACK 39401964d26d4e65f19d63f12f8278d12120a86a

**Pull request merged**
