### PR TITLE
Add a 256-bit reserved field to the block header

### LINKED ISSUE #724: Add reserved field in the block header that could potentially be used for merged mining
Merged mining in Bitcoin is implemented by sticking a commitment to the auxiliary block headers in the coinbase or other transaction. This is suboptimal for the chain being merged mined because aux headers of that chain require log(N) hashes where N is the number of bitcoin transactions in that block, something which is entirely meaningless to the merged mined chain.

A better approach, and one Bitcoin would have used if this had been thought up in advance, is to have the block header commit to a tree of blocks, with a fixed path through that tree for each chain. A Merkle patricia trie, for example. This allows efficient merged mining with minimal impact to both chains.

Since zcash is using its own proof of work, it should take advantage of this opportunity to enable proper merge mining for any future sidechains which reuse the same PoW algorithm.

### PR DESCRIPTION
**Pull request by str4d**
This field has no defined semantics. While it was added as a result of
discussions about merged mining in #724, this field will not necessarily ever be
used for that purpose.

Closes #724.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by ebfull** [comment]
ACK once tests are added (which is the intention of the `try` but I wish we weren't using buildbot for that..)

**Comment by str4d** [comment]
Ready for review!

**Comment by ebfull** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
