### PR TITLE
Refine LogPrint debugging for z_* rpc calls

### PR DESCRIPTION
**Pull request by bitcartel**
For #1504 ZCA011

### CODE REVIEW

**Comment by bitcartel** [comment]
Self-ACK.

**Comment by str4d** [comment]
ACK the changes in this PR. Have not checked whether there are any z_* RPC logs that have been missed.

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by daira** [comment]
ACK changes in the RPC. Like @str4d, I haven't checked for missed calls.

**Pull request merged**
