### PR TITLE
Stop some wallet tests creating ~/.zcash/testnet3 folder by setting -datadir environment

### LINKED ISSUE #1478: Investigate why some tests are dependent on the contents of `~/.zcash/testnet3`
While merging PRs for the beta 2 release, we discovered an issue where if the PR for updating dependencies was tested and failed (so not merged), all subsequent builds (or was it tests?) of branches that didn't use the new dependencies would fail. The fix was to delete the `~/.zcash/testnet3` folder, which suggests two things:

- The tests are unnecessarily writing to the live (testnet) data directory.
- The tests are unnecessarily reading from the live (testnet) data directory.

We should identify the cause of this.

### PR DESCRIPTION
**Pull request by bitcartel**
Closes #1478

### CODE REVIEW

**Comment by daira** [comment]
utACK. (Have not checked that this fixes all cases, just that it looks plausible and does no harm.)

**Comment by bitcartel** [comment]
@arcalinea Can you rename your existing .zcash folder, build and run test_bitcoin and zcash-gtest to confirm:
1. They do not create a .zcash/testnet3 folder
2. They do not create a wallet.dat folder in the src folder (or whatever folder you are running the test from).
Please ACK if the above is true.  Thanks.

**Comment by str4d** [comment]
Renamed my existing `~/.zcash` folder, ran `./qa/zcash/full-test-suite.sh` on master, and confirmed that the following files were created:

- `src/wallet.dat`
- `~/.zcash/testnet3/database/log.0000000001`
- `~/.zcash/testnet3/db.log`
- `~/.zcash/testnet3/debug.log`

Deleted all of the above files, re-ran `./qa/zcash/full-test-suite.sh` on this branch, and confirmed that the following files were created:

- `src/wallet.dat`
- `~/.zcash/testnet3/database/log.0000000001`
- `~/.zcash/testnet3/db.log`
- `~/.zcash/testnet3/debug.log`
- `~/.zcash/testnet3/wallet_crypted.dat`
- `~/.zcash/testnet3/wallet.dat`

NACK

**Comment by bitcartel** [comment]
@str4d Can you run test_bitcoin and zcash_gtest separately to see which one is causing this to occur?
I'm not seeing this behavior but will try again.  Did you make clean and rebuild for the second run?

**Comment by str4d** [comment]
@bitcartel I only re-ran `zcutil/build.sh` in between changing branch. I will do a clean build now and hunt for the root cause.

**Comment by bitcartel** [comment]
@str4d I pushed a commit to fix src/wallet.dat, found one case in test_bitcoin.

**Comment by str4d** [comment]
Cleaned and rebuilt after pulling the above commit. `test_bitcoin` does not generate any of the new files. Now testing the remaining components of `full-test-suite.sh` individually.

**Comment by bitcartel** [comment]
@str4d I noticed this.  If you run them individually, there is no issue.  However if you run ./zcash-gtest (without any filter) it will create the ~/.zcash folder (you can ctrl-c as soon as it hits the joinsplit test).  So something environmental?

**Comment by str4d** [comment]
One of the following test groups in `zcash-gtest` generates `~/.zcash/testnet3/debug.log`:

- `founders_reward_test`
- `json_spirit_tests`
- `tautologies`
- `checktransaction_tests`
- `equihash_tests`
- `joinsplit.h_sig` or `joinsplit.full_api_test`

I will keep monitoring the rest of the test run.

**Comment by str4d** [comment]
Oh, it was actually easy to figure out which:

```
$ cat ~/.zcash/testnet3/debug.log 
ERROR: CheckTransaction(): joinsplit.vpub_new and joinsplit.vpub_old both nonzero
ERROR: CheckTransaction(): vin empty
ERROR: CheckTransaction(): vout empty
ERROR: CheckTransaction(): size limits failed
ERROR: CheckTransaction(): txout.nValue negative
ERROR: CheckTransaction(): txout.nValue too high
ERROR: CheckTransaction(): txout total out of range
ERROR: CheckTransaction(): txout total out of range
ERROR: CheckTransaction(): txin total out of range
ERROR: CheckTransaction(): joinsplit.vpub_old negative
ERROR: CheckTransaction(): joinsplit.vpub_new negative
ERROR: CheckTransaction(): joinsplit.vpub_old too high
ERROR: CheckTransaction(): joinsplit.vpub_new too high
ERROR: CheckTransaction(): joinsplit.vpub_new and joinsplit.vpub_old both nonzero
ERROR: CheckTransaction(): duplicate inputs
ERROR: CheckTransaction(): duplicate nullifiers
ERROR: CheckTransaction(): duplicate nullifiers
ERROR: CheckTransaction(): coinbase has joinsplits
ERROR: CheckTransaction(): coinbase script size
ERROR: CheckTransaction(): prevout is null
ERROR: CheckTransaction(): invalid joinsplit signature
ERROR: CheckTransaction(): invalid joinsplit signature
```

**Comment by str4d** [comment]
Okay, all `~/.zcash` files are generated by `zcash-gtest`.

**Comment by bitcartel** [comment]
But if you run `./zcash-gtest --gtest_filter="checktransaction_tests.*"` it does not write to .zcash...

**Comment by str4d** [comment]
Yeah, and neither with `./src/zcash-gtest --gtest_filter=wallet_zkeys_tests.*` which is what I expect is generating the wallet files.

**Comment by bitcartel** [comment]
Added `SelectParams(CBaseChainParams::TESTNET);` (and tried MAIN) and both resulted in checktransaction_tests creating the .zcash folder when running ./zcash-gtest --gtest_filter="checktransaction_tests.*".  Since founders_reward test selects parameters, this may be the reason, as it is run before checktransaction.

**Comment by bitcartel** [comment]
I am running zcash-gtest now, having reordered the gtest makefile, putting checktransaction at the top, and putting founders_reward and wallet_z_keys before joinsplit.  Currently performing joinsplits.  Nothing written to .zcash yet.

**Comment by bitcartel** [comment]
@str4d Pushed new commit.  Zcash-gtest now does not write to ~/.zcash.

**Comment by str4d** [comment]
Pulled, rebuilt and ran `./src/zcash-gtest --gtest_filter=-joinsplit.*` (for speed, since I'm confident it wasn't `joinsplit` causing the writes). No writes observed.

ACK!

**Comment by bitcartel** [comment]
ACK + utACK + self-ACK @zkbot r+

**Pull request merged**
