### PR TITLE
More granular control over logging of z_* calls

### LINKED ISSUE #1504: ZCA-011 Private addresses and information of protected transactions exposed through log files
Private addresses and Information of protected transactions including plaintext of memo fields are logged to `~/.zcash/*/debug.log`, a log file in persistent storage that is not necessarily encrypted.

https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L113-L119

https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L758-L769
```
2016-10-10 16:05:38 async rpc opid-ae0e3e97-adde-438d-a06f-e09ee2183f6d finished (status=success, tx=CTransaction(hash=4a7c170761, ver=2, vin.size=0, vout.size=0, nLockTime=0)
)
```
```
2016-10-07 18:51:55 ThreadRPCServer method=z_sendmany
2016-10-07 18:51:55 opid-26d2c: found unspent note (txid=0419b1e5b1, vjoinsplit=0, ciphertext=0, amount=0.50, memo=0000000000)
2016-10-07 18:51:55 opid-26d2c: found unspent note (txid=0419b1e5b1, vjoinsplit=0, ciphertext=1, amount=0.1784, memo=f600000000)
2016-10-07 18:51:55 opid-26d2c: spending 0.3001 to send 0.30 with fee 0.0001
2016-10-07 18:51:55  -  transparent input: 0.00 (to choose from)
2016-10-07 18:51:55  -      private input: 0.6784 (to choose from)
2016-10-07 18:51:55  - transparent output: 0.00
2016-10-07 18:51:55  -     private output: 0.30
2016-10-07 18:51:55  -                fee: 0.0001
2016-10-07 18:51:55 opid-26d2c: spending note (txid=0419b1e5b1, vjoinsplit=0, ciphertext=0, amount=0.50)
2016-10-07 18:51:55 opid-26d2c: spending note (txid=0419b1e5b1, vjoinsplit=0, ciphertext=1, amount=0.1784)
2016-10-07 18:51:55 opid-26d2c: generating note for change (amount=0.3783)
2016-10-07 18:51:55 opid-26d2c: creating joinsplit at index 0 (vpub_old=0.00, vpub_new=0.0001, in[0]=0.50, in[1]=0.1784, out[0]=0.30, out[1]=0.3783)
```
https://github.com/zcash/zcash/blob/master/src/wallet/rpcdump.cpp#L308
https://github.com/zcash/zcash/blob/master/src/wallet/rpcdump.cpp#L312

```
2016-10-07 16:03:30 Skipping import of tmXUrzGp2d15quthkdoYrsxreE6vtg3GKYs (key already present)
2016-10-07 16:03:30 Skipping import of zaddr ztPqrWMZctcpDRQhFLokoa2n2mQHDFYJ5EMvMSzGJKSjbaNBP5JvKxav34XGfKy1ecrvd93dETMp1Fdih4qJ6NGqSAnHqht (key already present)
2016-10-07 16:03:30 Skipping import of zaddr ztgryfVice57QzdyLHk82wkrDQeUKzFwzKqhQZJyt4xUsXw1akYYry5WeNNAB7u8xpFMWpTmdppWsWNiBwTSfiDVXzmGLc3 (key already present)
2016-10-07 16:03:30 Rescanning last 61 blocks
```

### PR DESCRIPTION
**Pull request by bitcartel**
Closes #1504

### CODE REVIEW

**Comment by daira** [comment]
ACK. @zkbot r+

**Comment by daira** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
See #1596

**Comment by daira** [comment]
@zkbot retry

**Pull request merged**
