### PR TITLE
Implement consensus rules about the number of Spend and Output Descriptions in a transaction

### LINKED ISSUE #3209: Change check that at least one of tx_in_count, nShieldedSpend or nJoinSplit are nonzero

### PR DESCRIPTION
**Pull request by Eirik0**
Closes #3209.
Part of #3065.

### CODE REVIEW

**Comment by Eirik0** [comment]
See #3065

**Comment by ebfull** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot p=1

**Pull request merged**
