### PR TITLE
wip: establish build baseline

### PR DESCRIPTION
**Pull request by recursivelycurious**
Add change to README.md to validate existing build baseline.

NOTE: This is a preliminary change to evaluate / understand the existing infrastructure prior to proposing any changes.

@zkbot try

Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by the documentation team (@ioptio, @mdr0id, or @Eirik0) before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

### CODE REVIEW

**Comment by recursivelycurious** [comment]
@mdr0id, @Eirik0 

Hello. I am applying for the DevOps opening you presently have and am attempting to gauge the build / test baseline for contributors.

I believe an individual within some set of walls needs to ask zkbot to run the tests. 

Would either of you be able to make that request for me or point me toward the correct individual?

**Comment by mdr0id** [comment]
Hello,
Unfortunately we are not merging things in at the current time due to code freeze for release. 
You can look at other PRs to gauge the baseline at ci.z.cash

**Comment by str4d** [comment]
The most relevant build to look at is https://github.com/zcash/zcash/pull/4060#issuecomment-520434340 which shows the CI behaviour that will be baseline shortly after 2.0.7 is released.

**Comment by recursivelycurious** [comment]
Just to clarify, is there  not a way to run the build without any merge behavior?

https://gitlab.com/zcash-docs/zcash-docs/blob/master/source/rtd_pages/development_guidelines.rst#L311

Suggests that `@zkbot try` should only run the tests?

Does a successful build/test automatically merge?

Looking at a number of different builds, 2 hours seems to be the baseline. Please let me know if this seems incorrect.

**Comment by str4d** [comment]
- `zkbot try` runs the full CI suite on a merge commit between the PR and master, but does not push that commit to `master` if the CI suite passes (the commit is discarded).
- `zkbot r+` does the exact same CI suite run, and pushes the merge commit to master if the suite passes.

> Looking at a number of different builds, 2 hours seems to be the baseline. Please let me know if this seems incorrect.

It is historically correct (build times are around 1hr50). This is primarily due to the majority of the tests using the original Sprout circuit for testing against, which is very slow and memory-intensive. The PR I linked to deletes the original Sprout circuit, migrating all those tests to the hybrid Sprout circuit that was deployed in the Sapling upgrade. The hybrid Sprout circuit is twice as fast as the original one, leading to the observed drop in CI runtime.

A future improvement would be to migrate all tests that don't explicitly require Sprout (and are just testing shielded behaviour) to use Sapling instead. Sapling is 10x faster than hybrid Sprout, so we should see another large improvement in CI runtime.

**Comment by recursivelycurious** [comment]
Thanks for the clarification.  

Closing MR to reduce noise while reviewing what else I can find re: CI/CD and testing in the documentation and code base.

If there are non obvious places I should review, please point me in that direction.

**Pull request closed without merging**
