### PR TITLE
Add missing <stdexcept> header for std::invalid_argument

### LINKED ISSUE #1703: error: 'invalid_argument' is not a member of 'std' (GCC 4.7.2)
```
In file included from crypto/equihash.cpp:15:0:
./crypto/equihash.h: In function 'bool EhBasicSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector<unsigned char>)>, std::function<bool(EhSolverCancelCheck)>)':
./crypto/equihash.h:227:15: error: 'invalid_argument' is not a member of 'std'
./crypto/equihash.h: In function 'bool EhOptimisedSolve(unsigned int, unsigned int, const eh_HashState&, std::function<bool(std::vector<unsigned char>)>, std::function<bool(EhSolverCancelCheck)>)':
./crypto/equihash.h:251:15: error: 'invalid_argument' is not a member of 'std'
```

Needs to include `<stdexcept>`.

### PR DESCRIPTION
**Pull request by defuse**
Closes #1703.

### CODE REVIEW

**Comment by defuse** [comment]
Fixes https://github.com/zcash/zcash/issues/1703#issuecomment-633312223

**Comment by defuse** [comment]
I'm unsure if this was a regression or just from upgrading gcc.

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient failures.

@zkbot retry

**Comment by str4d** [comment]
And another one 😑

@zkbot retry

**Pull request merged**
