### PR TITLE
contrib: Add script for generating a graph of our Rust dependencies

### PR DESCRIPTION
**Pull request by str4d**
The Rust deps are also updated.

### CODE REVIEW

**Comment by str4d** [comment]
This PR doesn't remove the duplicate deps, because `metrics-util` still has a direct dependency on `atomic-shim 0.1`, but the script has `--no-transitive-deps` so it looked like `metrics-util` only depended on the older `crossbeam` via `quanta`.

**Comment by str4d** [comment]
I wouldn't mind merging this in the RC window, but given that it doesn't materially reduce our dependencies, it's not important. If `metrics-util` happens to make another release that bumps `atomic-shim` before we need to cut v4.5.0 then we can consider including it.

**Review by daira — APPROVED** [review]
utACK, but I agree it's not needed unless `metrics-util` updates again (see https://github.com/metrics-rs/metrics/pull/231).

**Comment by str4d** [comment]
I'm about to update the Rust dependencies anyway to bring in the `halo2` and `orchard` license text updates, so I'll merge this first.

**Pull request merged**
