### PR TITLE
Fix deadlock inside getblocktemplate function

### PR DESCRIPTION
**Pull request by luciocorral**
There is a deadlock between cs_main and csBestBlock related to inverse locking order inside getblocktemplate function.

These are the steps to reproduce the deadlock:
A- Thread 1 locks cs_main, locks csBestBlock, then unlocks cs_main for a while.
B- Thread 2 just enter, locks cs_main (cause it was temp unlocked) then tries to lock csBestBlock and wait there as it was already locked by thread 1.
C- Thread 1 go back to live, then try to re-lock cs_main, but gets locked as it was locked by thread 2.
D- We have a deadlock situation.

The solution was to move the cs_main release block outside the while loop.

### CODE REVIEW

**Comment by LarryRuane** [comment]
I discussed with Nick on Telegram that this isn't the right fix (we can't call `chainActive->Tip()` without holding `cs_main`), but there is a fix from upstream Bitcoin that I'll cherry-pick now.

**Comment by luciocorral** [comment]
> I discussed with Nick on Telegram that this isn't the right fix (we can't call `chainActive->Tip()` without holding `cs_main`), but there is a fix from upstream Bitcoin that I'll cherry-pick now.

Hi Larry, thanks for the advice, in fact as cs_main is protecting almost all I was unsure what it was trying to protect then :)

So, deadlock is there by sure so it needs to be fixed. A good solution will be to use different critical sections for each resource type, but that will be a major change. Therefore, I was analyzing the code and came up with a few options:

1- Remove csBestBlock. What will be the issue if you have multiple getblocktemplate calls going into the unprotected while loop? It seems to me that csBestBlock was just a leftover cs that was trying to protect something else from the past. Could it be?

2- Remove chainActive->Tip() call from while loop. If csBestBlock can't be removed, I feel this is the best approach but will require a separate (maybe global) best block update controlled by csBestBlock.

3- Move csBestBlock lock at function start right before cs_main lock. That will be as using csBestBlock for getblocktemplate mutual exclusion. You will be able to have multiple threads going into all other RCP, but just one getblocktemplate per time.

4- Remove the cs_main unlocking. As getblocktemplate takes a lot of time, that will be secure but not sure if what we are looking for.

What do you think?

**Comment by LarryRuane** [comment]
Hi @luciocorral, I made PR 5594 which is a cherry-pick of bitcoin upstream PR https://github.com/bitcoin/bitcoin/pull/12743. I think that PR fixes this the correct way. I think it implements what you listed as option 2 above.

**Comment by luciocorral** [comment]
> 5594

Hi Larry, thanks! Yeap, seems to be approach #2. Let us test it tomorrow and it works I will comment and approved it.

Thanks for the help!

**Comment by luciocorral** [comment]
Closing this MR as it was covered by https://github.com/zcash/zcash/pull/5594

**Pull request closed without merging**
