### PR TITLE
Adding addressindex.h to Makefile.am

### LINKED ISSUE #3962: Commit e73326e breaks Gitian build
### Describe the issue
All Gitian builds after https://github.com/zcash/zcash/commit/e73326eed0d987a6a90aac93745059f9be212d77 fail with:

```
In file included from bitcoind.cpp:9:0:
main.h:29:26: fatal error: addressindex.h: No such file or directory
 #include "addressindex.h"
                          ^
compilation terminated.
Makefile:5689: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] Error 1
make[2]: Leaving directory '/home/debian/build/zcash/distsrc-x86_64-unknown-linux-gnu/src'
Makefile:5737: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/debian/build/zcash/distsrc-x86_64-unknown-linux-gnu/src'
Makefile:615: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

#### If so, please list the steps to reproduce below:
1. Destroy any existing zcash-builder VMs
2. Set `ZCASH_VERSION` to e73326eed0d987a6a90aac93745059f9be212d77 or a later commit
3. Run `vagrant up zcash-build`
4. Once built `vagrant ssh zcash-build`
5. Run `./gitian-build.sh`
6. `gitian-builder/var/build.log` contains the following error and build does not complete

### Expected behaviour
It should build as the previous commit does https://github.com/zcash/zcash/commit/926fd0ce2836fd665a956f52566824ecbe143c47

### The version of Zcash you were using:
Vagrant 2.2.4
debian/stretch64 (virtualbox, 9.8.0)

Discussion from here: https://github.com/zcash/zcash/pull/3951

### PR DESCRIPTION
**Pull request by garethtdavies**
Co-authored by: Daira Hopwood <daira@jacaranda.org>

Closes #3962

### CODE REVIEW

**Comment by LarryRuane** [comment]
utACK thank  you @garethtdavies for figuring out my mistake.

**Comment by daira** [comment]
@LarryRuane wrote:
> thank you @garethtdavies for figuring out my mistake.

That was me actually :-) Thanks to Gareth for filing the PR.

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
@garethtdavies Just for future reference, it has to be spelled `Co-authored-by` to work for GitHub's author attribution. (It's not a problem in this case.)

**Comment by garethtdavies** [comment]
@daira Ah, sorry about that. I edited my commit message for correctness but I'm not sure if that works retroactively for author attribution.

**Pull request merged**
