### PR TITLE
For #3546. Shielded tx with missing inputs are not treated as orphans.

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by mdr0id** [comment]
utACK

**Comment by ebfull** [comment]
Oh, yes.

ACK

**Comment by ebfull** [comment]
In our Sprout implementation, we weren't sure how `JoinSplit`s would interact with `mapOrphans`, so we decided to be conservative and just throw away transactions that had shielded components in it. This extends that logic to Sapling.

**Comment by mdr0id** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
