### PR TITLE
Add gtest for non-malleable txids.

### PR DESCRIPTION
**Pull request by bitcartel**
1. Test txid of normal transaction is double sha256 with sigscript input data removed
2. Test txid of coinbase transaction is double sha256 over whole tx

You can run a single test with:
./zcash-gtest --gtest_filter="txid_tests*"

### CODE REVIEW

**Comment by nathan-at-least** [comment]
Reviewing this now.

**Comment by nathan-at-least** [comment]
Note this tests the changes merged in PR #1144 for issue #1145. That PR as well as this one should be scrutinized by Bitcoin experts. I'll add it to a list to point out to some of our auditors.

**Comment by nathan-at-least** [comment]
ACK: These tests are good basic sanity tests.

Not a blocker for this PR, but a follow up testing task:

I'd like to see more exhaustive mutation tests that check _each_ of a list of known malleability vectors, such as all 9 cases here: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki

Additionally, we should test malleability of the JoinSplit signatures (eg: sign flips).

Even though it should be obvious that these won't impact this "stable txid" having these tests would make me feel better.

**Comment by bitcartel** [comment]
ACK

@zkbot r+

**Pull request merged**
