### PR TITLE
cleanup: Ensure code is pyflakes-clean for CI

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
Fixes the warnings visible [here](https://ci.z.cash/#/builders/12/builds/269).

**Comment by bitcartel** [comment]
Pyflakes warnings should disappear... @zkbot try

**Comment by daira** [comment]
Unrelated RPC test failure. @zkbot r+

**Comment by str4d** [comment]
One of the CI workers failed to connect to GitHub to download the source? 😑

@zkbot retry

**Comment by str4d** [comment]
Another transient failure.

@zkbot retry

**Pull request merged**
