### PR TITLE
Add Sapling to upgrade list

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
Rebased on master to fix merge conflicts.

**Comment by ebfull** [comment]
I figure we'll want to merge this after 1.1.0?

**Comment by str4d** [comment]
Rebased on master to fix merge conflict. I've also added the (currently 404ing but eventual) link to the Sapling info page (which won't show up in the UI anywhere until an activation height is set).

**Comment by ebfull** [comment]
re-ACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
