### PR TITLE
Decrease block interval to 2.5 minutes

### LINKED ISSUE #764: analyze block-witholding ('selfish mining') attacks in light of Equihash performance
Litecoin has had 2.5-minute blocks all along (with 1 MB block size), and it doesn't seem to have suffered any problems because of it. Let's set Zcash's block interval to 2.5 minutes too.

I've asked the Zcash Technical Advisory Board privately if they think there would be a problem with this, and none of them raised a warning flag.

### PR DESCRIPTION
**Pull request by str4d**
Associated changes (to maintain the monetary curve and expected durations):

- Block subsidy quartered
- Mining slow start quadrupled
- Halving interval quadrupled
- Majority window quadrupled

Closes #764.

### CODE REVIEW

**Comment by str4d** [comment]
This will break a lot of tests; I have made this PR early so I can run the tests on the CI server (I don't have enough memory to do so locally and cannot figure out which test is loading the proving key).

**Comment by str4d** [comment]
Note that it is not necessary to alter the founder's reward code, because that is calculated based on the block subsidy and halving interval, which have both been adjusted to maintain the monetary curve.

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
#904 needs to be closed before this.

**Comment by str4d** [comment]
All tests pass except for two "insufficient priority" errors in the RPC tests, which will disappear once #904 is closed.

**Comment by str4d** [comment]
The updates to the miner tests clash with #999, so I will rebase and update this when that merges.

**Comment by defuse** [comment]
ACK, will be fun to see this working on the testnet :)

Remember to make the corresponding changes for #1004 (not sure which one will be going in first).

**Comment by defuse** [comment]
There's a hard-coded number of blocks "72" here: https://github.com/zcash/zcash/issues/826#issuecomment-224952777 Either correct the comment (to say 3 hours instead of 12) or change the 72 to 288.

**Comment by str4d** [comment]
Rebased on master, updated miner tests and fixed the issue raised by @defuse.

**Comment by ebfull** [comment]
ACK, I am landing this before my softfork activation changes since it will be a simpler rebase for me, and the ordering doesn't matter much.

@zkbot r+

**Comment by str4d** [comment]
- I've never seen the `test/alert_tests.cpp` failure before, investigating...
- The `txn_doublespend.py` is strange, looks like something not stopping? I haven't had problems locally.
- The `zcpourdoublespend.py` error is something I overlooked because I don't run that locally because RAM limits.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
