### PR TITLE
Scan the whole chain whenever a z-key is imported

### LINKED ISSUE #1941: When importing z-addresses, rescan does not see transactions older than wallet birthday
Wallet bug:

When importing a z-address key via `z_importkey`, the wallet automatically does a rescan to recognize associated transactions. However, the rescan code skips over blocks that are older than the time the wallet was created, so if the node is a new installation, it will not see historical transactions.

Culprit code in `CWallet::ScanForWalletTransactions()`:
```
        // no need to read and scan block, if block was created before
        // our wallet birthday (as adjusted for block time variability)
        while (pindex && nTimeFirstKey && (pindex->GetBlockTime() < (nTimeFirstKey - 7200)))
            pindex = chainActive.Next(pindex);
```

This optimization may make sense in some contexts, but not when importing keys.

Related to #1860, #1350.

### PR DESCRIPTION
**Pull request by str4d**
Closes #1941.

### CODE REVIEW

**Comment by bitcartel** [comment]
We might want an RPC test to ensure the rescan behaviour has changed.

**Comment by bitcartel** [comment]
@str4d What about importwallet - where the wallet contains Z keys?

**Comment by Voluntary-zcash** [comment]
Can there be an additional option or an alternative way to import a z_addr that also specifies the block number to start scanning from or a range of blocks to scan?

**Comment by bitcartel** [comment]
We need to update the PR for importwallet:
```  
                // Successfully imported zaddr.  Now import the metadata.
                pwalletMain->mapZKeyMetadata[addr].nCreateTime = nTime;
                continue;
```
to
```
                // Successfully imported zaddr.  Now import the metadata.
                pwalletMain->mapZKeyMetadata[addr].nCreateTime = nTime;
                pwalletMain->nTimeFirstKey = 1;
                continue;
```
When importing wallet dump files, the time associated with the zkey may not be accurate, so we should rescan the whole blockchain.  Otherwise when importing the wallet dump file, how far back to go in the rescan will be based on the taddr addresses in the wallet.

**Comment by bitcartel** [comment]
ACK

**Comment by ebfull** [comment]
@Voluntary-zcash that would be nice! feel free to file an issue, I think we could add that to the API.

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
