### PR TITLE
Update more dependencies for 5.8.0

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by str4d** [comment]
After this PR, our only dependencies that pull in `windows-sys 0.48` will be:

| Crate | Blocker |
| --- | --- |
| `home` | Updating this requires updating Rust to at least 1.70 due to an MSRV bump, which is blocked on finding a newer LLVM release that provides compiler binaries for all the targets we need. |
| `mio` | Update merged into repo, no release yet. MSRV for this release will likely be Rust 1.74 which we are blocked on per above. |
| `socket2` | Update merged into repo, no release yet. |
| `tokio` | Waiting on `mio` release. |

**Review by nuttycom — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK

**Review by nuttycom — APPROVED** [review]
utACK a4f8fabe2f3d25377f59c7b7316013b8685ec838

I have not verified the updated sha256 hashes.

**Review by daira — APPROVED** [review]
utACK. I have not checked any hashes either.

**Pull request merged**
