### PR TITLE
Change regtest port to 18344.  Closes #2269.

### LINKED ISSUE #2269: Change default regtest port of 18444 which is the same as (inherited from) upstream
https://github.com/zcash/zcash/blob/master/src/chainparams.cpp#L322
via
https://github.com/zcash/zcash/pull/2150#issuecomment-293670166

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by arcalinea** [comment]
Tested, works fine. And don't see that port number anywhere else in the code, so think it's safe to change. 

ACK. @zkbot try

**Comment by daira** [comment]
Hmm, why is this still pending after 11 hours? @ageis?

**Comment by ageis** [comment]
@zkbot retry

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
Known-nondeterministic test failure unrelated to this PR. @zkbot retry

**Comment by arcalinea** [comment]
Are we merging this soon?

**Comment by daira** [comment]
@arcalinea yes, it had already merged.

**Pull request merged**
