### PR TITLE
Fix an error reporting bug due to BrokenPipeError and ConnectionResetError not existing in Python 2

### PR DESCRIPTION
**Pull request by daira**
refs #2263

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot try

**Comment by bitcartel** [comment]
Now I get `[Errno 32] Broken pipe`, so the correct exception is being thrown and caught with Python 2.

**Comment by arcalinea** [comment]
utACK

**Comment by daira** [comment]
It appears that this fixes the error reporting. @zkbot r+

**Comment by daira** [comment]
This fix should be submitted upstream.

**Pull request merged**
