### PR TITLE
Use -O1 opimitization flag when building libzcash

### PR DESCRIPTION
**Pull request by bitcartel**
Continuation of #1064 and related to #1168.

### CODE REVIEW

**Comment by bitcartel** [comment]
ACK (self)

@ebfull This is so you can measure performance as discussed in #1064 (note that levelDB, secp256k1 and dependencies are built with whatever optimization flags are specified in their own Makefiles.)

**Comment by ebfull** [comment]
ACK but I still firmly believe we should use O2, and I think we're going to backtrack on this.

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by daira** [comment]
@ebfull - there are two issues here:
1. Making sure we reliably use the same optimisation level for all compilation.
2. Deciding whether that level should be -O1 or -O2.

2. should be easy after we've done 1.

**Pull request merged**
