### PR TITLE
Add a missing % to a string interpolation in rpc test framework

### PR DESCRIPTION
**Pull request by defuse**

### CODE REVIEW

**Comment by defuse** [comment]
I haven't run the tests with the fix to confirm it works (sorry, I'm running RPC tests from another branch, and I'm worried running two at once would conflict)

**Review by daira — APPROVED** [review]
ACK

**Comment by rex4539** [comment]
I ran the tests on macOS and they all pass.

**Comment by daira** [comment]
@zkbot r+

**Review by nuttycom — APPROVED** [review]

**Pull request merged**
