### PR TITLE
Fix incorrect locking in CCryptoKeyStore

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by ebfull** [comment]
Is this meant to address #1680?

**Comment by daira** [comment]
utACK

**Comment by nathan-at-least** [comment]
Let's postpone this to 1.0.[Soon]. We're not certain this change is worth it *if* we're not going to re-enable wallet encryption, but we need to sync up w/ @str4d first.

**Comment by ebfull** [comment]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
