### PR TITLE
Change JSOutPoint constructor to have js argument be uint64_t

### LINKED ISSUE #3192: Change JSOutPoint constructor to have js argument be uint64_t
To match the change we made to the internal field for portability.

### PR DESCRIPTION
**Pull request by str4d**
Closes #3192.

### CODE REVIEW

**Comment by Eirik0** [comment]
@zkbot try

**Comment by str4d** [comment]
> Should we change CWallet::IsLockedNote(...) as part of this PR also?

Yeah - in fact, it doesn't need to even go through a `js`. I'll push a commit altering it.

**Comment by ebfull** [comment]
re-ACK

**Comment by str4d** [comment]
I'm going to use this along with #3201 to test Homu's rollup feature.

**Comment by str4d** [comment]
@zkbot rollup

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
I'm manually cancelling this PR because #3202 is more important to get through (and I only just saw it failed overnight).

**Comment by str4d** [comment]
@zkbot retry p=0

**Comment by str4d** [comment]
@zkbot rollup-

**Pull request merged**
