### PR TITLE
Apply MiniUPnP patches to enable compilation on Solaris 11

### LINKED ISSUE #1835: Solaris 11, miniupnpc patch
When compiling ***miniupnpc*** on Solaris 11:

```
gcc -m64 -fPIC -pipe -O1 -I/export/home/zcash/depends/x86_64-unknown-linux-gnu/include -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600   -c -o igd_desc_parse.o igd_desc_parse.c
gcc -m64 -fPIC -pipe -O1 -I/export/home/zcash/depends/x86_64-unknown-linux-gnu/include -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DMINIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600   -c -o minisoap.o minisoap.c
In file included from /usr/include/iso/string_iso.h:24:0,
                 from /usr/include/string.h:11,
                 from minixml.c:33:
/usr/include/sys/feature_tests.h:358:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications 	require the use of c99"
 #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications \
  ^
make[1]: *** [minixml.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/stdio.h:15:0,
                 from minisoap.c:10:
/usr/include/sys/feature_tests.h:358:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications 	require the use of c99"
 #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications \
  ^
In file included from /usr/include/stdio.h:15:0,
                 from miniwget.c:9:
/usr/include/sys/feature_tests.h:358:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications 	require the use of c99"
 #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications \
  ^
In file included from /usr/include/stdio.h:15:0,
                 from igd_desc_parse.c:10:
/usr/include/sys/feature_tests.h:358:2: error: #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications 	require the use of c99"
 #error "Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications \
  ^
make[1]: *** [igd_desc_parse.o] Error 1
make[1]: *** [minisoap.o] Error 1
miniwget.c: In function ‘getHTTPResponse’:
miniwget.c:87:6: warning: variable ‘reason_phrase_len’ set but not used [-Wunused-but-set-variable]
  int reason_phrase_len = 0;
      ^
miniwget.c:86:9: warning: variable ‘reason_phrase’ set but not used [-Wunused-but-set-variable]
  char * reason_phrase = NULL;
         ^
make[1]: *** [miniwget.o] Error 1
make[1]: Leaving directory `/export/home/zcash/depends/work/build/x86_64-unknown-linux-gnu/miniupnpc/2.0-792e2b4396f'
make: *** [/export/home/zcash/depends/work/build/x86_64-unknown-linux-gnu/miniupnpc/2.0-792e2b4396f/./.stamp_built] Error 2
```

Cloning [miniupnpc](https://github.com/miniupnp) and removing the `-D_XOPEN_SOURCE=600` clears the issue:

```
git clone https://github.com/miniupnp/miniupnp.git
cd miniupnp/
find $PWD -name 'minisoap.c'
   miniupnp/miniupnpc/minisoap.c
cd miniupnp/
gcc -m64 -fPIC -pipe -O1 -I../../depends/work/build/x86_64-unknown-linux-gnu/min
iupnpc/2.0-792e2b4396f -I/export/home/zcash/depends/x86_64-unknown-linux-gnu/inc
lude -Wall -W -Wstrict-prototypes -fno-common -DMINIUPNPC_SET_SOCKET_TIMEOUT -DM
INIUPNPC_GET_SRC_ADDR -D_BSD_SOURCE -D_DEFAULT_SOURCE -c -o minisoap.o minisoap.
c
```

-----

Also see [MiniUPnP Issue 216: Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications](https://github.com/miniupnp/miniupnp/issues/216).

### PR DESCRIPTION
**Pull request by str4d**
These can be removed after the next MiniUPnP release.

Closes #1835.

### CODE REVIEW

**Comment by str4d** [comment]
Both patches have been applied upstream (see miniupnp/miniupnp#216 and miniupnp/miniupnp#220).

@noloader could you please check that this resolves your issue?

**Comment by str4d** [comment]
(I have ambitiously put this PR into 1.0.4, but will not merge it without confirmation from @noloader, since none of us devs are using Solaris.)

**Comment by bitcartel** [comment]
@str4d Upstream miniupnp has patched the patch... https://github.com/miniupnp/miniupnp/commit/0aa7c46227acd8ddb135c577674ad454bf2fba86

**Comment by str4d** [comment]
@bitcartel upstream patch patch applied.

**Comment by bitcartel** [comment]
I don't think this applies to us given our fork version https://bitcoin.org/en/alert/2015-10-12-upnp-vulnerability

Q. Do we want this ticket to be just about compiling for Solaris, or for it to become an upgrade of miniupnp?

**Comment by str4d** [comment]
@bitcartel #1835 was about a specific Solaris compilation issue caused by miniupnpc. This PR fixes it by patching miniupnpc, but a later PR can replace these patches with an upgrade of miniupnpc (when it is released).

**Comment by str4d** [comment]
(And yes, that alert was for an older version of miniupnpc than we are using.)

**Comment by ebfull** [comment]
ACK on the patch but can Solaris users not just disable miniupnp? I would rather not ever use that thing.

**Comment by bitcartel** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
