### PR TITLE
Update testing scripts for parallel CI support

### PR DESCRIPTION
**Pull request by mdr0id**
Add rpc_group sort for parallel test CI pipelines and according targets to split test on N machines. Note we are a bit limited in this implementation for now because of how the underlying rpc_test_list is organized, so we wrote this to be agnostic to the resource intensive tests that could reduce optimizations from sharding groups further. Later we can go back and formalize both lists to not only split better for N groups, but also allow dynamic lists generations so devs/operators can ideally test variations of tests to identify regressions/bugs.

### CODE REVIEW

**Comment by mdr0id** [comment]
Other random note that for now we do 4 test groups for cost reasons but this can scale as needed once markets rebound etc.

**Comment by superbaud** [comment]
`how many machines run in parallel. Default=4.` has a typo (should be "tests") and the default if it's _not given_ should be 1, since we want all the RPC tests to execute if they're not being sharded. 

More generally it's not quite clear how this change affects the code flow when either (or both) of these new arguments *aren't* given.

**Comment by mdr0id** [comment]
Good question. This is forcing the default to be 4 rpc test banks to allow Tekton to gracefully drive the underlying parallel task in the given static pipeline. Later we can make the underlying python more dynamic and tekton more dynamic to just create N of these per the test driver script for a formal dynamic pipeline.

Additionally this is one way of us transitioning from `rpc`  naming conventions to `rpc_group0` (or whatever we want to do) onward. If we want to support legacy runs we can refactor the default and force rpc_group0 to operate exactly like `full_test_suite.py rpc`

**Review by nuttycom — CHANGES_REQUESTED** [review]
Minor suggestion for a change in how the test list fragments are computed.

**Comment by mdr0id** [comment]
ffs github squash :-1:

**Pull request closed without merging**
