### PR TITLE
Update rpc-tests.py

### PR DESCRIPTION
**Pull request by mdr0id**
Testing the sharding against the cloud to optimize horizontally.

Minimum updates in this PR:
1. Update the current RPC timings in the static list

End Goal:
1. Optimize the shard queues for rpc-tests.py
   a. tests existing conventions with properly updated `test_lists` timings
   b. randomly sample the non-sequential list to ideally distribute computation across N shards in CI
   c. randomly sample the non-sequential list and append the sequential only tests to optimize computation across N shards in CI

### CODE REVIEW

**Review by daira — DISMISSED** [review]
utACK. Not sure why we're bothering to reorder the `BASE_SCRIPTS` when we're going to shuffle them, though.

**Comment by mdr0id** [comment]
The timings in the list are wrong, so at a minimum we move them(each rpc test) to be in the correct timing bucket. Otherwise agree it doesn't matter much. This PR just provides a minimal diff to reduce the times of current CI, but https://github.com/zcash/zcash/pull/6247 continues this inside the cluster to optimize shards on the k8 side, instead of the limits of rpc-test.py. Upstream has started to do this but not sure they have also used our optimization to use cluster resources more per shard.

**Review by nuttycom — APPROVED** [review]
utACK modulo conflicts

**Comment by nuttycom** [comment]
@mdr0id can you look into the conflicts here?

**Comment by nuttycom** [comment]
@mdr0id Looks like it's still conflicted?

**Comment by mdr0id** [comment]
The conflict appear to be the updating of which bucket a given test should go in based on it's actual run time. I have sanity checked that none of the tests were left behind in the update(e.g. 108 vs 108). Sqaushed commits and ready for re review

**Comment by mdr0id** [comment]
I don't understand why it can't handle the reorg of tests list that are just strings and thinks it's some major conflict

**Comment by mdr0id** [comment]
Closing. Resolved in another PR and CI modifications post zcash v5.3.2

**Pull request closed without merging**
