### PR TITLE
Add logging when we receive an invalid note plaintext (using the "receiveunsafe" log category)

### LINKED ISSUE #4735: Add option to complain loudly if a v1 note plaintext is received after Canopy activation
The current behaviour (as of 4.0.0) is to treat received v1 note plaintexts normally during the ZIP 212 grace period. That's not convenient for testing that v2 note plaintexts are being sent correctly. We should have an option that complains loudly if a v1 note plaintext is received.

### PR DESCRIPTION
**Pull request by daira**
fixes #4735

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Review by therealyingtong — APPROVED** [review]
utACK

**Review by nuttycom — APPROVED** [review]
utACK (PR Gardening)

**Comment by nuttycom** [comment]
@zkbot r+

**Comment by daira** [comment]
@zkbot r+

**Review by str4d — APPROVED** [review]

**Comment by str4d** [comment]
Failed due to transient CI issues.

@zkbot retry

**Pull request merged**
