### PR TITLE
Split wallet.py

### PR DESCRIPTION
**Pull request by oxarbitrage**
Split some of the tests from `wallet.py` into its own files to make it easier to debug. 
Some of the tests moved where depending(specially in balance amounts) on previous code. As standalone, some of the hardcoded balances needed some changes. No further modifications to tests are done in this PR. 

We can split more but i think is a good start.

If this is merged it will close https://github.com/zcash/zcash/issues/4917

-----------------------
Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by @mdr0id before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

### CODE REVIEW

**Review by therealyingtong — APPROVED** [review]
utACK

**Review by daira — APPROVED** [review]
utACK. I did not check in detail that the tests are (logically) the same, but @therealyingtong has.

**Comment by daira** [comment]
@zkbot r+

**Comment by therealyingtong** [comment]
Failing on pyflakes:

```
qa/rpc-tests/wallet_zero_value.py:8:1 'test_framework.authproxy.JSONRPCException' imported but unused
qa/rpc-tests/wallet_broadcast.py:8:1 'test_framework.authproxy.JSONRPCException' imported but unused
```

and on a request to GitHub tag API:

```
Traceback (most recent call last):
  File "./qa/zcash/updatecheck.py", line 387, in <module>
    main()
  File "./qa/zcash/updatecheck.py", line 333, in main
    if dependency.is_up_to_date():
  File "./qa/zcash/updatecheck.py", line 146, in is_up_to_date
    return len(self.released_versions_after_current_version()) == 0
  File "./qa/zcash/updatecheck.py", line 139, in released_versions_after_current_version
    for release in self.known_releases():
  File "./qa/zcash/updatecheck.py", line 132, in known_releases
    self.cached_known_releases = sorted(self.release_lister.known_releases())
  File "./qa/zcash/updatecheck.py", line 163, in known_releases
    all_tags = self.all_tag_names()
  File "./qa/zcash/updatecheck.py", line 181, in all_tag_names
    raise RuntimeError("Request to GitHub tag API failed.")
RuntimeError: Request to GitHub tag API failed.
```

**Comment by nuttycom** [comment]
@zkbot try

**Review by daira — APPROVED** [review]
ACK ada04aa01d1301c4ca3fc22158b9f926fdd419b6

**Comment by nuttycom** [comment]
@zkbot r+

**Pull request merged**
