### PR TITLE
Update boost to v1.70.0 to eliminate build warning

### LINKED ISSUE #3947: build warning boost integer_log2.hpp deprecated
Building `zcash` on (at least) Linux debian Ubuntu 18.04.2 LTS generates the following compile warning (irrelevant path prefix removed):
```
In file included from [...]include/boost/random/detail/integer_log2.hpp:19:0,
                 from [...]include/boost/random/detail/large_arithmetic.hpp:19,
                 from [...]include/boost/random/detail/const_mod.hpp:23,
                 from [...]include/boost/random/detail/seed_impl.hpp:26,
                 from [...]include/boost/random/mersenne_twister.hpp:30,
                 from [...]include/boost/uuid/random_generator.hpp:17,
                 from [...]include/boost/uuid/uuid_generators.hpp:17,
                 from wallet/gtest/test_paymentdisclosure.cpp:26:
[...]include/boost/pending/integer_log2.hpp:7:59: note: #pragma message: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/integer/integer_log2.hpp>");
```
Since this is just a warning, the build completes successfully, but the warning is still disconcerting. This problem was introduced as described here: https://github.com/zcash/zcash/issues/3786#issuecomment-480393016. The fix is to upgrade to boost version 1.70.0 when it becomes available (until then, fixing this issue is blocked).

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #3947.

### CODE REVIEW

**Comment by LarryRuane** [comment]
Changes are documented here: https://www.boost.org/users/history/version_1_70_0.html
I verified that the warning no longer appears when building (`zcutil/build.sh`) but I didn't try running any of the tests.

**Comment by bitcartel** [comment]
Has a Gitian build been run against this branch/commit to verify updating the dependency doesn't break Gitian?

**Comment by daira** [comment]
utACK. I did not check the hash. I did read the changelog and found the following potentially-relevant-to-us fixed security issues in the Filesystem component:

* Fixed a few instances of dereferencing `std::string::end()` in path implementation.
* Fixed possible use of uninitialized data in directory iterator increment operation on Linux.

**Comment by LarryRuane** [comment]
Charlie's helping me get up my system to do Gitian builds. You may want to wait for that before r+. I'll post here when I've finished testing that.

**Comment by LarryRuane** [comment]
Well, it seems I can't do a Gitian build because that requires VirtualBox, but I run my Linux in VB and nested virtualization doesn't seem to be supported. But @charlieok  said he'd try tomorrow. (Thanks, Charlie!)

**Comment by garethtdavies** [comment]
I tried a Gitian build of this and it failed with 

```
In file included from bitcoind.cpp:9:0:
main.h:29:26: fatal error: addressindex.h: No such file or directory
 #include "addressindex.h"
                          ^
compilation terminated.
Makefile:5689: recipe for target 'zcashd-bitcoind.o' failed
make[2]: *** [zcashd-bitcoind.o] Error 1
make[2]: Leaving directory '/home/debian/build/zcash/distsrc-x86_64-unknown-linux-gnu/src'
Makefile:5737: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/debian/build/zcash/distsrc-x86_64-unknown-linux-gnu/src'
Makefile:615: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

To check I tried the current Zcash master and this also failed with the same. Checking through commits since 2.0.4 looks like this one is the issue e73326eed0d987a6a90aac93745059f9be212d77

I confirmed this by running the previous commit 926fd0ce2836fd665a956f52566824ecbe143c47 and that built fine and indeed e73326eed0d987a6a90aac93745059f9be212d77 fails.

So, I guess this can't be confirmed to build via Gitian until that issue is resolved?

**Comment by garethtdavies** [comment]
I cherrypicked this commit and applied on top of v2.0.4 and that does indeed build via Gitian.

**Comment by charlieok** [comment]
[gitian_hashes.txt](https://github.com/zcash/zcash/files/3090048/gitian_hashes.txt)

I did a gitian build of the latest commit on this PR: https://github.com/LarryRuane/zcash/commit/dfc13c5d1042ae35a7c13c4e607e5cc74abcc15b

The generated file of associated hashes is attached, on the assumption that the gitian concern was about the newer version of boost breaking reproducibility, in case anyone else would like to compare their result with mine.

**Comment by garethtdavies** [comment]
@charlieok did that actually complete or did it fail as looking at those hashes the `out_manifest` is empty? I just destroyed my VM and recreated and still get in `gitian-builder/var/build.log`

```main.h:29:26: fatal error: addressindex.h: No such file or directory
 #include "addressindex.h"```

**Comment by charlieok** [comment]
@garethtdavies Thanks for catching that. I just quickly ran the build and copied the result here without inspecting it. I destroyed the VM afterward but I'll try running it again.

**Comment by charlieok** [comment]
Yes, it looks like the gitian build is failing. Attaching the contents of `/home/vagrant/gitian-builder/var/build.log` in my VM:
[build.log](https://github.com/zcash/zcash/files/3090352/build.log)

**Comment by garethtdavies** [comment]
That looks like a different issue and possibly related to the latest commit to zcash-gitian as `curl` now isn't available? https://github.com/zcash/zcash-gitian/commit/367b6e9ecc606fe5b297df87fd7d5b99ebaaf768

**Comment by charlieok** [comment]
@garethtdavies I did wonder about that but I verified that curl was installed in the VM:

```bash
vagrant@zcash-build:~$ dpkg --status curl
Package: curl
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 346
Maintainer: Alessandro Ghedini <ghedo@debian.org>
Architecture: amd64
Multi-Arch: foreign
Version: 7.52.1-5+deb9u9
Depends: libc6 (>= 2.17), libcurl3 (= 7.52.1-5+deb9u9), zlib1g (>= 1:1.1.4)
Description: command line tool for transferring data with URL syntax
 curl is a command line tool for transferring data with URL syntax, supporting
 DICT, FILE, FTP, FTPS, GOPHER, HTTP, HTTPS, IMAP, IMAPS, LDAP, LDAPS, POP3,
 POP3S, RTMP, RTSP, SCP, SFTP, SMTP, SMTPS, TELNET and TFTP.
 .
 curl supports SSL certificates, HTTP POST, HTTP PUT, FTP uploading, HTTP form
 based upload, proxies, cookies, user+password authentication (Basic, Digest,
 NTLM, Negotiate, kerberos...), file transfer resume, proxy tunneling and a
 busload of other useful tricks.
Homepage: http://curl.haxx.se

vagrant@zcash-build:~$ type curl
curl is /usr/bin/curl
```

**Comment by charlieok** [comment]
Just tried rebuilding using commit https://github.com/zcash/zcash-gitian/commit/0abc644d62cb89e9d840e0d82d56702023cff20e to verify that the recent update did not cause the error I posted above. It did not -- it failed in the same way.

**Comment by LarryRuane** [comment]
Thanks, @garethtdavies and @charlieok, I don't understand what the problem with https://github.com/zcash/zcash/commit/e73326eed0d987a6a90aac93745059f9be212d77 is; that commit did add a new source file, `src/addressindex.h`, but it's clearly part of that commit (and of course the normal build succeeds). I'm not sure what to do now, maybe create a new ticket that says Gitian build doesn't succeed with current zcash master?

**Comment by charlieok** [comment]
Apologies for the noise above. My posts above were in response to a request from @LarryRuane to run a gitian build on this branch, and I did not see until after my initial post that @garethtdavies had already found an issue and apparently traced it to its source.

**Comment by mms710** [comment]
We're blocking this PR on getting https://github.com/zcash/zcash/pull/3966 just so we can make sure we have a passing build before we merge things.

**Comment by daira** [comment]
@zkbot r+

**Comment by LarryRuane** [comment]
I just rebased from zcash master to pick up the Gitian build fix #3966.

**Comment by ebfull** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
Transient failure, timed-out.
```
=== Running testscript key_import_export.py ===
command timed out: 1200 seconds without output running ['./qa/zcash/full_test_suite.py', 'rpc'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=4473.756010
```
@zkbot retry

**Pull request merged**
