### PR TITLE
Handle full Zcash version string in AC_INIT

### PR DESCRIPTION
**Pull request by str4d**
#943 added new definitions to `configure.ac` for the Zcash version number. But in `AC_INIT`, the leading `.z` was not being parsed separately, resulting instead in that particular substitution failing (visible in e.g. test output headers). This PR adds a separate `define()` specifically for this case.

### CODE REVIEW

**Comment by str4d** [comment]
I'd certainly prefer to find a way to have `_CLIENT_VERSION_ZCASH` substitution work properly in `AC_INIT`, but I can find no documentation for `define()` anywhere (it doesn't appear to be part of either autoconf or m4), and have no idea how its substitution is done (and therefore what syntax could be used to fix this).

**Comment by str4d** [comment]
Fixed to now have no duplication. The `define()` macro is part of m4, and the new solution uses the fact that macros can have arguments.

**Comment by ebfull** [comment]
Where did @daira's comment go?

**Comment by str4d** [comment]
I don't know 🤔 It wasn't a commit comment...

**Comment by str4d** [comment]
Figured it out - @daira's comment was on the commit, not on the PR, so it appeared in my repo rather than here (because I wasn't notified on my Zcash email). When I rebased, the comment was disassociated.

**Comment by daira** [comment]
ACK

**Comment by ebfull** [comment]
Merging this will delay the release we want to do today, and I feel it's low priority.

**Comment by ebfull** [comment]
Alternatively, merge this in as part of the release PR!

**Comment by defuse** [comment]
Sure, I'll try to remember to do that :)

**Pull request merged**
