### PR TITLE
fix build error due to usage of obsolete boost_system-mt

### LINKED ISSUE #2304: configure: error: Could not link against boost_system-mt !
When executing:
`./zcutil/build.sh --disable-rust -j$(nproc)`

I get:
```
...
checking miniupnpc/upnperrors.h presence... yes
checking for miniupnpc/upnperrors.h... yes
checking for main in -lminiupnpc... (cached) yes
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system-mt... no
configure: error: Could not link against boost_system-mt !
```

### The version of Zcash you were using:
v1.0.8-1

### Machine specs:
```
uname -or
4.10.0-20-generic GNU/Linux
uname -a
Linux wks-PC 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 gcc --version
gcc (Ubuntu 7-20170407-0ubuntu2) 7.0.1 20170407 (experimental) [trunk revision 246759]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by rofl0r**
closes #2304 for real

### CODE REVIEW

**Comment by bitcartel** [comment]
Good catch!  Turns out `boost_system-mt` dropped the `-mt` suffix a few years ago.

**Comment by bitcartel** [comment]
@zkbot try

**Comment by str4d** [comment]
It shouldn't be using the default system path - it is using the `depends/` subsystem, and our Boost libraries are built with the `-mt` suffix. So if we want to make this change, we also need to make changes to the Boost dependency package.

**Comment by rofl0r** [comment]
@zkbot try

**Comment by rofl0r** [comment]
could someone with privs tell the bot to try again @bitcartel  @str4d thanks

**Comment by rofl0r** [comment]
hello ? is everybody in holidays over at zcash corporation ?

**Comment by daira** [comment]
Just busy with the 1.0.15 release. @zkbot try

**Comment by rofl0r** [comment]
yay, it built. there's one test failure `Failing tests: mempool_tx_input_limit.py` but i doubt its related

**Comment by bitcartel** [comment]
Yeah, that test needs to be looked at, some non-deterministic behaviour, which sometimes fails.

@zkbot retry

**Comment by daira** [comment]
Needs one more ACK.

**Comment by str4d** [comment]
utACK

@zkbot r+

**Comment by str4d** [comment]
Transient failure on unrelated RPC test.

@zkbot retry

**Pull request merged**
