### PR TITLE
Rename libzerocash to libzcash

### PR DESCRIPTION
**Pull request by alfiedotwtf**
Rename libzerocash to libzcash in Makefiles and source (C++ namespace) #960

### CODE REVIEW

**Comment by ebfull** [comment]
Cool! One catch: we still have some old "libzerocash" things in `src/zerocash` so I'd like to leave their names as "libzerocash" so we can keep track of them.

**Comment by daira** [comment]
Can't be just rename those as well now? It's just ``zerocash/utils/util.cpp``, right?

**Comment by ebfull** [comment]
I'd rather we just removed all of those, replacing them with tested variants inside of `zcash/util.cpp`.

**Comment by ebfull** [comment]
(Let's remove those as another PR later on, for now this PR just needs to avoid renaming `libzerocash` in all the `src/zerocash/` stuff.)

**Comment by alfiedotwtf** [comment]
Ok, removing now.

**Comment by alfiedotwtf** [comment]
Just checking - did you still want the namespace changed (as this is inside src/zerocash/)?

**Comment by ebfull** [comment]
Just anything inside of `src/zerocash` should not be changed to `libzcash` yet. The name of the static library and other such things can be changed though, as you've done.

**Comment by alfiedotwtf** [comment]
Let me know if there's anything else that needs to be done.

**Comment by ebfull** [comment]
I think this is perfect, thanks!

@zkbot r+

**Pull request merged**
