### PR TITLE
Release v1.0.14

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by arcalinea** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient failure in `zkey_import_export` (we really need to pin that down).

@zkbot retry

**Comment by arcalinea** [comment]
Looks like if fails on build, not on `zkey_import_export`? 

```
checking whether the linker accepts -Wl,-z,relro... no
configure: error: Cannot enable RELRO
program finished with exit code 1
elapsedTime=520.446825
```

**Pull request merged**
