### PR TITLE
Less verbose tests

### LINKED ISSUE #2453: RPC test output is too verbose and includes expected failures by default
For example, successful test output for wallet_protectcoinbase.py includes, by default:
```
  waiting for async operation opid-22ebcf29-7202-41af-8034-3399d0bd5fb9
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 0.00000053 more to avoid creating invalid change output 0.00000001 (dust threshold is 0.00000054)
  waiting for async operation opid-f0dacab2-989e-40bc-955e-29d35b2c8513
  ...returned status: failed
  ...returned error: Insufficient transparent funds, have 10.00, need 10000.0001
  waiting for async operation opid-a0ddd003-6a68-4bf3-9f2e-32db54bdf925
  ...returned status: failed
  ...returned error: Insufficient protected funds, have 9.9998, need 10000.0001
```

which could lead someone to conclude there is a problem when there is none.

### PR DESCRIPTION
**Pull request by per-gron**
Fixes #2453 and deduplicates some related code.

### CODE REVIEW

**Comment by daira** [comment]
Also fixes #2720.

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
Please fix the pyflakes warnings. (Our CI enforces that all builds must be pyflakes-clean.) https://ci.z.cash/#/builders/2/builds/211/steps/5/logs/unused

**Comment by per-gron** [comment]
@daira Sure! I amended the commit. Lmk if you prefer the fix in a separate commit.

**Comment by daira** [comment]
I don't see the fix; those files still import ``time`` when they no longer use it directly.

**Comment by daira** [comment]
utACK.

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
