### PR TITLE
Mark Orchard notes as locked

### LINKED ISSUE #5568: Add ability to mark notes as locked and spent to the Orchard wallet.
Locked notes are those that have been selected for use in a transaction that has not yet been mined. 
- [ ] When a note is used in construction of a transaction, it should be locked when the transaction is submitted to the network.
- [ ] When a transaction expires without having been mined, the notes used in its construction should be unlocked.
- [ ] Note locking metadata should be persisted to the wallet database, loaded to the wallet on wallet load, and removed when notes are unlocked.

### PR DESCRIPTION
**Pull request by therealyingtong**
Closes #5568

### CODE REVIEW

**Review by nuttycom — COMMENTED** [review]
I don't see in here where notes are actually being locked and unlocked?

**Comment by therealyingtong** [comment]
> I don't see in here where notes are actually being locked and unlocked?

This is currently only done in `z_mergetoaddress`, which doesn't yet support UAs.

**Comment by nuttycom** [comment]
This can be made usable after #6217

**Comment by nuttycom** [comment]
@therealyingtong I can't reopen this, and it's not clear why.

**Pull request closed without merging**
