### PR TITLE
Rename COPYING to COPYING.md

### PR DESCRIPTION
**Pull request by jackgavigan**
Looks like this file was originally a text file (per @str4d) but has since been edited to include markdown. However, without the .md extension, Github displays it as a text file.

### CODE REVIEW

**Comment by daira** [comment]
NACK, because almost every source file has this comment:
```
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.
```

**Comment by daira** [comment]
We should just remove the Markdown (which was my fault I think).

**Comment by daira** [comment]
Yes it was my fault: 86b671eae08893300da732e23210061fde875351

**Comment by jackgavigan** [comment]
Ah, I didn't realise that several hundred files reference COPYING. 😆

**Pull request closed without merging**
