### PR TITLE
Create a checklist for all zcashd PRs

### PR DESCRIPTION
**Pull request by mms710**
All items in the checklist must be done before a PR can be merged.

### CODE REVIEW

**Comment by daira** [comment]
Checkboxes only work when they're in a bulleted list. See https://github.com/zcash/zcash/blob/pr-checklist-addition/.github/pull_request_template.md for how it currently renders. (Bulleted lists have a blank line and then each line starts with "* ", followed by the checkbox.)

**Comment by mms710** [comment]
Thanks @daira ! Okay I think I may have actually fixed the issues now.

**Comment by daira** [comment]
That works on GitHub, but remember that the PR description will end up in the git merge commit, where it will be displayed as text by git. So it would be preferable to avoid `<br/>`. That will render correctly as long as the bulleted list is preceded and followed by a blank line.

**Comment by mms710** [comment]
Should I just use \ instead of <br/>? I think both should work but when I didn't use either and I tested it in a markup previewer, the last comment was indented strangely as it if were part of the bulleted list but just without a checkbox or bullet. Is there another solution I'm missing?

**Comment by str4d** [comment]
As long as you leave a blank line between the last bulleted list item and subsequent text, it should be rendered as a separate paragraph. No newline-related markup should be necessary beyond actual newlines.

**Comment by mms710** [comment]
Alright I'll attempt that, amend the PR and then check it out before I ask for a review. Thanks!

**Comment by mms710** [comment]
YAS! Okay you were all right and I got the formatting looking the way I wanted. Let me know if you have further thoughts.

**Comment by defuse** [comment]
ACKed (although I haven't checked that relevant documentation for this PR has been reviewed by the docs team)

**Comment by mms710** [comment]
Closing this PR because I found out I didn't follow the right process to open it (I needed to create my own fork and make a PR from there in order to do this properly). Here's a link to the new PR where I think I've followed the right process: https://github.com/zcash/zcash/pull/3948

**Pull request closed without merging**
