### PR TITLE
depends: Update to latest config.guess & config.sub

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
The updated files return `x86_64-pc-linux-gnu` where they previously returned `x86_64-unknown-linux-gnu`. I've updated the map in the `native_rust` to handle this (it will also continue to work for `x86_64-unknown-linux-gnu` if that is still returned on any platforms).

@zkbot r+

**Comment by str4d** [comment]
There were several other places we were hard-coding `x86_64-unknown-linux-gnu`, causing test failures. I've updated them all as appropriate.

@zkbot r+

**Comment by str4d** [comment]
Okay, **that** one was just a transient failure.

@zkbot retry

**Pull request merged**
