### PR TITLE
Fix z_importviewingkey startHeight parameter

### LINKED ISSUE #2937: Bugfix: z_importviewingkey RPC call missing startHeight
If I call RPC command z_importviewingkey with one or two arguments, it works OK.
But if I call RPC with three arguments, adding startHeight, RPC returns with error (usage text).

So it seems to me RPC is not configured properly, it does not understand the third argument.

Using zcash 1.0.14

### PR DESCRIPTION
**Pull request by str4d**
Closes #2937.

Co-authored-by: Tomas M <tomas@slax.org>

### CODE REVIEW

**Comment by daira** [comment]
@zkbot r+

**Comment by daira** [comment]
(I did change the first comment to credit @Tomas-M.)

**Comment by str4d** [comment]
That should work (though GitHub usually requires name+email for linking to their profile)

**Comment by str4d** [comment]
Failed due to a transient failure.

@zkbot retry

**Pull request merged**
