### PR TITLE
Remove Bitcoin mainnet and testnet seeds.

### PR DESCRIPTION
**Pull request by bitcartel**
Simple patch for issue #651 to remove hard-coded mainnet and testnet seeds
- they currently point to bitcoin nodes
- some are .onion addresses but Tor support has not yet been added
- gets rid of error messages in debug.log which might confuse people testing the alpha builds

### CODE REVIEW

**Comment by ebfull** [comment]
Nice! Let's remove them all though, even for mainnet.

**Comment by bitcartel** [comment]
Done!

**Comment by ebfull** [comment]
Thanks, ACK!

If @str4d ACKs I'll r+.

**Comment by daira** [comment]
ACK!

**Comment by ebfull** [comment]
Works!

@zkbot r+

**Pull request merged**
