### PR TITLE
Update ed25519 zebra

### LINKED ISSUE #6648: Ensure we depend on sha2 0.10 (not 0.9.x) and metrics 0.21 (not 0.20.x)
This can be done by upgrading `bs58`, `ed25519-zebra`, and `metrics`. The immediate motivation for filing this ticket is to allow Zebra to remove exceptions they have in their `deny.toml` due to their `zcash_script` dependency: https://github.com/ZcashFoundation/zebra/pull/6624/files#r1187912655 , but it also deduplicates the `sha2` dependency for us.

### PR DESCRIPTION
**Pull request by nuttycom**
This deduplicates sha2, rand-core, block-buffer, digest, and ahash. (It adds duplications for hashbrown and libm which are less important.) @daira has audited some but not all of the new dependencies.

fixes #6648

### CODE REVIEW

**Comment by nuttycom** [comment]
Closing in favor of #6709

**Comment by nuttycom** [comment]
Reopening because 86f5039 is being pulled from #6709

**Comment by daira** [comment]
Marking as draft since it will need to be rebased.

**Comment by nuttycom** [comment]
@daira I can't seem to push the rebase over this branch; can you modify the branch permissions to allow maintainers to edit it?

**Comment by nuttycom** [comment]
Opened #6717 instead.

**Pull request closed without merging**
