### PR TITLE
Enable -alertnotify for hard fork detection. Test it.

### LINKED ISSUE #131: Enable loud hard-fork detection
This feature may be a fairly light configuration of an existing feature: #109 is for documenting the existing feature, and it links to this bitcoin-development message which alludes to the feature:

https://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg06273.html

### LINKED ISSUE #171: disable RPC interface if you detect you are on the short side of a fork
A couple of weeks ago, the day that Andrew left IEEE ("Oakland") and came to stay with Nathan, Andrew and Brian and I had a conversation about "forward-compatibility" and "future-proofing" features for Zcoin. Out of that conversation, only two of the options seemed to me to be "shallow rabbit holes", where I could see the bottom of how many decisions and how much work we'd have to do in order to implement the thing: shipping with The Update Framework (TUF) http://theupdateframework.com/ (or any other comparable secure software updater), and having the Zcoin node freeze with a warning message if it detects that it is on the short side of a fork. This ticket is about the second one of those. https://github.com/Electric-Coin-Company/zerocashd/issues/170 is about TUF.

### PR DESCRIPTION
**Pull request by defuse**
Closes #171. Closes #131.

### CODE REVIEW

**Comment by defuse** [comment]
Another idea for testing this (which would be kinda cool, I think) is to add a `-blockmaxforce` switch to override the maximum blocksize sanity check in `CreateNewBlock()`, and then in the RPC test have a second node that mines a chain of blocks bigger than MAX_BLOCK_SIZE.

**Comment by ebfull** [comment]
ACK

**Comment by ebfull** [comment]
I think @nathan-at-least might enjoy reviewing this one.

**Comment by ebfull** [comment]
(But I won't block this for it.)

@zkbot r+

**Comment by daira** [comment]
Reviewing.

**Pull request merged**
