### PR TITLE
Don't log to stdout if a file logger is configured.

### PR DESCRIPTION
**Pull request by nuttycom**
This fixes an error introduced by 5dce316f1010f7b06ad496e0d222e8f3595bdb20

### CODE REVIEW

**Comment by steven-ecc** [comment]
utACK

**Review by steven-ecc — APPROVED** [review]
Looks good to me.

**Review by str4d — APPROVED** [review]
utACK. Good catch!

**Comment by str4d** [comment]
@zkbot r+

**Review by daira — COMMENTED** [review]
utACK

**Pull request merged**
