### PR TITLE
Bash completion

### PR DESCRIPTION
**Pull request by str4d**
This PR pulls in bitcoin/bitcoin#8289, updates the bash completion files for use with Zcash, and bundles them into the Debian package.

### CODE REVIEW

**Comment by str4d** [comment]
These can be tested locally by sourcing each bash-completion file (`. contrib/bitcoind.bash-completion` etc), and then using the locally-built binaries (e.g. `./src/zcashd [TAB]`).

**Comment by str4d** [comment]
@bitcartel correct, it is just auto-completion for arguments. I did not bother to remove them because it made the diff simpler, and in practice no users will encounter them - the initial RPC commands are auto-completed from the output of `zcash-cli help`, which itself queries `zcashd` across RPC and will therefore always be accurate.

**Comment by ebfull** [comment]
I'm happy with this for now. ACK

**Comment by bitcartel** [comment]
In bash, I sourced the completion files, and autocomplete worked for zcashd but it did not work for zcash-cli.

**Comment by str4d** [comment]
@bitcartel did not work at all, or only showed the `-foo` options? The latter is the case while `zcashd` is not running, because the autocomplete commands are fetched live.

**Comment by bitcartel** [comment]
@str4d zcashd is running.  Autocomplete does not work at all for zcash-cli.
``` echo $BASH_VERSION
4.3.46(1)-release
```

**Comment by str4d** [comment]
@bitcartel I'm on the same Bash version as you, so that's not the issue.

After sourcing the various bash-completion files, what is the output of `complete -p | grep zcash`? I just found the following in one CLI after sourcing `contrib/bitcoind.bash-completion`:

```
$ complete -p | grep zcash
complete -F _minimal ./src/zcashd
complete -F _zcashd zcashd
```

ie. something else was blocking it. When I opened a new CLI and tried again, I correctly saw only the second line.

**Comment by bitcartel** [comment]
New terminal resolves the issue.

**Comment by bitcartel** [comment]
ACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
