### PR TITLE
Add checkpoint at block height 15000

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by str4d** [comment]
NACK, doesn't satisfy the criteria for a good checkpoint block:
```cpp
/**
 * What makes a good checkpoint block?
 * + Is surrounded by blocks with reasonable timestamps
 *   (no blocks before with a timestamp after, none after with
 *    timestamp before)
 * + Contains no strange transactions
 */
```

**Comment by bitcartel** [comment]
Checkpoint is now block 15000 which meets criteria above.  Rebased against master.

**Comment by str4d** [comment]
utACK

**Comment by ebfull** [comment]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
