### PR TITLE
Include the package name and version in metrics UI.

### PR DESCRIPTION
**Pull request by nejucomo**
Scratching an itch: the metrics UI now displays the official package name and version. This patch should also support any source forks which should have renamed their `PACKAGE_STRING`.

Issues:

This requires `HAVE_CONFIG_H`. I don't understand how to find the same information on other platforms. I expect builds to fail on those platforms with `PACKAGE_STRING` as an undefined symbol in `metrics.cpp`

There's no automated testing of any kind.

I'm not sure I'm using `_` correctly and couldn't find it's API documentation (nor which dependency it comes from, since I don't know how to figure that out with C++).

### CODE REVIEW

**Comment by daira** [comment]
Please rebase this on top of #3765.

**Comment by rex4539** [comment]
I guess this could be closed now.

**Comment by daira** [comment]
Why? It's still useful, it just needs to be rebased.

**Comment by rex4539** [comment]
Ah, I was under the impression that the other PR included this too.

**Comment by daira** [comment]
No the other PR still says "Zcash" in the message: https://github.com/zcash/zcash/pull/3765/files

**Comment by daira** [comment]
I resolved the conflict.

**Comment by str4d** [comment]
Replaced by #4180.

**Pull request closed without merging**
