### PR TITLE
Update copyright year to 2020

### PR DESCRIPTION
**Pull request by sandakersmann**
Update copyright year to 2020

### CODE REVIEW

**Comment by oxarbitrage** [comment]
There are a few additional places where the copyright can be updated:

https://github.com/zcash/zcash/blob/master/autogen.sh#L2-L4
https://github.com/zcash/zcash/blob/master/share/genbuild.sh#L2-L4

Also inside `doc/man/`:
https://github.com/zcash/zcash/blob/master/doc/man/zcash-tx.1#L91-L92
https://github.com/zcash/zcash/blob/master/doc/man/zcash-cli.1#L78-L79
...etc

https://github.com/zcash/zcash/blob/master/contrib/amqp/amqp_sub.py#L2

Got them by searching for string "-2019" inside the zcash project. The copyrights with just `2019` or any other single year i guess are fine, as they are the date the file was created.

**Comment by sandakersmann** [comment]
I did not aim to update all copyright headers with this PR.

**Comment by oxarbitrage** [comment]
ok, why the ones you updated are special ?

**Comment by sandakersmann** [comment]
Because those counts towards the license and software settings. I can update the others as well, but I suspect it will touch many files and make life harder for other PRs. Best to just merge this first I think.

**Comment by daira** [comment]
The doc/man files are generated and do not need to be manually updated. They're generated by `make_release.py` from the help output printed by https://github.com/zcash/zcash/blob/868c63f92d7db1905ccee4cda936f3e4ed5ca462/src/util.cpp#L911-L912

**Comment by daira** [comment]
@zkbot r+

**Comment by oxarbitrage** [comment]
Got it, thank you @sandakersmann and @daira

**Pull request merged**
