### PR TITLE
Rename bitcoin.conf and bitcoind.pid

### PR DESCRIPTION
**Pull request by defuse**
This leaves the mentions of those files in `doc/` and `contrib/` unchanged.

**FORCE PUSHED**

### CODE REVIEW

**Comment by defuse** [comment]
I ran all the tests locally and they pass.

**Comment by defuse** [comment]
#844

**Comment by ebfull** [comment]
This PR contains a binary file (zcashPerformance) for some reason.

**Comment by defuse** [comment]
@ebfull: Fixed!

**Comment by defuse** [comment]
Warning: I force pushed

**Comment by ebfull** [comment]
ACK

**Comment by daira** [comment]
ACK

**Comment by daira** [comment]
(I did not check for remaining instances of ``bitcoin.*`` files, just correctness of the changes that are in the diff.)

**Comment by daira** [comment]
Note that we also need something in the alpha guide/release notes to document that the filename has changed, and that people should rename ``bitcoin.conf`` if they have edited it.

**Comment by defuse** [comment]
@zkbot r+

**Comment by defuse** [comment]
Opened #912 to update the guide.

**Pull request merged**
