### PR TITLE
Update UniValue subtree

### PR DESCRIPTION
**Pull request by str4d**
This brings us up-to-date with upstream Bitcoin's version of the library.

Includes a commit cherry-picked from bitcoin/bitcoin#12193.

### CODE REVIEW

**Comment by str4d** [comment]
After this PR, the diff from upstream consists of:
- fc4a70e8128f1dced9f241074f7f8bbc78d93dfe:
  - `s/UniValue::__pushKV/UniValue::_pushKV/g`
  - Removing `__` prefixes from include guards.
- 5a1e6853c18bc4741c35918f1fb0c96854122be7: `-pthread` additions.
- HTTP -> HTTPS in comments etc.

**Review by nuttycom — APPROVED** [review]
utACK

**Comment by nuttycom** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient failure.

@zkbot retry

**Pull request merged**
