### PR TITLE
Clarify help text of dumpprivkey

### LINKED ISSUE #3190: Clarify help text of dumpprivkey
It only works on t-addrs, but the help text just refers to a `zcashaddress`, which has confused at least one user.

### PR DESCRIPTION
**Pull request by Eirik0**
Closes #3190

### CODE REVIEW

**Comment by str4d** [comment]
Let's use this PR to test Homu's rollup feature.

**Comment by Eirik0** [comment]
@zkbot try

**Comment by Eirik0** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot rollup

**Comment by str4d** [comment]
Finished the experiment. Looks like what Homu does for rollups is just remember them all, and then when you click the "Create a rollup" button it creates a new PR containing them all. That's not quite the workflow I thought it would be, so for now let's not use it.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
