### PR TITLE
Bech32 encoding support

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#8578
- bitcoin/bitcoin#11167
  - Only the second and third commits (first is in #3228, fourth depends on #2390, later ones are SegWit-specific).
- bitcoin/bitcoin#12757
  - Only the change to `src/bech32.h`

Part of #3058.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
Updated PR so that it now contains both the `CBitcoinAddress` and `CBitcoinSecret` refactors.

@zkbot try

**Comment by str4d** [comment]
Implemented the changes to remove `CZCEncoding`, and then pulled in the remaining upstream changes to clean up transparent address encoding.

@zkbot try

**Comment by str4d** [comment]
Missed some includes in Zcash-specific code; pushed a commit to fix.

@zkbot try

**Comment by str4d** [comment]
Transient failure in one of the RPC tests.

**Comment by str4d** [comment]
Rebased on master to account for #3213. Opened #3228 with the next set of commits.

**Comment by str4d** [comment]
Rebased on master to fix the (tiny) merge conflict. This means the commits in #3228 are no longer exactly the same here (different IDs), but they did not change at all, and I'll rebase again to remove them once that PR is merged.

**Comment by str4d** [comment]
I'm gonna interrupt the try above, as we've already run one.

**Comment by str4d** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
Build error, nullifier test time out.
```
Tests successful
--- Success: wallet_overwintertx.py ---
=== Running testscript wallet_nullifiers.py ===
command timed out: 1200 seconds without output running ['./qa/zcash/full_test_suite.py', 'rpc'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=3088.330927
```

**Comment by str4d** [comment]
Yeah, transient failures (AWS-related likely).

@zkbot retry p=1

**Comment by str4d** [comment]
Transient failure.

@zkbot retry

**Comment by str4d** [comment]
Another transient hang in one of the EC2 workers 😠

@zkbot retry

**Pull request merged**
