### PR TITLE
Equihash - Optimization to DistinctIndices function

### PR DESCRIPTION
**Pull request by bitcartel**
Update to DistinctIndices function (for issue #857).

Running time results from zcbenchmark solveequihash are upto 5% quicker.

### CODE REVIEW

**Comment by str4d** [comment]
Huh, when originally implementing this I thought that would be slower. But I guess the slow party of the function is the sorting. Shows what I get for premature optimisation 😂

Two issues:

- This currently uses tab when it should user spaces.
- This is probably going to conflict with #921.

**Comment by ebfull** [comment]
@zkbot try

**Comment by daira** [comment]
What's the expected number of indices in the input arrays (in terms of n and k)? If it is small enough then you can do better than either sorting, or the quadratic loop in this PR, by using a bit mask with an entry for each possible index. The complexity of that is Θ(max(a.size(), b.size())) with a small constant factor.

**Comment by daira** [comment]
Pseudocode for that approach:
```
static bitmap = new bool[max_index+1]; // initially all false
bool DistinctIndices(a, b) {
    ret = false;
    for i in a.indices {
        bitmap[i] = true;
    }
    for j in b.indices {
        if (bitmap[j]) goto cleanup;
    }
    ret = true;
cleanup:
    for i in a.indices {
        bitmap[i] = false;
    }
    return ret;
}

**Comment by str4d** [comment]
The arrays increase in length each round from `2^1` to `2^(k-1)`.

**Comment by daira** [comment]
I meant to ask what is the range of the indices. (I subsequently edited the comment with that correction.)

**Comment by str4d** [comment]
Ah. `2^((n/(k+1))+1)`.

**Comment by daira** [comment]
So ``bitmap`` would be 2^25 bits (4 MiB) for n = 144, k = 5, which is probably too much. Instead you could use a card-marking approach like this:
```
card_bits = 12;
static bitmap = new bool[(max_index+1) >> card_bits]; // initially all false
bool DistinctIndices(a, b) {
    ret = false;
    for i in a.indices {
        bitmap[i >> card_bits] = true;
    }
    for j in b.indices {
        if (bitmap[j]) {
            for i in a.indices {
                if (i == j) goto cleanup;
            }
        }
    }
    ret = true;
cleanup:
    for i in a.indices {
        bitmap[i >> card_bits] = false;
    }
    return ret;
}
```

**Comment by str4d** [comment]
@bitcartel #921 has now landed, so you can rebase and rework this PR without worrying about future merge conflicts (I won't be touching that part of Equihash) :smile:

**Comment by ebfull** [comment]
@bitcartel We're hoping to land this soon, can you rebase? (If not we will rebase for you.)

**Comment by bitcartel** [comment]
@ebfull Rebased cleanly in a new PR #1005.

**Pull request closed without merging**
