### PR TITLE
Replace setInventoryKnown with a rolling bloom filter

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from bitcoin/bitcoin#7133.
- Excluding for last commit, which needs bitcoin/bitcoin#7129.

Part of #2074.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK, verified against bitcoin/bitcoin#7133

**Comment by str4d** [comment]
Not merging this until after the 4.3.0 release.

**Comment by str4d** [comment]
But in the meantime:

@zkbot try

**Review by daira — APPROVED** [review]
utACK. @str4d is checking whether there have been any upstream changes to `CRollingBloomFilter`.

**Comment by str4d** [comment]
There have been; I will backport them in a separate PR.

@zkbot r+

**Pull request merged**
