### PR TITLE
Added documentation warnings about DNS rebinding attacks, issue #3841

### PR DESCRIPTION
**Pull request by zebambam**
For AMQP and ZMQP.

### CODE REVIEW

**Comment by zebambam** [comment]
This is the same as before, but squashed, from a proper branch, matching the issue number etc..

**Comment by mdr0id** [comment]
utACK

**Comment by mdr0id** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
@mdr0id Looks like a transient failure and you can retry.

**Comment by zebambam** [comment]
This is for issue #3841

**Comment by bitcartel** [comment]
The test failed on one of the builders:
```
[ RUN      ] WalletTests.ClearNoteWitnessCache
wallet/gtest/test_wallet.cpp:1462: Failure
Value of: (bool) saplingWitnesses[1]
  Actual: true
Expected: false
wallet/gtest/test_wallet.cpp:1473: Failure
Value of: (bool) saplingWitnesses[1]
  Actual: true
Expected: false
[  FAILED  ] WalletTests.ClearNoteWitnessCache (3 ms)
```

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
Another transient failure this time with kitchen sink builder.
https://ci.z.cash/#/builders/10/builds/822/steps/7/logs/stdio

**Comment by bitcartel** [comment]
@zkbot retry

**Comment by bitcartel** [comment]
@zkbot retry

**Pull request merged**
