### PR TITLE
Closes #1988. Add qa test for cache invalidation bug found in v1.0.0 to v1.0.3.

### LINKED ISSUE #1988: Add qa test for cache invalidation bug fixed in 1.0.4
As described in point 1 here: https://blog.z.cash/new-release-1-0-4/

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by bitcartel** [comment]
This test verifies that a bug fix was applied correctly in v1.0.4.  The test will pass with v1.0.4 or later, but fail with earlier versions.  To verify, reviewers can checkout v1.0.3 and run this version of the qa test https://gist.github.com/bitcartel/f43f077beed1d724e04b6297d3a5f985 (the difference being the version in this PR uses wait_and_assert_operationid_status() from the test framework).

**Comment by mdr0id** [comment]
Tested ACK:

**v1.0.3 hangs on network exception, see below:**

`
=== Running testscript wallet_anchorfork.py ===
zcashd: main.cpp:2116: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `tree.root() == old_tree_root' failed.
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/wallet_anchorfork.py", line 129, in run_test
    self.sync_all()
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/test_framework.py", line 73, in sync_all
    sync_blocks(self.nodes)
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/util.py", line 40, in sync_blocks
    counts = [ x.getblockcount() for x in rpc_connections ]
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/authproxy.py", line 122, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
Traceback (most recent call last):
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/wallet_anchorfork.py", line 136, in <module>
    WalletAnchorForkTest().main()
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/test_framework.py", line 134, in main
  Initializing test directory /tmp/testV8mgJi
    stop_nodes(self.nodes)
  Mining blocks...
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/util.py", line 210, in stop_nodes
  waiting for async operation opid-fe29aa9e-4d30-4a74-8810-45b7c9389ff9
  ...returned status: success
  waiting for async operation opid-cc0c6880-c13a-4973-9729-9f421dfa355c
  ...returned status: success
  Unexpected exception caught during testing: [Errno 111] Connection refused
  Stopping nodes
    node.stop()
  File "/home/marsh/zcash_dev_hub/1988_zc_2/zcash/qa/rpc-tests/test_framework/authproxy.py", line 122, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1091, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 939, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest

`

**v1.0.4 passes:**

`=== Running testscript wallet_anchorfork.py ===
  Initializing test directory /tmp/testmw_EtX
  Mining blocks...
  waiting for async operation opid-57330168-fc0b-48f9-8a8f-2e47bf17b36e
  ...returned status: success
  waiting for async operation opid-cb30eb14-3282-4843-af3d-a729b98ae075
  ...returned status: success
  Stopping nodes
  Cleaning up
  Tests successful
--- Success: wallet_anchorfork.py ---



Tests completed: 1
successes 1; failures: 0
`

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Failed due to an issue on the Debian 9 builder which appears to be transient (because a manual build just worked fine).

@zkbot retry

**Pull request merged**
