### PR TITLE
Z5 release pr actual

### PR DESCRIPTION
**Pull request by defuse**
This includes #1024 and #1029.

### CODE REVIEW

**Comment by str4d** [comment]
ACK!

**Comment by ebfull** [comment]
ACK

**Comment by defuse** [comment]
@zkbot r+

**Comment by ebfull** [comment]
Network magics (pchStart in chainparams) need to be changed.

@zkbot r-

**Comment by ebfull** [comment]
@zkbot r+ 1ea8b009263677495d1e704072fa8ffca9993e49

**Comment by ebfull** [comment]
@zkbot force

**Comment by str4d** [comment]
Re-ACK!

**Comment by daira** [comment]
Post-hoc ACK

**Pull request merged**
