### PR TITLE
`ed25519-zebra` 3

### PR DESCRIPTION
**Pull request by str4d**
This is the versioned release of the git revision we were previously pinning.

Also bumps the other Rust dependencies.

### CODE REVIEW

**Comment by str4d** [comment]
Low-priority; we should hold off merging this until after #5391 merges.

**Comment by str4d** [comment]
The (trivial) changes since the pinned release: https://github.com/ZcashFoundation/ed25519-zebra/compare/d3512400227a362d08367088ffaa9bd4142a69c7...3.0.0

**Review by nuttycom — APPROVED** [review]
utACK

**Review by nuttycom — APPROVED** [review]
re-utACK

**Comment by nuttycom** [comment]
I note that this differs slightly from what I get from running a `cargo update` today: tokio is now available at version 1.15.0, and proc-macro2 and a couple other dependencies have slightly newer versions available.

**Comment by str4d** [comment]
It's only been three days 😭

I'll have a look locally and see if any of them are useful. I can easily update this PR again, at the cost of another CI loop.

**Comment by str4d** [comment]
Upgrading locally, I see the following changes:
```
    Updating futures-channel v0.3.18 -> v0.3.17
    Updating futures-core v0.3.18 -> v0.3.17
    Updating futures-task v0.3.18 -> v0.3.17
    Updating futures-util v0.3.18 -> v0.3.17
    Updating once_cell v1.8.0 -> v1.9.0
    Updating proc-macro2 v1.0.33 -> v1.0.34
    Updating tokio v1.14.0 -> v1.15.0
    Updating tokio-macros v1.6.0 -> v1.7.0
```
Notice the downgrade. `futures-core 0.3.18` was yanked yesterday: https://github.com/rust-lang/futures-rs/issues/2529#issuecomment-993823045

So we definitely want the changes!

**Comment by nuttycom** [comment]
Ah, I had noticed the downgrade in the diff and it confused me; I should have mentioned it, good catch!

**Review by ebfull — APPROVED** [review]

**Pull request merged**
