### PR TITLE
Remove FindAndDelete and disable OP_CODESEPARATOR

### LINKED ISSUE #1386: ZCA­002 - Inheriting FindAndDelete from Bitcoin is considered dangerous

### PR DESCRIPTION
**Pull request by str4d**
Closes #1386

### CODE REVIEW

**Comment by daira** [comment]
Ideally we would have tests to check that OP_CODESEPARATOR is a disabled operation, and that it *is* included in the input to a sighash. However, IMHO that doesn't need to block this PR; please file another ticket to add those tests. utACK.

**Comment by bitcartel** [comment]
test_bitcoin fails:
```
test/transaction_tests.cpp(158): error in "tx_valid": [[["0000000000000000000000000000000000000000000000000000000000000100",0,"DUP HASH160 0x14 0x5b6462475454710f3c22f5fdf0b40704c92f25c3 EQUALVERIFY CHECKSIGVERIFY 1 0x47 0x3044022067288ea50aa799543a536ff9306f8e1cba05b9c6b10951175b924f96732555ed022026d7b5265f38d21541519e4a1e55044d5b9e17e15cdbaf29ae3792e99e883e7a01"]],"01000000010001000000000000000000000000000000000000000000000000000000000000000000006a473044022067288ea50aa799543a536ff9306f8e1cba05b9c6b10951175b924f96732555ed022026d7b5265f38d21541519e4a1e55044d5b9e17e15cdbaf29ae3792e99e883e7a012103ba8c8b86dea131c22ab967e6dd99bdae8eff7a1f75a2c35f1f944109e3fe5e22ffffffff010000000000000000015100000000","P2SH"]
test/transaction_tests.cpp(159): error in "tx_valid": Script failed an OP_CHECKSIGVERIFY operation
```

**Comment by ebfull** [comment]
`OP_CODESEPARATOR` should be removed or renamed from the enum inside `script.h`.

**Comment by bitcartel** [comment]
Also in script_tests, uncomment the #ifdef to regenerate test data for transaction_tests.

**Comment by str4d** [comment]
@ebfull that doesn't match the existing semantics for disabled opcodes (e.g. OP_LSHIFT). IIRC we decided to disable instead of removing to avoid issues with anything that assumed that opcode was for `OP_CODESEPARATOR`. But if we *do* want to reclaim that opcode, then yes we could rename or remove.

**Comment by bitcartel** [comment]
@str4d Action items from earlier were: move test from invalid to valid, document why it is being moved and then ping Coinspect.

**Comment by str4d** [comment]
I've done the first two locally, pushing now

**Comment by bitcartel** [comment]
@str4d I have sent a message to @SergioDemianLerner regarding the test that failed.  Will wait for feedback before merging.

**Comment by str4d** [comment]
@ebfull does your thumb-up mean you're happy with leaving `OP_CODESEPARATOR` as disabled?

**Comment by str4d** [comment]
@ebfull
> @str4d yes w.r.t. the comment you left on github just now

**Comment by daira** [comment]
ACK a4f2555b3536eb854bda16763142dcf2a0cb067a

**Comment by SergioDemianLerner** [comment]
I'm reviewing now. I'll need 30 minutes.

**Comment by SergioDemianLerner** [comment]
No problem found.

**Comment by str4d** [comment]
Excellent! Thank you @SergioDemianLerner. I'm happy to merge this.
@zkbot r+

**Comment by str4d** [comment]
@zkbot r+ a4f2555

**Comment by str4d** [comment]
@zkbot r+ a4f2555b3536eb854bda16763142dcf2a0cb067a

**Comment by str4d** [comment]
@zkbot force

**Comment by str4d** [comment]
@zkbot r+ a4f2555b3536eb854bda16763142dcf2a0cb067a

**Comment by str4d** [comment]
@zkbot r-

**Comment by str4d** [comment]
@zkbot r+ a4f2555b3536eb854bda16763142dcf2a0cb067a

**Comment by ageis** [comment]
@zkbot r+

**Comment by ageis** [comment]
@zkbot r+

**Pull request merged**
