### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pejvan**
Added default options to build zcash with as many parallel compilation units as there are cpu cores. 
This makes compiling zcash multiple times faster.

### CODE REVIEW

**Comment by pejvan** [comment]
Added default options to build zcash with as many parallel compilation units as there are cpu cores.
This makes compiling zcash multiple times faster.

**Comment by bitcartel** [comment]
We document this slightly differently in the user guide.  @pejvan Could you update to use parentheses?  Thx.  https://github.com/zcash/zcash/wiki/1.0-User-Guide#upgrading

**Comment by mdr0id** [comment]
@pejvan Some of this info has gotten scattered about, but in the future please also reference:
 http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/user_guide.html

**Comment by pejvan** [comment]
@bitcartel  — done as per your request 👍

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
