### PR TITLE
Update libsnark

### LINKED ISSUE #491: Ensure proving/verifying keys change whenever circuit changes
We could hash the R1CS constraint system and place this in the proving/verifying keys on disk so that we cannot forget to change these keys.

### LINKED ISSUE #780: libsnark PRNG hook
Let's hook libsnark's PRNG and attach libsodium's to it. We don't need this for 1.0, probably, but we do as we expand platform support or want better (reproducable) testing.

### PR DESCRIPTION
**Pull request by ebfull**
We have now forked libsnark's current master and applied the following patches:

* [`9216072`: Remove code that we don't use.](https://github.com/zcash/libsnark/commit/9216072c3b20d65359f4d5f3982c8270dab422b6) (unblocks #69)
* [`dcb78b2`: Modify makefile to stop compiling things we removed.](https://github.com/zcash/libsnark/commit/dcb78b24d9de86522f7f976741111e9e66804889)
* [`a6b0ad0`: Use libsodium's PRNG](https://github.com/zcash/libsnark/commit/a6b0ad0c801fe96d0e12e5961279cdf306a412fa) (closes #780)
* [`4036716`: Don't (de)serialize the constraint system in the proving key.](https://github.com/zcash/libsnark/commit/403671675ada05caf7446f9676fa3c54d5830325) (closes #491)
* [`a703148`: Taylor's compilation patch](https://github.com/zcash/libsnark/commit/a7031481fd8d2360337321401fe8e24f0359317a) (@defuse can you submit this to upstream?)

This PR adopts those changes, and makes the requisite changes to Zcash to support them. I have decided to not bring libsnark in tree for the time being, though it should be incredibly easy to do later if we're *absolutely* sure we should.

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot try

**Comment by daira** [comment]
Reviewing.

**Comment by daira** [comment]
Reviewed this PR, now checking the [libsnark changes](https://github.com/scipr-lab/libsnark/compare/master...zcash:master).

**Comment by daira** [comment]
ACK.

**Comment by defuse** [comment]
Submitted that patch to upstream: https://github.com/scipr-lab/libsnark/pull/44

**Comment by defuse** [comment]
ACK, taking a look at the libsnark diff too.

**Comment by defuse** [comment]
Is it possible to remove more, e.g. "tinyram_ppzksnark_pp.cpp", "hashes/knapsack"?

**Comment by defuse** [comment]
Anyway, ACK!

**Comment by ebfull** [comment]
We can continue to chip away at it. I think once we see the code coverage results from this we can purge a lot more code out.

Thanks for reviewing!

@zkbot r+

**Pull request merged**
