### PR TITLE
Upgrade googletest to 1.8.0

### LINKED ISSUE #1432: Upgrade Google Test and Google Mock
Google Test 1.80 was recently released, which is the first release since the Google Mock repository was merged in. We should upgrade to use it.

Split off from #867.

### PR DESCRIPTION
**Pull request by str4d**
Since 1.8.0, the googletest and googlemock repositories have merged.

Closes #1432

### CODE REVIEW

**Comment by str4d** [comment]
Currently fails with a linker error.

This is not security-critical, so if no one has a quick fix then we can kick it forward.

**Comment by bitcartel** [comment]
Maybe this? https://github.com/google/googletest/issues/50

**Comment by bitcartel** [comment]
Not enough time to fix for rc1, moving to 1.0.0, could be moved to 1.0.1 too since low priority.

**Comment by str4d** [comment]
Rebased on master and tweaked to better follow the upstream build process. Still fails with linker errors:

```
libtool: link: /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/share/../native/bin/ccache g++ -m64 -std=c++11 -pipe -O1 -fwrapv -fno-strict-aliasing -Werror -g -Wformat -Wformat-security -Wstack-protector -fstack-protector-all -fPIE -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o zcash-gtest gtest/zcash_gtest-main.o gtest/zcash_gtest-utils.o gtest/zcash_gtest-test_checktransaction.o gtest/zcash_gtest-json_test_vectors.o gtest/zcash_gtest-test_foundersreward.o wallet/gtest/zcash_gtest-test_wallet_zkeys.o gtest/zcash_gtest-test_tautology.o gtest/zcash_gtest-test_equihash.o gtest/zcash_gtest-test_joinsplit.o gtest/zcash_gtest-test_keystore.o gtest/zcash_gtest-test_noteencryption.o gtest/zcash_gtest-test_merkletree.o gtest/zcash_gtest-test_metrics.o gtest/zcash_gtest-test_miner.o gtest/zcash_gtest-test_pow.o gtest/zcash_gtest-test_random.o gtest/zcash_gtest-test_rpc.o gtest/zcash_gtest-test_transaction.o gtest/zcash_gtest-test_circuit.o gtest/zcash_gtest-test_txid.o gtest/zcash_gtest-test_libzcash_utils.o gtest/zcash_gtest-test_proofs.o gtest/zcash_gtest-test_checkblock.o wallet/gtest/zcash_gtest-test_wallet.o -fopenmp  -L/home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/share/../lib -lgmock libbitcoin_server.a libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a crypto/libbitcoin_crypto.a univalue/.libs/libunivalue.a ./leveldb/libleveldb.a ./leveldb/libmemenv.a -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt -lboost_unit_test_framework-mt secp256k1/.libs/libsecp256k1.a libbitcoin_zmq.a -L/home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/lib /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/lib/libzmq.a -lrt -lpthread -lstdc++ libbitcoin_wallet.a ./.libs/libzcashconsensus.a -ldb_cxx-6.2 -lssl -ldl -lminiupnpc libzcash.a -lsnark /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmpxx.a /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/lib/libgmp.a -lboost_system-mt -lcrypto /home/str4d/dev/zcash/zcash/depends/x86_64-unknown-linux-gnu/lib/libsodium.a -lanl -fopenmp -pthread
gtest/zcash_gtest-test_foundersreward.o: In function `__static_initialization_and_destruction_0':
/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:89: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:113: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:121: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:129: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:138: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
gtest/zcash_gtest-test_foundersreward.o:/home/str4d/dev/zcash/zcash/src/gtest/test_foundersreward.cpp:171: more undefined references to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)' follow
collect2: error: ld returned 1 exit status
Makefile:3160: recipe for target 'zcash-gtest' failed
make[2]: *** [zcash-gtest] Error 1
```

**Comment by daira** [comment]
The linker command that fails has ``-lgmock`` but not ``-lgtest``. (It should be near the end.)

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
I'm hitting https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844896 when building locally.

**Comment by daira** [comment]
Maybe related to this commit: https://github.com/google/googletest/commit/0928adbfea9b7645e884bd95fee23cfd669729cd

**Comment by daira** [comment]
Oh!
```
In file included from /usr/src/gtest/src/gtest-all.cc:42:0:
```
It's picking up my system gtest, not the one built by the depends system :-(

**Comment by daira** [comment]
``sudo apt-get install --upgrade googletest`` worked around my problem, although obviously this is not fixing the underlying problem. (The version installed by ``apt-get`` was libgtest-dev_1.8.0-6_amd64.)

**Comment by daira** [comment]
I think I see what's going on. In the libsnark testing build step, libgtest is either not being built or not being found by the linker. On my VM, gtest is installed globally so that version is picked up by the link (causing the ``gtest_flag_saver_`` problem until I upgraded). On the CI workers that fail, gtest is not installed globally so the link fails.

**Comment by daira** [comment]
Superceded by #2751.

**Pull request closed without merging**
