### PR TITLE
Migrate to LLVM 18

### PR DESCRIPTION
**Pull request by str4d**
Includes changes backported from the following upstream PRs:
- bitcoin/bitcoin#9791
- bitcoin/bitcoin#11286

### CODE REVIEW

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/zcash/compare/b25fb09094f96a35bdc76e153aa67816f54d2878..11e0b03ff9d00e8303f7920c5d2cbf58095b8ab9) to fix Clang major version settings for not-upgraded targets (Intel macOS).

**Comment by str4d** [comment]
[Force-pushed several times](https://github.com/zcash/zcash/compare/11e0b03ff9d00e8303f7920c5d2cbf58095b8ab9..1730d6c8009f6ecf3faccc18a9a6c76bcd88ae16) to fix various issues.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/zcash/compare/1730d6c8009f6ecf3faccc18a9a6c76bcd88ae16..3a6bd8ac38fab33cacf55d3f4b784ffa35686690) to backport another patch to avoid a new Clang error while compiling `libevent`.

**Review by daira — APPROVED** [review]
utACK

**Pull request merged**
