### PR TITLE
[WIP] Update rust crates

### PR DESCRIPTION
**Pull request by defuse**
I just updated the .mk files, it almost certainly won't build. Eventually need to rebase out the commits from #3870.

### CODE REVIEW

**Comment by defuse** [comment]
Oh, it looks like the versions are fixed in [librustzcash's Cargo.lock](https://github.com/zcash/librustzcash/blob/master/Cargo.lock), so they would need to be updated there and here at the same time.

**Comment by str4d** [comment]
This is a good example of why I want to move the librustzcash crate itself into this repo (zcash/librustzcash#155). The Rust convention is that a Cargo.lock is committed anywhere that results in an end binary, i.e. application crates; library crates instead rely on their SemVer-specified dependencies. We currently pin for an FFI crate, which does make sense to me as we are building static libs, but that is a decision driven entirely by zcashd, and should really be coupled together.

**Comment by str4d** [comment]
See #4321.

**Comment by therealyingtong** [comment]
Closing as obsolete (with @daira )

**Pull request closed without merging**
