### PR TITLE
depends: Support additional cross-compilation targets in Rust

### PR DESCRIPTION
**Pull request by str4d**
This will make it easier for third parties to cross-compile `zcashd` for other platforms. The third commit in this PR shows how to add a new target to the Rust dependency builder.

The default Rust target during cross-compilation is the canonical host, which is derived from `HOST` using `depends/config.sub`. If the canonical host differs from the required Rust target, add the necessary mapping in addition to the target itself.

Also includes fixes for cross-compiling aarch64 targets.

### CODE REVIEW

**Comment by str4d** [comment]
Rebased on master to fix merge conflict.

**Comment by str4d** [comment]
Rebased on master to fix merge conflicts.

**Comment by str4d** [comment]
Pushed fixes for cross-compiling aarch64. Cross-compilation runs to completion for me now.

**Comment by str4d** [comment]
Let's check that this hasn't broken anything...

@zkbot try

**Comment by mdr0id** [comment]
I was able to compile this, but was not able to test further due to SBC limitations ATM.

**Comment by ianamunoz** [comment]
So I ran this build like so:
```
$docker run -it --rm -v /tmp:/tmp debian:latest
root@e31e6312207f:~/zcash# apt-get update
root@e31e6312207f:~/zcash# apt-get upgrade
root@e31e6312207f:~/zcash# apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget curl bsdmainutils automake
root@e31e6312207f:~/zcash# apt-get install g++-aarch64-linux-gnu
root@e31e6312207f:~/zcash# git clone https://github.com/str4d/zcash.git
root@e31e6312207f:~/zcash# cd zcash/
root@e31e6312207f:~/zcash# git checkout -b str4d-rust-targets master
root@e31e6312207f:~/zcash# git pull https://github.com/str4d/zcash.git rust-targets
root@e31e6312207f:~/zcash# HOST=aarch64-linux-gnu ./zcutil/build.sh -j$(nproc)
root@e31e6312207f:~/zcash# mkdir /tmp/aarch64-zcash/
root@e31e6312207f:~/zcash# cp ./src/zcash-cli ./src/zcashd ./src/zcash-tx ./src/zcash-gtest ./zcutil/fetch-params.sh /tmp/aarch64-zcash/
```
Copied the binaries up to a Scaleway x6 core ARM. Fetched the params. 
Currently syncing and appears to run normally on:
```
# uname -a
Linux builder 4.9.93-mainline-rev1 #1 SMP Tue Apr 10 09:54:46 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
Will run smoke tests to see if I can flush out any bugs.

**Comment by mdr0id** [comment]
utACK, per comment above but otherwise appears GTM

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
