### PR TITLE
Closes #2639. z_shieldcoinbase is now supported, no longer experimental.

### LINKED ISSUE #2639: Move z_shieldcoinbase from experimental feature to fully supported rpc call

### PR DESCRIPTION
**Pull request by bitcartel**
This reverts commit 5023af7bd5fc8c147e6fd111b610bd8922e91131.

### CODE REVIEW

**Comment by bitcartel** [comment]
@arcalinea has run tests successfully on the testnet faucet server.

Previous testnet testing is here: https://github.com/zcash/zcash/pull/2615#issuecomment-331015221

Mainnet tests also conducted.

**Comment by str4d** [comment]
@zkbot try

**Comment by bitcartel** [comment]
Error due to unrelated test.

```
=== Running testscript mempool_tx_input_limit.py ===
  File "/home/zcbbworker/latent-0/debian8/build/qa/rpc-tests/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/home/zcbbworker/latent-0/debian8/build/qa/rpc-tests/mempool_tx_input_limit.py", line 139, in run_test
    assert_equal("Too many transparent inputs 3 > limit 2", msg)
  File "/home/zcbbworker/latent-0/debian8/build/qa/rpc-tests/test_framework/util.py", line 356, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
Initializing test directory /tmp/testKNRBya
waiting for async operation opid-c2669365-7aaf-4271-b623-fb0ea9b5efd1
...returned status: success
waiting for async operation opid-a567ed3a-40b1-4524-aba3-1fe75f5f83fd
...returned status: success
Assertion failed: Too many transparent inputs 3 > limit 2 != Account has insufficient funds
Stopping nodes
Cleaning up
Failed
!!! FAIL: mempool_tx_input_limit.py !!!
```

However test, on this branch, passes locally.

**Comment by bitcartel** [comment]
Let's try again... @zkbot try

**Comment by bitcartel** [comment]
@str4d Test not related to z_shieldcoinbase is failing on debian8 but works on debian8-kitchensink.

**Comment by str4d** [comment]
That's a transient failure - sometimes `mempool_tx_input_limit.py` generates transactions that fail its assertions, I suspect due to randomness in `sendfrom`. We can just `r+` this once it has a second ACK.

**Comment by bitcartel** [comment]
I have pushed a commit to add a limit parameter as discussed in #2639.

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@str4d @daira PR updated.

**Comment by bitcartel** [comment]
Just tweaked the qa test to check for limit parameter set to something absurdly high.

```+        # Shielding will fail because limit parameter is absurdly large
+        try:
+            self.nodes[0].z_shieldcoinbase("*", myzaddr, Decimal('0.001'), 99999999999999)
+        except JSONRPCException,e:
+            errorString = e.error['message']
+        assert_equal("JSON integer out of range" in errorString, True)
+
```

```-        result = self.nodes[0].z_shieldcoinbase(mytaddr, myzaddr, 0, 0)
+        # We set an unrealistically high limit parameter of 99999, to verify that max tx size will constrain the number of utxos.
+        result = self.nodes[0].z_shieldcoinbase(mytaddr, myzaddr, 0, 99999)
```

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
