### PR TITLE
 Use depth-first scan for eliminating partial solutions instead of breadth-first

### LINKED ISSUE #857: Optimize Equihash implementation
There are several ways our initial release of Equihash are suboptimal for memory usage and time. Let's do a subsequent release to improve those so that we can set the parameters (#856) appropriately.

We don't have to do every possible optimization, but enough that it's feasible to run a miner with the right parameters.

### PR DESCRIPTION
**Pull request by str4d**
This reduces the peak number of lists in-memory from 2^k to k, and enables the
solver to eliminate most duplicates before it has instantiated the full set of
leaves.

Part of #857.

### CODE REVIEW

**Comment by str4d** [comment]
With `n = 144, k = 5` (memory usage around 740 MiB), here is the solving time on my machine (Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz on Xubuntu inside Virtualbox on Windows 7) before this PR (592b2f0):

```json
$ ./qa/zcash/performance-measurements.sh time solveequihash
[
    {
        "runningtime" : 221.86767900
    },
    {
        "runningtime" : 121.05709200
    },
    {
        "runningtime" : 364.05223800
    },
    {
        "runningtime" : 332.93036900
    },
    {
        "runningtime" : 348.53837200
    },
    {
        "runningtime" : 135.76709800
    },
    {
        "runningtime" : 246.63396400
    },
    {
        "runningtime" : 506.23024300
    },
    {
        "runningtime" : 186.89934000
    },
    {
        "runningtime" : 312.82442000
    }
]
```

And with depth-first scanning (0a66f01), run twice for good measure:

```json
$ ./qa/zcash/performance-measurements.sh time solveequihash
[
    {
        "runningtime" : 95.07250100
    },
    {
        "runningtime" : 148.82645200
    },
    {
        "runningtime" : 149.05558900
    },
    {
        "runningtime" : 84.78875000
    },
    {
        "runningtime" : 208.65920100
    },
    {
        "runningtime" : 162.60182800
    },
    {
        "runningtime" : 81.13651300
    },
    {
        "runningtime" : 118.13927500
    },
    {
        "runningtime" : 138.75577200
    },
    {
        "runningtime" : 110.40828300
    }
]
$ ./qa/zcash/performance-measurements.sh time solveequihash
[
    {
        "runningtime" : 168.90254700
    },
    {
        "runningtime" : 111.89588000
    },
    {
        "runningtime" : 88.69492300
    },
    {
        "runningtime" : 92.13983900
    },
    {
        "runningtime" : 333.55639200
    },
    {
        "runningtime" : 118.73794400
    },
    {
        "runningtime" : 172.18170400
    },
    {
        "runningtime" : 359.33046600
    },
    {
        "runningtime" : 115.49226200
    },
    {
        "runningtime" : 138.79895400
    }
]
```

Via ad-hoc timing, it appears that the time to find the partial solutions is pretty consistently around 80s (on my machine). The variation in final solving time is caused by the variations in number of partial solutions found. The depth-first scan doesn't remove all variability, but does enable most partials to be eliminated sooner.

**Comment by str4d** [comment]
Other possible speed optimisations:

- [ ] XOR on-the-fly
  - Reduces variability in solving time at the expense of requiring additional time during the main step, so may not be worthwhile past the first round.
- [ ] Don't truncate indices for some rounds, but still store full hash
  - May not be possible, as this only works if the full row lengths in those rounds are below the peak truncated row length for the chosen parameters.
- [ ] Multithreaded solver
  - [ ] Multithreaded sorting
  - [ ] Eliminate partial solutions in parallel
  - Having the solver use more threads will reduce the number of mining threads that can be run (`genproclimit`).

**Comment by str4d** [comment]
@zkbot try

**Comment by daira** [comment]
How does the solution time scale with n and k?

**Comment by str4d** [comment]
Solution time increases as peak memory usage increases, which is a combination of increasing n and k, and increasing (n/(k+1))+1. Solution time variation increases as index truncation increases and peak memory usage decreases.

**Comment by str4d** [comment]
Here are the corresponding speed measurements from the metrics server (for the current testnet parameters `n = 96, k = 5`):

592b2f0:


```json
[
    {
        "runningtime" : 1.78607700
    },
    {
        "runningtime" : 0.45920400
    },
    {
        "runningtime" : 0.78211100
    },
    {
        "runningtime" : 0.49103600
    },
    {
        "runningtime" : 0.51412300
    },
    {
        "runningtime" : 0.99892500
    },
    {
        "runningtime" : 0.49797400
    },
    {
        "runningtime" : 2.17664800
    },
    {
        "runningtime" : 1.19773800
    },
    {
        "runningtime" : 0.79342700
    }
]
```

0a66f01:

```json
[
    {
        "runningtime" : 0.85764600
    },
    {
        "runningtime" : 0.83390300
    },
    {
        "runningtime" : 0.32357900
    },
    {
        "runningtime" : 0.46429600
    },
    {
        "runningtime" : 0.28994400
    },
    {
        "runningtime" : 1.10518900
    },
    {
        "runningtime" : 0.50795300
    },
    {
        "runningtime" : 0.59142900
    },
    {
        "runningtime" : 0.28419900
    },
    {
        "runningtime" : 0.27175600
    }
]
```

**Comment by ebfull** [comment]
I feel like multithreaded sorting is the ticket.

**Comment by daira** [comment]
We want it to be possible to do mining in the background, right? If we use all cores then that's not going to work. (I know the memory bandwidth use will affect performance of other cores, but hopefully not too painfully.)

**Comment by str4d** [comment]
Any additional threads used would be configurable, probably via e.g. an `equihashproclimit` parameter. The user docs would indicate that the product of `genproclimit` and `equihashproclimit` should not exceed the total number of cores.

**Comment by daira** [comment]
Okay, but I don't think we should rely on multithreading to solve the time-to-single-Equihash-solution problem.

**Comment by zookozcash** [comment]
Re https://github.com/zcash/zcash/pull/988#issuecomment-223889565, no, we do _not_ include running the miner in the background on a general purpose computer that is also doing other tasks as one of our desiderata.

**Comment by daira** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode_using.html

I think we should use ``__gnu_parallel::sort`` rather than defining ``_GLIBCXX_PARALLEL``; there's no point in using parallel implementations of other standard library functions that we don't use in a performance-critical context, and that might increase risk of bugs and race conditions.

``omp_set_num_threads`` can be used around the call to ``__gnu_parallel::sort`` to control the *maximum* number of threads used.

**Comment by str4d** [comment]
This PR is now just about getting this particular optimisation in. Multithreading discussion should continue in #857.

**Comment by ebfull** [comment]
This needs review!

**Comment by ebfull** [comment]
ACK!

**Comment by defuse** [comment]
ACK!

**Comment by ebfull** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r-

**Comment by ebfull** [comment]
@zkbot r+ 0a66f013040f1268faa6fcc354b8f17310dcebc5

**Pull request merged**
