### PR TITLE
Add -Wformat -Wformat-security

### LINKED ISSUE #915: Re-enable --enable-hardening security features
When we added the `-O0` flag to disable optimization, that disabled `FORTIFY_SOURCE` security features. You can see the warnings saying it requires optimization to be enabled in the build output. We have to re-enable optimization (and make sure `--enable-hardening` is on) before we release 1.0.

### PR DESCRIPTION
**Pull request by defuse**
Closes #915. Supersedes #1267 (because of weird rebase/github/zkbot bug).

### CODE REVIEW

**Comment by daira** [comment]
ACK; cannot affect coverage. @zkbot r+

**Comment by defuse** [comment]
:confused:

**Comment by daira** [comment]
```
checking whether C++ compiler accepts -Wformat... yes
checking whether C++ compiler accepts -Wformat-security... no
configure: error: Cannot enable -Wformat-security
```

Maybe GCC on the buildslave needs updating?

**Comment by daira** [comment]
BTW I also like this option:
```
-Wformat-nonliteral
If -Wformat is specified, also warn if the format string is not a string literal and so cannot be checked, 
unless the format function takes its format arguments as a va_list.
```

**Comment by daira** [comment]
Or perhaps the problem is with the macro specifying ``-Wformat-security`` without ``-Wformat``?

**Comment by ebfull** [comment]
I'm going to run coverage tests locally on this to make sure nothing broke and then r+ it again.

**Comment by ebfull** [comment]
Coverage builds fine.

@zkbot r+

**Pull request merged**
