### PR TITLE
Observatory logging, including alternative blocks and peer timestamps 

### PR DESCRIPTION
**Pull request by pranavt61**
**Context**

We are adding “observatory” features, which collect and archive key ephemeral off-chain data that are currently not retained. The scope of this initial pull request is local retention of metadata for all blocks (including stale/orphaned alternative blocks). This allows us to:

- Analyze fork frequency for evidence of stubborn mining
- Record forensic evidence of selfish/stubborn mining & double spend attacks
- An upcoming PR will parse these blocks/txns to detect possible double spends mining by comparing the transaction inputs (transparent pool) or nullifiers (shielded pool)

Other features under development in the next month include: message receipt timestamps for each peer, double spend detection, and alerting

This work is supported by the Zcash Foundation
(https://grants.zfnd.org/proposals/21786689-zcash-observatory)

**Notes**
Activate observatory features by using the flag “--printtocsv”

**Feedback requested:**
What format would be most accessible?
What tests should be written for this code?
Default path to observatory log files?
Any changes in style or design?

Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed and reviewed by the documentation team (@ioptio, @mdr0id, or @Eirik0) before the PR can be merged
* [ ] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all buildbot tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

### CODE REVIEW

**Comment by Mitchellpkt** [comment]
We'll update for v3.0.0 and re-submit, thanks for the tip @zkbot

**Comment by pranavt61** [comment]
Submitted the updated PR: https://github.com/zcash/zcash/pull/4540

**Comment by str4d** [comment]
I don't think this PR is intended to be merged (as it is tied to the current main branch of the downstream repo). In any case, most of what is in this PR is not something I think we want to commit to maintaining inside `zcashd` (vs it being part of a separate binary that consumes data from `zcashd`, or maintained as an external patch on `zcashd`).

#4540 appears to be a subset of this PR, so let's look at the changes there and decide what parts of it are suitable to be merged in `zcashd`; then we can revisit the remaining delta for a similar analysis.

**Comment by Mitchellpkt** [comment]
Sounds good, thanks @str4d. Your are correct, this PR was superseded by #4540

**Pull request closed without merging**
