### PR TITLE
Add getlocalsolps and getnetworksolps RPC calls, show them in getmininginfo

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by daira** [comment]
Not necessary / too much code for before launch, I think.

**Comment by str4d** [comment]
I disagree on the code aspect. There is very little actual code in this PR; most of the lines are documentation. Whether it is necessary is debatable (this PR was prompted by user requests).

**Comment by daira** [comment]
I think it's too much code. NACK, sorry.

**Comment by str4d** [comment]
Fair point on tests, and I can't justify the time to write them today.

**Comment by str4d** [comment]
Rebased on master to fix merge conflicts.

**Comment by str4d** [comment]
Rebased on master and added a test.

**Comment by str4d** [comment]
Proposing for merge into 1.0.4 pending review.

**Comment by ebfull** [comment]
ACK+cov

**Pull request merged**
