### PR TITLE
Backport fix for orphan handling

### PR DESCRIPTION
**Pull request by daira**
Disclosed in https://bitcoincore.org/en/2024/07/03/disclose-orphan-dos/

Includes commits cherry-picked from the following upstream PRs:
- bitcoin/bitcoin#8179
- bitcoin/bitcoin#15644
  - This was the covert fix.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK 4e7ec7f

**Review by nuttycom — APPROVED** [review]
utACK f6de253f7df47beec2ec8f0f254570c0d8781906

**Review by nuttycom — DISMISSED** [review]
utACK 34c6e76cc1a61b6b131080ba171fdbb6c0211b28

**Comment by daira** [comment]
Note that this passed required tests.

**Review by nuttycom — APPROVED** [review]
utACK https://github.com/zcash/zcash/pull/6928/commits/c890bb505aba82ab5df6c5322e4f581fc1fa0dcb with the caveat that we should figure out why this test has gone from regularly passing to regularly failing.

**Pull request merged**
