### PR TITLE
Add build scripts and fetch-params.sh to "make install" and "make dist"

### LINKED ISSUE #1728: fetch-params.sh missing from gitian builds
This was mentioned during launch; I don't remember any details.

### PR DESCRIPTION
**Pull request by str4d**
Closes #1728

### CODE REVIEW

**Comment by str4d** [comment]
I'm running a Gitian build on this branch to check that it resolves #1728.

**Comment by str4d** [comment]
Rebased to add a missing `\`.

**Comment by str4d** [comment]
Rebased to fix Makefile (and simplify) by always installing `fetch-params.sh` regardless of build flags.

**Comment by str4d** [comment]
I've run a Gitian build on 33efd816ec068e7164813c24781dab9143ef32d0 and confirmed that `zcutil/fetch-params.sh` appears in `zcash-1.0.0.tar.gz`, and that `bin/zcash-fetch-params` appears in `zcash-1.0.0-linux64.tar.gz`. `bin/zcash-fetch-params` does not currently appear in `zcash-1.0.0-linux64-debug.tar.gz`, but that is fine, because the debug binary tarball is intended for use in tandem with the regular binary tarball.

**Comment by ageis** [comment]
Partial ACK. Thanks for taking care of this! @str4d, another refinement that we should make is to make it so that `build-debian-package.sh` works with the paths of the binaries extracted from the Gitian release tarball. Presently, I have to extract the Gitian release tarball and move binaries into `/src` (as if I was building Zcash in a regular source tree) for the Debian package script to work.

**Comment by ebfull** [comment]
utACK

**Comment by str4d** [comment]
@ageis
> another refinement that we should make is to make it so that build-debian-package.sh works with the paths of the binaries extracted from the Gitian release tarball. Presently, I have to extract the Gitian release tarball and move binaries into /src (as if I was building Zcash in a regular source tree) for the Debian package script to work.

ACK, but I wouldn't block this PR on that. We don't currently include the Debian build script in the binary package, and this PR only adds it into the source tarball.

**Comment by ageis** [comment]
Ok, then utACK.

**Comment by str4d** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot retry

**Comment by str4d** [comment]
@zkbot retry

**Pull request merged**
