### PR TITLE
Fix SIGHASH_SINGLE bug by removing in-band signalling.

### LINKED ISSUE #1078: Fix the SIGHASH_SINGLE bug
If you try to do `SIGHASH_SINGLE` in an input for which there is no corresponding (same-index) output, then `SignatureHash` returns `1`. It is a known bug that at least some places (e.g. `CheckSig`) don't check for this error code, and so the bug is baked into Bitcoin's consensus rules. *Our new code* (JoinSplits) is checking for the error code when we call SignatureHash, which is inconsistent with those parts of Bitcoin. Fortunately, there are no bugs introduced by that since we always use `SIGHASH_ALL` for JoinSplits (so restricting the signature type was a good call!).

Should we fix the bug? There are only 2 calls (excluding ones in tests) that would need to have an error check added, but by fixing it we risk breaking Bitcoin tools which expect the bug to be present.

Here's the relevant code from `SignatureHash`:

```
uint256 SignatureHash(const CScript& scriptCode, const CTransaction& txTo, unsigned int nIn, int nHashType)
{
    static const uint256 one(uint256S("0000000000000000000000000000000000000000000000000000000000000001"));
    if (nIn >= txTo.vin.size() && nIn != NOT_AN_INPUT) {
        //  nIn out of range
        return one;
    }

    // Check for invalid use of SIGHASH_SINGLE
    if ((nHashType & 0x1f) == SIGHASH_SINGLE) {
        if (nIn >= txTo.vout.size()) {
            //  nOut out of range
            return one;
        }
    }
...
```

### PR DESCRIPTION
**Pull request by defuse**
Competes with #1079. Closes #1078.

**I FORCE PUSHED**

### CODE REVIEW

**Comment by defuse** [comment]
This breaks tests

**Comment by defuse** [comment]
Broken tests:

```
Running 181 test cases...
test/transaction_tests.cpp(158): error in "tx_valid": [[["0000000000000000000000000000000000000000000000000000000000000100",0,"DUP HASH160 0x14 0xe52b482f2faa8ecbf0db344f93c84ac908557f33 EQUALVERIFY CHECKSIG"],["0000000000000000000000000000000000000000000000000000000000000200",0,"1"]],"01000000020002000000000000000000000000000000000000000000000000000000000000000000000151ffffffff0001000000000000000000000000000000000000000000000000000000000000000000006b483045022100c9cdd08798a28af9d1baf44a6c77bcc7e279f47dc487c8c899911bc48feaffcc0220503c5c50ae3998a733263c5c0f7061b483e2b56c4c41b456e7d2f5a78a74c077032102d5c25adb51b61339d2b05315791e21bbe80ea470a49db0135720983c905aace0ffffffff010000000000000000015100000000","P2SH"]
test/transaction_tests.cpp(159): error in "tx_valid": Script evaluated without error but finished with a false/empty top stack element
test/transaction_tests.cpp(158): error in "tx_valid": [[["b5b598de91787439afd5938116654e0b16b7a0d0f82742ba37564219c5afcbf9",0,"DUP HASH160 0x14 0xf6f365c40f0739b61de827a44751e5e99032ed8f EQUALVERIFY CHECKSIG"],["ab9805c6d57d7070d9a42c5176e47bb705023e6b67249fb6760880548298e742",0,"HASH160 0x14 0xd8dacdadb7462ae15cd906f1878706d0da8660e6 EQUAL"]],"0100000002f9cbafc519425637ba4227f8d0a0b7160b4e65168193d5af39747891de98b5b5000000006b4830450221008dd619c563e527c47d9bd53534a770b102e40faa87f61433580e04e271ef2f960220029886434e18122b53d5decd25f1f4acb2480659fea20aabd856987ba3c3907e0121022b78b756e2258af13779c1a1f37ea6800259716ca4b7f0b87610e0bf3ab52a01ffffffff42e7988254800876b69f24676b3e0205b77be476512ca4d970707dd5c60598ab00000000fd260100483045022015bd0139bcccf990a6af6ec5c1c52ed8222e03a0d51c334df139968525d2fcd20221009f9efe325476eb64c3958e4713e9eefe49bf1d820ed58d2112721b134e2a1a53034930460221008431bdfa72bc67f9d41fe72e94c88fb8f359ffa30b33c72c121c5a877d922e1002210089ef5fc22dd8bfc6bf9ffdb01a9862d27687d424d1fefbab9e9c7176844a187a014c9052483045022015bd0139bcccf990a6af6ec5c1c52ed8222e03a0d51c334df139968525d2fcd20221009f9efe325476eb64c3958e4713e9eefe49bf1d820ed58d2112721b134e2a1a5303210378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71210378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c7153aeffffffff01a08601000000000017a914d8dacdadb7462ae15cd906f1878706d0da8660e68700000000","P2SH"]
test/transaction_tests.cpp(159): error in "tx_valid": Script evaluated without error but finished with a false/empty top stack element
test/transaction_tests.cpp(158): error in "tx_valid": [[["ceafe58e0f6e7d67c0409fbbf673c84c166e3c5d3c24af58f7175b18df3bb3db",0,"DUP HASH160 0x14 0xf6f365c40f0739b61de827a44751e5e99032ed8f EQUALVERIFY CHECKSIG"],["ceafe58e0f6e7d67c0409fbbf673c84c166e3c5d3c24af58f7175b18df3bb3db",1,"2 0x48 0x3045022015bd0139bcccf990a6af6ec5c1c52ed8222e03a0d51c334df139968525d2fcd20221009f9efe325476eb64c3958e4713e9eefe49bf1d820ed58d2112721b134e2a1a5303 0x21 0x0378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71 0x21 0x0378d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71 3 CHECKMULTISIG"]],"0100000002dbb33bdf185b17f758af243c5d3c6e164cc873f6bb9f40c0677d6e0f8ee5afce000000006b4830450221009627444320dc5ef8d7f68f35010b4c050a6ed0d96b67a84db99fda9c9de58b1e02203e4b4aaa019e012e65d69b487fdf8719df72f488fa91506a80c49a33929f1fd50121022b78b756e2258af13779c1a1f37ea6800259716ca4b7f0b87610e0bf3ab52a01ffffffffdbb33bdf185b17f758af243c5d3c6e164cc873f6bb9f40c0677d6e0f8ee5afce010000009300483045022015bd0139bcccf990a6af6ec5c1c52ed8222e03a0d51c334df139968525d2fcd20221009f9efe325476eb64c3958e4713e9eefe49bf1d820ed58d2112721b134e2a1a5303483045022015bd0139bcccf990a6af6ec5c1c52ed8222e03a0d51c334df139968525d2fcd20221009f9efe325476eb64c3958e4713e9eefe49bf1d820ed58d2112721b134e2a1a5303ffffffff01a0860100000000001976a9149bc0bbdd3024da4d0c38ed1aecf5c68dd1d3fa1288ac00000000","P2SH"]
test/transaction_tests.cpp(159): error in "tx_valid": Script evaluated without error but finished with a false/empty top stack element
```

**Comment by defuse** [comment]
I wonder if those are transactions that trigger the old failure case, and they can just be deleted?

**Comment by defuse** [comment]
There are three transactions in `tx_valid.json` that make use of the bug. The first one just tests the bug, so it's easy to move it to `tx_invalid.json`. However, for the other two, *upstream actually uses the bug to test something else*, so we're reducing test coverage if I just move them to `tx_invalid.json`.

**Comment by defuse** [comment]
The latest commit fixes the tests by moving all three broken ones into `tx_invalid.json`. I honestly don't understand what the comment in the later two tests is saying, so I don't have a clue how to write an equivalent test for it that doesn't use the SIGHASH_SINGLE bug.

**Comment by daira** [comment]
"upstream actually uses the bug to test something else"

Sigh. 🙄

**Comment by ebfull** [comment]
We're probably not going to land this for the release next week.

**Comment by daira** [comment]
ACK.

**Comment by defuse** [comment]
@zkbot r+

**Comment by ebfull** [comment]
@zkbot r-

I would like to review this first anyhow! I'm concerned that throwing exceptions from SignatureHash will not be expected by some of its callers, especially during things like block verification. I want to double-check that it's okay.

**Comment by defuse** [comment]
force pushed

**Comment by defuse** [comment]
@ebfull yes please review!

**Comment by ebfull** [comment]
ACK

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
