### PR TITLE
Igor Stenski's -m64 patch (see zcash-dev).

### PR DESCRIPTION
**Pull request by defuse**
See the thread on zcash-dev titled `[zcash-dev] [PATCH] libsnark.a and gtest.a to be elf64-x86-64, not elf-i386`

### CODE REVIEW

**Comment by ebfull** [comment]
ACK

**Comment by defuse** [comment]
ACK, but I realize that eventually changes like this will need to be reverted one day when we want to support multiple architectures.

**Comment by daira** [comment]
ACK (once rebased).

**Comment by daira** [comment]
Here's a link to the zcash-dev part explaining the problem: https://lists.zca.sh/pipermail/zcash-dev/2016-June/000089.html

**Comment by ebfull** [comment]
ACK once rebased (anyone can r+ this)

**Comment by defuse** [comment]
force pushed

**Comment by ebfull** [comment]
@zkbot r+

**Comment by daira** [comment]
Changing my ACK to a NACK, because I don't understand why ``-m64`` is needed in these two places and not in other places, for example ``Makefile`` line 314.

**Comment by daira** [comment]
Oops, already r+'d. I guess this is fine.

**Comment by ebfull** [comment]
It isn't being tested yet.

@zkbot r-

**Comment by 0x64616E69656C** [comment]
personal opinion: don't do this. -m64 is ABI selection and not really relevant.

**Comment by daira** [comment]
Still NACK: I don't understand the issue raised in https://github.com/zcash/zcash/pull/1052#issuecomment-233791990 , and I suspect this only happens if the compiler toolchain is broken.

**Comment by ebfull** [comment]
Closing because disagreement and this is polluting our PRs. It's also not really clear we need it.

**Pull request closed without merging**
