### PR TITLE
[macOS] curl fail on HTTP errors without downloading any data

### PR DESCRIPTION
**Pull request by kozyilmaz**
tested on macOS Sierra 10.12.5 (issue #2431)

```
mkdir -p /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources
rm -f /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
touch /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps/.stamp_fetched-rust-rust-1.16.0-x86_64-apple-darwin.tar.gz.hash
cd /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/download-stamps; (test -f /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz || ( mkdir -p /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0 && echo Fetching rust... && ( curl --connect-timeout 10 --fail --retry 3 -L -o "/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://z.cash/depends-sources/rust-1.16.0-x86_64-apple-darwin.tar.gz" || curl --connect-timeout 10 --fail --retry 3 -L -o "/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" "https://static.rust-lang.org/dist/rust-1.16.0-x86_64-apple-darwin.tar.gz" ) && echo "2d08259ee038d3a2c77a93f1a31fc59e7a1d6d1bbfcba3dba3c8213b2e5d1926  /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp" > /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && shasum -a 256 -c /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/.rust-1.16.0-x86_64-apple-darwin.tar.gz.hash && mv /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/sources/rust-1.16.0-x86_64-apple-darwin.tar.gz && rm -rf /Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0 ))
Fetching rust...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 85.7M  100 85.7M    0     0  1444k      0  0:01:00  0:01:00 --:--:-- 2248k
/Users/loki/Desktop/devel/zcash-apple/zcash/zcash_v1.0.9/depends/work/download/rust-1.16.0/rust-1.16.0-x86_64-apple-darwin.tar.gz.temp: OK
```

### CODE REVIEW

**Comment by ebfull** [comment]
utACK

**Comment by bitcartel** [comment]
utACK - note that it might not cover all possible http errors, from curl man page
```
              This  method is not fail-safe and there are occasions where non-
              successful response codes will  slip  through,  especially  when
              authentication is involved (response codes 401 and 407).
```

**Comment by str4d** [comment]
Bumping until we get a macOS worker hooked up to CI.

**Comment by kozyilmaz** [comment]
https://github.com/zcash/zcash/pull/2697 contains this fix, closing

**Pull request closed without merging**
