### PR TITLE
Pre-Release 2.0.2 

### PR DESCRIPTION
**Pull request by mdr0id**
Update nnMinimumChainWork per 2.0.2 getblockchaininfo

### CODE REVIEW

**Comment by bitcartel** [comment]
This needs ACK rather than utACK to ensure a node can actually sync.

**Comment by mdr0id** [comment]
Built this branch on another node that was not synced to the `437371` block and it was able to sync past this height.

**Comment by mdr0id** [comment]
@zkbot retry

**Comment by mdr0id** [comment]
@zkbot retry

**Pull request merged**
