### PR TITLE
Improvements to getheaders handling

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6974

Part of #2074, addresses issues raised in #2099.

### CODE REVIEW

**Comment by str4d** [comment]
We should also consider bitcoin/bitcoin#9061, which replaces bitcoin/bitcoin#6974 with an alternate strategy.

**Comment by daira** [comment]
Shouldn't this include https://github.com/bitcoin/bitcoin/pull/6172 ?

**Comment by daira** [comment]
Oh, we already had that one.

**Comment by daira** [comment]
Added to engineering meeting agenda to discuss whether we should do https://github.com/bitcoin/bitcoin/pull/9061 .

**Comment by nathan-at-least** [comment]
We're considering tabling this and Bitcoin #9061, on the theory that syncing isn't a problem for us *yet*, so let's deal with this only once it bothers real users.

**Comment by str4d** [comment]
ACK, tabling. We can re-open this PR later if we decide we want it.

**Pull request closed without merging**
