### PR TITLE
Trivial change: Capitalize the Z in Zerocash

### PR DESCRIPTION
**Pull request by defuse**

### CODE REVIEW

**Comment by str4d** [comment]
ACK!

**Comment by ebfull** [comment]
ACK!!!!

**Comment by str4d** [comment]
@zkbot r+

**Comment by nathan-at-least** [comment]
I don't want to block this PR, but are we sure capital latin Z is the best unicode character for this purpose? Maybe we should do a systemic review of all Z-like unicode characters.

**Comment by daira** [comment]
Post-hoc utACK :-p

**Pull request merged**
