### PR TITLE
Prevent non-x86_64 builds in zcutil/build.sh

### PR DESCRIPTION
**Pull request by defuse**

### CODE REVIEW

**Comment by defuse** [comment]
This is ready for review, but:

1. How do we feel about linking to github.com/zcash/zcash issues in the code?
2. Will this break any of our CI builds for not-officially-supported systems that we don't want to break?

Do we even use the code with those bugs anymore? If someone remembers where that code is I can add preprocessor macros to check the architecture right beside the vulnerable code.

**Comment by daira** [comment]
There are other little-endian 64-bit platforms, for example some variants of ARM and PowerPC.

**Comment by radix42** [comment]
I have an aarch64/arm64 v8 port, yes

**Comment by Eirik0** [comment]
Closing this ticket because we now support building on aarch64.

**Pull request closed without merging**
