### PR TITLE
[WIP] print zcashd config file settings and command-line args to debug.log

### PR DESCRIPTION
**Pull request by LarryRuane**
This will help when analyzing problems.

### CODE REVIEW

**Comment by LarryRuane** [comment]
Here's a sample of the output that this change writes to `debug.log`:
```
2019-01-23 22:59:26 Zcash version v2.0.2-8df7a073c-dirty (2019-01-03 08:49:16 -0800)
2019-01-23 22:59:26 config file and command line arguments:
2019-01-23 22:59:26     -addnode	testnet.z.cash
2019-01-23 22:59:26     -dbmaxopenfiles	1000
2019-01-23 22:59:26     -developerencryptwallet	1
2019-01-23 22:59:26     -developersapling	1
2019-01-23 22:59:26     -equihashsolver	tromp
2019-01-23 22:59:26     -experimentalfeatures	1
2019-01-23 22:59:26     -exportdir	lrexportdir
2019-01-23 22:59:26     -genproclimit	-1
2019-01-23 22:59:26     -rpcpassword	lrpw
2019-01-23 22:59:26     -rpcuser	lruser
2019-01-23 22:59:26     -server	1
2019-01-23 22:59:26     -testnet	1
2019-01-23 22:59:26     -txindex	1
```

**Comment by leto** [comment]
This looks useful

**Comment by LarryRuane** [comment]
Changed to WIP because this should be improved in two ways (https://github.com/bitcoin/bitcoin/pull/16115):
- don't log sensitive values such as rpc passwords
- when `debug.log` rotates (see `fReopenDebugLog`), these values should be logged again so they appear in the current log file.

Also, it needs a rebase.

**Comment by daira** [comment]
Concept ACK, modulo changes in https://github.com/bitcoin/bitcoin/pull/16115

**Comment by LarryRuane** [comment]
Now much better to cherry-pick https://github.com/bitcoin/bitcoin/pull/16115 (just merged), I will find some time to do that.

**Comment by LarryRuane** [comment]
I tried to cherry-pick https://github.com/bitcoin/bitcoin/pull/16115, but the implementation had to be very different (to the point of unrecognizability), because of changes they've made to the configuration argument processing.  

As I mentioned in the comment above, one of the main concerns of reviewers of the Bitcoin Core PR was not to leak sensitive information. A blacklist (enumerating the configuration arguments that contain sensitive information) wasn't considered good enough, because someone may create a new configuration setting with a sensitive value, and forget or not be aware of the blacklist. Having a whitelist avoids this problem, but requires the listing of a large number of configuration arguments. 

One of the major differences in this area between Bitcoin Core and Zcash is that in the former, all allowed configuration options must be declared (using `gArgs.AddArg()`). This has a nice advantage that a mistyped configuration option generates an error. (In Zcash, unknown arguments are simply ignored.) This also allowed an intermediate solution to the PR, which is to add a new flag to the set of flags already passed to `AddArg()` that says this argument has sensitive data. (I consider this only an intermediate solution because it's still possible that someone could add a new sensitive argument by copying an existing non-sensitive argument's `AddArg()` call without being aware of the `SENSITIVE` flag. But the reviewers were okay with this.) This meant only a few `AddArg()` calls had to be modified, and no blacklist or whitelist.

In Zcash, we don't have that option. So the latest force-push here implements a whitelist. This is very safe, but could become out of date as developers add new (non-sensitive) arguments without updating the whitelist (a fairly minor problem). I think this is still probably the best approach with minimal changes. If we don't want the whitelist, one alternative is to cherry-pick the entire argument processing from Bitcoin Core, which would be a significant amount of effort.

Another alternative is to take the whitelist in this PR, put it in a more public place, add a flags field (sensitive or not, plus possibly other flags in the future). This would allow us to catch mistyped configuration arguments, a nice benefit. This would be much easier than cherry-picking `gArgs`. And, actually, having a table is cleaner than the huge number of `AddArg()` calls currently in Bitcoin Core. But it does have the disadvantage that we diverge from them even more. I think in this case, that would be okay.

I recall a zcash PR that did exactly this (a whitelist to catch mistyped configuration arguments), but I can't seem to find it now.

I didn't port the tests over, because the test there uses a mechanism that we don't have (to track what gets logged). But I really don't think automated testing is very important for this change; or, I could port the tests (maybe just the unit test) if reviewers here think this is a good approach and worth merging.

Here's an example of the beginning of `debug.log` with the latest changes;
```
2020-03-20 17:35:46 Zcash version v2.1.1-1-c3df71a8e-dirty (2020-03-19 13:26:42 +0000)
2020-03-20 17:35:46 Config arg -equihashsolver=tromp
2020-03-20 17:35:46 Config arg -experimentalfeatures=1
2020-03-20 17:35:46 Config arg -genproclimit=-1
2020-03-20 17:35:46 Config arg -rpcpassword=****
2020-03-20 17:35:46 Config arg -rpcport=8232
```

**Comment by daira** [comment]
I'm dubious about this approach and I think we should consider taking more of the upstream changes.

**Comment by LarryRuane** [comment]
> I'm dubious about this approach and I think we should consider taking more of the upstream changes. Please hold off merging for now.

Thanks, I agree. Should we close this, at least for now? That's the best way to ensure it doesn't get merged. We can always reopen later if needed. I'll go ahead and do that now.

**Pull request closed without merging**
