### PR TITLE
Add z_getnotescount API

### PR DESCRIPTION
**Pull request by oxarbitrage**
Implement new API call to count notes in wallet. 

Closes https://github.com/zcash/zcash/issues/4463

### CODE REVIEW

**Comment by kowalski** [comment]
@oxarbitrage :heart::heart::heart:

**Comment by holmesworcester** [comment]
This is extremely helpful for us on [Zbay](https://zbay.app)!

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient failure.

@zkbot retry

**Pull request merged**
