### PR TITLE
Add a roundtrip test for Orchard merkle frontier serialization from the C++ side.

### PR DESCRIPTION
**Pull request by nuttycom**

### CODE REVIEW

**Review by ebfull — APPROVED** [review]

**Review by therealyingtong — DISMISSED** [review]
utACK

**Review by str4d — DISMISSED** [review]
utACK with non-blocking suggestion.

**Comment by str4d** [comment]
Debian 11 CI builder failed in gtest; looks like an unrelated transient failure due to builder load affecting disk I/O.

**Review by str4d — APPROVED** [review]
utACK

**Pull request merged**
