### PR TITLE
Fix CTransaction undefined behaviour by removing const specifiers and const_casts

### LINKED ISSUE #967: Bitcoin deserialization API strictly speaking invokes undefined behaviour
Consider for example https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/primitives/transaction.h#L318 :

```
class CTransaction
{
    //...
    const int32_t nVersion;
    //...
    template <typename Stream, typename Operation>
    inline void SerializationOp(Stream& s, Operation ser_action, int nType, int nVersion) {
        READWRITE(*const_cast<int32_t*>(&this->nVersion));
        //...
    }
}
```

This invokes undefined behaviour on deserialization, because a const variable is modified via a pointer.

We probably get away with this when compiling with gcc.

### PR DESCRIPTION
**Pull request by daira**
Supercedes #981. Fixes #967.

### CODE REVIEW

**Comment by defuse** [comment]
Maybe we should submit this PR to upstream to get discussion going?

**Comment by daira** [comment]
@zkbot try

**Comment by ebfull** [comment]
I think this is low-priority, perhaps even dangerous, and we should have consultation with upstream before we change anything like this.

**Comment by daira** [comment]
I want to get the fix right before doing that.

**Comment by daira** [comment]
@zkbot try

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
the heck...

@zkbot force

**Comment by defuse** [comment]
I know we had a long discussion about this in the engineering meeting, but I'm ACK on this.

Have we added new code that reads from these variables? If we have, then the argument that upstream bitcoin has not seen problems caused by this undefined behavior is not valid. Upstream's code might not read and write to the variables in a way that'll trigger the optimization, but the code that we added might.

**Comment by defuse** [comment]
Maybe we can instrument GCC to see if it's doing the kind of optimization that can cause problems. What is that optimization anyway, is it just that the const lets the compiler re-order reads from the variables so that they come before a write that was supposed to affect the read?

I tried to trick the compiler like this:

```
[firexware@firexware-pc zcash]$ git diff
diff --git a/src/gtest/test_tautology.cpp b/src/gtest/test_tautology.cpp
index 56b3555..db46865 100644
--- a/src/gtest/test_tautology.cpp
+++ b/src/gtest/test_tautology.cpp
@@ -1,5 +1,17 @@
 #include <gtest/gtest.h>
+#include "primitives/transaction.h"
 
 TEST(tautologies, seven_eq_seven) {
-    ASSERT_EQ(7, 7);
+    CMutableTransaction mtx1, mtx2;
+    mtx1.nVersion = 1;
+    mtx2.nVersion = 2;
+
+    CTransaction tx1(mtx1);
+    CTransaction tx2(mtx2);
+
+    int32_t total = 0;
+    total += tx1.nVersion;
+    tx1 = tx2;
+    total += tx1.nVersion;
+    ASSERT_TRUE(total == 3);
 }
```

But the assembly came out correct:

```
  40fe50:       8b 9c 24 70 01 00 00    mov    ebx,DWORD PTR [rsp+0x170]
  40fe57:       48 8d 74 24 30          lea    rsi,[rsp+0x30]
  40fe5c:       48 8d bc 24 30 01 00    lea    rdi,[rsp+0x130]
  40fe63:       00 
  40fe64:       e8 b7 7b 31 00          call   727a20 <_ZN12CTransactionaSERKS_>
  40fe69:       89 d8                   mov    eax,ebx
  40fe6b:       03 84 24 70 01 00 00    add    eax,DWORD PTR [rsp+0x170]
  40fe72:       83 f8 03                cmp    eax,0x3
  40fe75:       0f 94 04 24             sete   BYTE PTR [rsp]
```

I'm not sure what optimization level that was compiled at. I wonder if I add a bunch of crap to before the `tx1 = tx2;` line if it will make the compiler not want to keep the original value around in a register.

**Comment by ebfull** [comment]
We decided not to accept this PR right now because it introduces a change in `CTransaction` semantics in order to fix what is an unlikely memory safety issue, which means it's not a priority for us. We'll follow what upstream does after launch.

@daira for the record isn't happy with this decision, but we need to close PRs that won't be merged anyway because we're renaming `zc.v0.11.2.latest`.

**Pull request closed without merging**
