### PR TITLE
#776 add sha256sum support for Mac OS X

### PR DESCRIPTION
**Pull request by loxal**

### CODE REVIEW

**Comment by ebfull** [comment]
Nice!

ACK

**Comment by ebfull** [comment]
Actually, why was a space placed in `<< EOF`?

**Comment by loxal** [comment]
fixed & rebased

**Comment by ebfull** [comment]
Okay ACK again. :)

**Comment by defuse** [comment]
NACK: This should require an `-a 256` option since SHA1 is the default (at least on my system). Is it not failing because because SHA256 is the default on OSX?

**Comment by defuse** [comment]
Nevermind, I'm an idiot, the `-a 256` is right there! ACK!

**Comment by loxal** [comment]
```
✔ ~/Library/Ethereum 
01:36 $ shasum --help
Usage: shasum [OPTION]... [FILE]...
Print or check SHA checksums.
With no FILE, or when FILE is -, read standard input.

  -a, --algorithm   1 (default), 224, 256, 384, 512, 512224, 512256
  -b, --binary      read in binary mode
  -c, --check       read SHA sums from the FILEs and check them
  -t, --text        read in text mode (default)
  -p, --portable    read in portable mode
                        produces same digest on Windows/Unix/Mac
  -0, --01          read in BITS mode
                        ASCII '0' interpreted as 0-bit,
                        ASCII '1' interpreted as 1-bit,
                        all other characters ignored

The following two options are useful only when verifying checksums:
  -s, --status      don't output anything, status code shows success
  -w, --warn        warn about improperly formatted checksum lines

  -h, --help        display this help and exit
  -v, --version     output version information and exit

When verifying SHA-512/224 or SHA-512/256 checksums, indicate the
algorithm explicitly using the -a option, e.g.

  shasum -a 512224 -c checksumfile

The sums are computed as described in FIPS-180-4.  When checking, the
input should be a former output of this program.  The default mode is to
print a line with checksum, a character indicating type (`*' for binary,
` ' for text, `?' for portable, `^' for BITS), and name for each FILE.

Report shasum bugs to mshelor@cpan.org
````

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
