### PR TITLE
Zcash zk-SNARK public parameters for 1.0 "Sprout".

### LINKED ISSUE #1553: Integrate the zkSNARK parameters generated from the official ceremony.

### PR DESCRIPTION
**Pull request by ebfull**
Created in the ceremony this weekend! :tada:

We're writing a blog post about this, I'm going to publish the code shortly too.

Closes #1553

### CODE REVIEW

**Comment by daira** [comment]
utACK (that this is the correct way of changing the keys, not that the keys are consistent with the MPC transcript).

**Comment by ebfull** [comment]
There are some objects in the git repo that are too large to store on github, so I'm arguing with the github folks to let us exceed their limits by a couple MB. :sweat_smile:

**Comment by ebfull** [comment]
Code for the MPC is up (and some ceremonial information) https://bitbucket.org/zcashco/mpc

**Comment by str4d** [comment]
ACK

@zkbot r+

**Comment by petertodd** [comment]
FYI re: file sizes, look into using git annex: http://git-annex.branchable.com/

I'm recording all evidence of the ceremony in a git-annex repository.

**Pull request merged**
