### PR TITLE
Closes #3301. Non-void function should not have empty definition.

### LINKED ISSUE #3301: Fix bug where non-void function had empty definition
macOS clang builder detected an error, which the Linux gcc builders treated as a warning.
```
In file included from bloom.cpp:7:
In file included from ./primitives/transaction.h:22:
In file included from ./zcash/JoinSplit.hpp:7:
./zcash/Note.hpp:19:33: error: control reaches end of non-void function [-Werror,-Wreturn-type]
    virtual uint256 cm() const {};
                                ^
1 error generated.
```

Full build log: https://ci.z.cash/#/builders/16/builds/359

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
- macos builder error is unrelated to change: missing python2 at sec-hard step
- debian8 kitchen sink builder error is transient: mempool_tx_input_limit

**Comment by bitcartel** [comment]
Passed.  Ready for review!

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
