### PR TITLE
Update libsodium from 1.0.11 to 1.0.15

### LINKED ISSUE #2693: Update libsodium.mk
libsodium-1.0.11 is a dead link now
https://download.libsodium.org/libsodium/releases/

See https://github.com/hellcatz/zcash/commit/44603b9450c5170617891c80ad7e523ee4fd8174

Maybe update for libsodium-1.0.15 ?

### PR DESCRIPTION
**Pull request by syd0**
Closes #2693.

### CODE REVIEW

**Comment by daira** [comment]
Thanks @syd0 :-)

**Comment by daira** [comment]
@zkbot r+

**Comment by arcalinea** [comment]
When I build this branch, why am I getting an error for libsnark?
```
make[2]: *** No rule to make target 'snark/build/lib/libsnark.a', needed by 'zcashd'.  Stop.
make[2]: *** Waiting for unfinished jobs....
mv -f zcash/.deps/libzcash_a-Note.Tpo zcash/.deps/libzcash_a-Note.Po
mv -f .deps/libbitcoin_util_a-utiltime.Tpo .deps/libbitcoin_util_a-utiltime.Po
mv -f zcash/.deps/libzcash_a-JoinSplit.Tpo zcash/.deps/libzcash_a-JoinSplit.Po
mv -f zcash/.deps/libzcash_a-prf.Tpo zcash/.deps/libzcash_a-prf.Po
make[2]: Leaving directory '/home/jay/Zcash/zcash/src'
Makefile:5454: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/jay/Zcash/zcash/src'
Makefile:623: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by syd0** [comment]
That's weird, not sure why you'd get that. I doubt it will help but maybe try a `make clean` first to see if that helps?

**Comment by arcalinea** [comment]
Built on another branch, came back and it built on this one.

**Pull request merged**
