### PR TITLE
Delete old protocol version constants and simplify code that used them.

### LINKED ISSUE #2244: Delete old version constants from src/version.h, and make code that used them unconditional
The Zcash network launched with a `PROTOCOL_VERSION` of 170002. This is also the value of `MIN_PEER_PROTO_VERSION`, so we will immediately disconnect from any peer claiming to have an older version than this. However version.h also defines several constants for older Bitcoin P2P protocol versions that lacked various features or that needed workarounds for bugs. We should remove these, and simplify any code that references them to assume that the features are available, and that the workarounds are not needed.

### PR DESCRIPTION
**Pull request by daira**
fixes #2244

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
@str4d done.

**Comment by ebfull** [comment]
utACK as well.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
