### PR TITLE
zcash-addrgen, a small tool to generate a shielded address

### PR DESCRIPTION
**Pull request by goblin**
Hello all,

I've written a tiny tool to convert a random seed (which can come from a mnemonic) into a Spending Key and a Payment Address. This will be a part of my cold storage solution - I'll put it on a Live CD later. It's meant for quick and easy address generation, without having to download all the network params (without which a zcash node doesn't like to start up).

This is probably too early a stage to warrant merging into the official zcash tree, but please let me know if you like it. I'll be happy to polish it up a bit if you're interested in merging it later. Or if you think it sucks feel free to close this PR.

### CODE REVIEW

**Comment by goblin** [comment]
My LiveCD (with zcash-addrgen) is available at https://github.com/goblin/gblcclcd

This should make it easier to use Zcash with cold storage.

**Comment by mms710** [comment]
Question: Is this still a change we should make given the implementation of ZIP 32 (HD seeds)?

**Comment by goblin** [comment]
Nope, I'll need to review this, but I believe the changes in 2.0 make this PR obsolete.

**Comment by daira** [comment]
This is incompatible with ZIP 32, and in any case is obsolete.

**Pull request closed without merging**
