### PR TITLE
Upstream encoding cleanups

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#7922
- bitcoin/bitcoin#7825
- bitcoin/bitcoin#8317
- bitcoin/bitcoin#9804
  - Only the commit that changed `base58.cpp`

Precursor to #3202.

### CODE REVIEW

**Comment by mdr0id** [comment]
utACK:

Changes look reasonable; likely to aid some of the dangling mem leaks.

**Comment by bitcartel** [comment]
@zkbot try

**Comment by str4d** [comment]
Unrelated transient RPC test failure.

@zkbot retry

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
@zkbot p=1

**Pull request merged**
