### PR TITLE
Bitcoin 0.12 test PRs 1

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6337
- bitcoin/bitcoin#6390
- bitcoin/bitcoin#5515
- bitcoin/bitcoin#6287 (partial, remainder included in bitcoin/bitcoin#6703)
- bitcoin/bitcoin#6465

Part of #2074.

### CODE REVIEW

**Comment by str4d** [comment]
d51ad27b63e9a90bb6d74a187189c50c674274c0 needs careful checking against https://github.com/bitcoin/bitcoin/pull/5881/commits/defd2d55b789163be4a863d0887d5d309ff9cde3 because we need to ensure that the improved test logic is actually maintained.

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
@zkbot try

**Comment by daira** [comment]
Keeping track of suitability-to-merge review:

- [ ] bitcoin/bitcoin#6337
- [ ] bitcoin/bitcoin#5881
- [ ] https://github.com/bitcoin/bitcoin/commit/3f16971442f1b52f94759b15998bc82e82a90aea
- [ ] bitcoin/bitcoin#6365
- [ ] https://github.com/bitcoin/bitcoin/commit/56dc70439f4a5cfeec3c49609229d973349e5c8f
- [ ] bitcoin/bitcoin#6390
- [ ] bitcoin/bitcoin#6414
- [ ] bitcoin/bitcoin#5515
- [ ] bitcoin/bitcoin#6287 (partial, remainder included in bitcoin/bitcoin#6703)
- [ ] bitcoin/bitcoin#6465

**Comment by daira** [comment]
Re: https://github.com/bitcoin/bitcoin/pull/5881 , I can't confirm that this is only changing tests. The description says:

> The second commit introduces a primitive method CTransaction::IsEquivalentTo and uses it in the wallet to ensure that SyncMetaData is only called for malleability clones, not general conflict (doublespend) transactions.

but there's no explanation of why this should be the case. (SyncMetaData is not only called by tests; it's called by CWallet::AddToSpends which is called by CWallet::AddToWallet; there's also some overloading of those methods which makes it difficult to follow the control flow.)

**Comment by daira** [comment]
Re: https://github.com/bitcoin/bitcoin/pull/6414 , I don't agree with moving the two tests to the extended test suite. Saving 15 seconds on the overall test time is not important.

**Comment by daira** [comment]
Re: 0ffc9b1f31a647a25e06271be381dab2f5d1a0da, I wasn't able to compile with clang in order to check what the results of compiling with ``-Wthread-safety`` are.

**Comment by radix42** [comment]
oculdn't compile bitcoin or zcash with clang? because to my knowledge zcash hasn't built with clang since libsnark won't compile with a recent clang (at least since I've been trying)

**Comment by daira** [comment]
For this specific purpose I don't need to compile the dependencies (or I can compile those with g++); I just need to see the output from attempting to compile the main zcash code with clang++.

**Comment by radix42** [comment]
oh I hadn't ever tried that on linux...failed when I tried that on Mac last fall....I'll have to give it a go sometime

**Comment by bitcartel** [comment]
Tracking my review
- [ ] bitcoin/bitcoin#6337
- [ ] bitcoin/bitcoin#5881
- [ ] bitcoin/bitcoin@3f16971
- [ ] bitcoin/bitcoin#6365
- [ ] bitcoin/bitcoin@56dc704
- [ ] bitcoin/bitcoin#6390
- [ ] bitcoin/bitcoin#6414
- [ ] bitcoin/bitcoin#5515
- [ ] bitcoin/bitcoin#6287 (partial, remainder included in bitcoin/bitcoin#6703)
- [ ] bitcoin/bitcoin#6465

**Comment by arcalinea** [comment]
Keeping track of review and comments made so far: 

- [x] bitcoin/bitcoin#6337
- [ ] bitcoin/bitcoin#5881
        + @daira NACK: can't confirm that this is only changing tests
        + @bitcartel also NACK
- [ ] https://github.com/bitcoin/bitcoin/commit/3f16971442f1b52f94759b15998bc82e82a90aea
        + daira NACK, bitcartel ACK
- [ ] bitcoin/bitcoin#6365
        + daira NACK, bitcartel ACK
- [ ] https://github.com/bitcoin/bitcoin/commit/56dc70439f4a5cfeec3c49609229d973349e5c8f
        + daira NACK, bitcartel ACK
- [x] bitcoin/bitcoin#6390
- [ ] bitcoin/bitcoin#6414
        + daira NACK:  I don't agree with moving the two tests to the extended test suite. Saving 15 seconds on the overall test time is not important.
         + bitcartel ACK
- [x] bitcoin/bitcoin#5515
- [ ] bitcoin/bitcoin#6287 (partial, remainder included in bitcoin/bitcoin#6703)
        + NACK
- [ ] bitcoin/bitcoin#6465
        + daira NACK, bitcartel ACK

**Comment by str4d** [comment]
Rebased and trimmed PRs.

**Comment by arcalinea** [comment]
@zkbot r+

**Pull request merged**
