### PR TITLE
ZIP 239 preparations 3

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:
- bitcoin/bitcoin#8080
- bitcoin/bitcoin#8082
- bitcoin/bitcoin#8126
- bitcoin/bitcoin#7910
  - This is the unsquashed version of bitcoin/bitcoin#8149
  - We take three cleanup commits to the protocol / `CInv` code.
- bitcoin/bitcoin#8822
- bitcoin/bitcoin#8880
  - Excluding the first commit (we don't have the comment it fixes yet).
- bitcoin/bitcoin#19322

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by str4d** [comment]
RPC test failures are reproducible (though `mempool_nu_activation.py` appears intermittent). I'll investigate tomorrow (which is technically today, as I haven't slept yet).

**Comment by str4d** [comment]
RPC test failures were due to me originally trying to backport https://github.com/bitcoin/bitcoin/pull/8126 before a needed commit (adding score-based sorting) from https://github.com/bitcoin/bitcoin/pull/6898, and then once the latter was backported in #5269 I mis-rebased this branch so that the score-based sorting was inconsistent. [The fix](https://github.com/zcash/zcash/compare/57cf4c271cc68d6c5e8a64e73cf42470519589f7..8469683eb62be535ea26d0e5b98a0246ac56c426):
```diff
diff --git a/src/txmempool.cpp b/src/txmempool.cpp
index bdf14e7eb7..25b0d37cbc 100644
--- a/src/txmempool.cpp
+++ b/src/txmempool.cpp
@@ -699,7 +699,7 @@ public:
         // As of https://github.com/bitcoin/bitcoin/pull/8126 this comparator
         // duplicates that function (as it doesn't need to hold a dependency
         // on the mempool).
-        return CompareTxMemPoolEntryByFee()(*a, *b);
+        return CompareTxMemPoolEntryByScore()(*a, *b);
     }
 };
 }
```

**Review by nuttycom — APPROVED** [review]
utACK; verified against the upstream changes.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
