### PR TITLE
change librustzcash_sapling_compute_cm name

### PR DESCRIPTION
**Pull request by oxarbitrage**
Part of https://github.com/zcash/zcash/issues/3446

Need https://github.com/zcash/librustzcash/pull/209

### CODE REVIEW

**Comment by str4d** [comment]
This blocks on #4321 and zcash/librustzcash#155.

**Comment by daira** [comment]
All of the blockers are resolved.

**Comment by therealyingtong** [comment]
Needs a rebase.

**Comment by str4d** [comment]
Superceded by #4682.

**Pull request closed without merging**
