### PR TITLE
Remove insecurely-downloaded dependencies that we don't currently use.

### LINKED ISSUE #898: Make sure all depends packages are verified against a hash
Currently Crypto++ is downloaded and extracted without verification. This is how a compromise of the z.cash web server could lead to a compromise of all of our developers (or users who compile from source).

https://github.com/zcash/zcash/pull/888/files#r61473757

#888 removes Crypto++ but we need to make sure all of the packages are verified against a hash.

### PR DESCRIPTION
**Pull request by defuse**
Closes #898.

### CODE REVIEW

**Comment by daira** [comment]
ACK that this can safely be merged. I have *not* checked that these are the only packages for which hashes were not verified.

**Comment by ebfull** [comment]
Is there a way we can avoid removing these dependencies but still ensure they are verified? We don't use them because we don't yet use Qt.

**Comment by defuse** [comment]
Yes, but it's more work, so I vote we just remove them for now.

**Comment by ebfull** [comment]
ACK.

@zkbot r+

**Comment by ebfull** [comment]
This needs to be rebased. :)

**Comment by daira** [comment]
ACK.

**Comment by ebfull** [comment]
@zkbot r+

**Pull request merged**
