### PR TITLE
z4 release

### LINKED ISSUE #978: Create a release for 2016.0-beta

### PR DESCRIPTION
**Pull request by defuse**
Closes #978

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot r+

**Comment by daira** [comment]
Isn't there also a version number in the source code somewhere, or was that already changed?

**Comment by str4d** [comment]
Nope, it was missed:

```
$ ./src/zcash-cli --version
Zcash RPC client version v0.11.2.0.z3-592b2f0
```

@nathan-at-least or @ebfull, this should be added to the release process doc. The files to update are `configure.ac` and `src/clientversion.h` (although the latter doesn't actually appear to ever be used, strangely...)

**Comment by ebfull** [comment]
Darn. I was under the impression from our last release that we didn't have a version like this anywhere. Modifying `configure.ac` needs to be added to the release process notes.

**Comment by str4d** [comment]
We didn't last release, but then I made #943 :stuck_out_tongue_winking_eye:

**Comment by ebfull** [comment]
Can you make another PR like that?

**Pull request merged**
