### PR TITLE
Fix proton patch regression.

### LINKED ISSUE #3916: Fix proton library regression
It appears that merged PR https://github.com/zcash/zcash/pull/3809 breaks Proton. where the library would not be built.

```
zcutil/build.sh --enable-proton

...

checking proton/connection.hpp usability... yes
checking proton/connection.hpp presence... yes
checking for proton/connection.hpp... yes
checking for main in -lqpid-proton-cpp... no
configure: WARNING: Proton libraries not found, disabling Proton support

...

qa/pull-tester/rpc-tests.sh proton_test.py

Tests completed: 0
successes 0; failures: 0
```

For reference, when Proton is built correctly, you should see:
```
checking proton/connection.hpp usability... yes
checking proton/connection.hpp presence... yes
checking for proton/connection.hpp... yes
checking for main in -lqpid-proton-cpp... yes```

...

qa/pull-tester/rpc-tests.sh proton_test.py
=== Running testscript proton_test.py ===
Initializing test directory /tmp/testBx4gq_
Proton listening on: 127.0.0.1:25672
Stopping nodes
Cleaning up
Tests successful
--- Success: proton_test.py ---



Tests completed: 1
successes 1; failures: 0
```

### PR DESCRIPTION
**Pull request by defuse**
Closes #3916.  Fixes a regression introduced in #3809.

Co-authored-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by defuse** [comment]
Oh I should mention @daira helped with this.

**Comment by bitcartel** [comment]
@zkbot treeclosed-

**Comment by bitcartel** [comment]
@zkbot r+

**Comment by defuse** [comment]
Added a commit to remove the deprecation of `proton::url` to fix the build error. Once we merge this a ticket should be filed to fix it more like in #3920.

**Comment by bitcartel** [comment]
Looks good, utACK https://github.com/zcash/zcash/commit/675cf3d606722feec0bb3960837152340936181a

@zkbot try

**Comment by bitcartel** [comment]
Build succeeded on required builders, except one which failed due to "Error: Error: Disk space is low!"

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
