### PR TITLE
Release v5.9.0-rc1

### LINKED ISSUE #6855: [zcashd book] Document that Debian Bookworm is a tier 1 platform

### PR DESCRIPTION
**Pull request by str4d**
fixes #6855

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]
utACK 0db3fc3f2a7f79682e0d32e8d26d33c553a19557

**Review by daira — APPROVED** [review]
utACK

**Comment by cshintov** [comment]
According to [this](https://github.com/zcash/zcash/blob/0db3fc3f2a7f79682e0d32e8d26d33c553a19557/doc/book/src/user/release-support.md#L45) is it mandatory to upgrade to this release if I want to keep running official zcash?

> | 5.8.0 | 2024-01-02 | 2482200 | 2024-04-23 |

Will the debian bullseye package release for this release?

**Comment by str4d** [comment]
There will be a 5.9.0 release PR today, after which Debian packages will be published.

**Pull request merged**
