### PR TITLE
Update which lock to synchronize on when calling GetBestAnchor().

### PR DESCRIPTION
**Pull request by bitcartel**
Closes issue #2623.

### CODE REVIEW

**Comment by bitcartel** [comment]
@zkbot try

**Comment by daira** [comment]
Reviewing now.

**Comment by daira** [comment]
Note that ``BatchWrite`` also affects ``hashAnchor``.

**Comment by str4d** [comment]
> Note that `BatchWrite` also affects `hashAnchor`.

Yes, and it is only called via `Flush` AFAICT.

**Comment by daira** [comment]
There's an inconsistency between ``ConnectTip`` and ``DisconnectTip`` in main.cpp: both are required to hold ``cs_main``, but only the former asserts that it does.

**Comment by daira** [comment]
In general I would be inclined to sprinkle a lot more ``AssertLockHeld(cs_main);``s around. I don't know what the performance cost of an ``AssertLockHeld`` is, but the call chains are really tricky to follow otherwise.

**Comment by str4d** [comment]
> [Edit: oh, but there is no inconsistency between ConnectTip and DisconnectTip; neither of those assert that they hold the lock.]

Right; both `ConnectTip` and `DisconnectTip` are only called by functions that either lock on `cs_main` or assert it is held.

> In general I would be inclined to sprinkle a lot more `AssertLockHeld(cs_main);`s around. I don't know what the performance cost of an `AssertLockHeld` is, but the call chains are really tricky to follow otherwise.

I'm somewhat inclined to agree, but not for this PR. Also note that upstream Bitcoin still doesn't have them in `ConnectTip` and `DisconnectTip`.

**Comment by daira** [comment]
I particularly don't like the fact that ``DisconnectBlock`` doesn't assert that ``cs_main`` is held even though it seems to be at the same level of abstraction as ``ConnectBlock``, and is not static. (I checked all callers and it's ok, but yuck.)

**Comment by daira** [comment]
Checked all call chains:

* ConnectBlock -> PushAnchor, GetBestAnchor (asserts lock)
* DisconnectBlock -> PopAnchor
* CVerifyDB::VerifyDB -> DisconnectBlock (takes lock)
* DisconnectTip -> DisconnectBlock, Flush, GetBestAnchor
* ConnectTip -> Flush, GetBestAnchor
* FlushStateToDisk -> Flush (takes lock)
* ActivateBestChainStep -> DisconnectTip, ConnectTip (asserts lock)
* InvalidateBlock -> DisconnectTip (asserts lock)
* getblockchaininfo (rpcblockchain.cpp) -> GetBestAnchor (takes lock)

LoadBlockIndexDB -> GetBestAnchor does not take the lock, and is called during initialization (from LoadBlockIndex, from AppInit2). I'd prefer if it did take the lock, but I guess we're running in a single thread at that point so it should be fine.

utACK.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
