### PR TITLE
Merge current secp256k1 subtree

### PR DESCRIPTION
**Pull request by str4d**
Part of #1272.

### CODE REVIEW

**Comment by bitcartel** [comment]
Changes look innocuous.  Two questions:
1. Why squash the commits from upstream?  Why not retain the history?
2. What differences are there between upstream and our repo?

**Comment by str4d** [comment]
1. @bitcartel we *could*, but a) there isn't a need to include them, and b) historically they haven't ever been included, so IDK how the subtree would react (probably fine, but...)

2. None now. You can (and should) check this with `./contrib/devtools/git-subtree-check.sh src/secp256k1`

**Comment by bitcartel** [comment]
@str4d point (2) above, here's what I get:
```
./contrib/devtools/git-subtree-check.sh src/secp256k1
ERROR: subtree commit 6ad5cdb42a1a8257289a0423d644dcbdeab0f83c unavailable. Fetch/update the subtree repository
```

**Comment by str4d** [comment]
@bitcartel Ah, you need to have the libsecp256k1 repository fetched inside your Zcash git repository. Do this first:

```
$ git remote add secp256k1_remote https://github.com/bitcoin-core/secp256k1.git
$ git fetch secp256k1_remote
```

**Comment by str4d** [comment]
Oh, and upstream have just merged https://github.com/bitcoin-core/secp256k1/pull/486 which looks very useful - do we want this now? If so, I'll add that to this PR (as a separate subtree update, to make it easier to review here).

**Comment by str4d** [comment]
We decided to leave out the new upstream performance PR, and stick with this current PR as-is.

**Comment by daira** [comment]
``git-subtree-check`` passed for me, and I had already reviewed the upstream changes. @zkbot r+

**Pull request merged**
