### PR TITLE
Add address indexing for retrieving unspent outs for non wallet-based addresses

### PR DESCRIPTION
**Pull request by ianpurton**
Most exchanges and wallets etc use a custom version of bitcoind that adds address indexing leading to problems

Address indexing is essential as no business wants to use the zcashd wallet due to security concerns of having private keys on the server. If Zcash doesn't have address indexing then businesses are forced to either use a patched version of zcash or use a 3rd part API leading to centralization.

It would be nice if ZCash had this out of the box. This pull request incorporates address indexing based on the following patch for bitcoin core. https://github.com/dexX7/bitcoin

Please let me know if this feature can be added then I'm available to do what is required to get this merged.

### CODE REVIEW

**Comment by ianpurton** [comment]
Forgot to mention. This functionality is switched on with the addrindex=1 parameter in the conf file.

**Comment by str4d** [comment]
Is this the same patch that Bitcore uses (on my phone, haven't inspected it yet)? I've been maintaining that (along with the rest of their commits) in a separate branch on my fork; merging it into zcash would definitely reduce my maintenance workload.

**Comment by ianpurton** [comment]
@str4d Not sure if it's exactly the same patch, do you have a pointer?

**Comment by str4d** [comment]
This is the Bitcore branch I'm referring to (they appear to have merged the ones I was originally using into a single 0.12.1 branch now):

https://github.com/bitpay/bitcoin/commits/0.12.1-bitcore

This is my branch with the patches (from their older bitcore-3 branch) backported into 1.0.0 along with things from Bitcoin 0.12+ we were missing:

https://github.com/str4d/zcash/tree/v1.0.0-bitcore-3?files=1

**Comment by daira** [comment]
Concept ACK, but this should be a ZIP.

**Comment by nathan-at-least** [comment]
It's currently possible to use `importaddress` to add a watch-only address. Is address indexing functionally equivalent to making all (transparent) addresses watch-only automatically?

**Comment by ianpurton** [comment]
@nathan-at-least  importaddress has high overhead. For a wallet provider every address we create would require a re-index which takes a few seconds on a large blockchain.

**Comment by cyberluke** [comment]
what is the status here?

**Comment by katzo9** [comment]
@str4d  does your branch v1.1.0-bitcore still working with overwinter just to watch addresses ?

**Comment by LarryRuane** [comment]
I believe this is a subset-duplicate of https://github.com/zcash/zcash/issues/3708 although the RPC interface details are different. Those changes will be merged soon (within the next couple of months). Closing; please reopen if this PR has functionality that isn't included there.

**Pull request closed without merging**
