### PR TITLE
Back-merge hotfixes v5.3.3 and v5.4.2 to master

### PR DESCRIPTION
**Pull request by nuttycom**

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK. Checked both the overall diff and that all expected commits are included.

**Review by str4d — CHANGES_REQUESTED** [review]
NACK. Currently missing the last few commits of the v5.3.3 branch which includes the v5.3.3 tag.

**Review by daira — APPROVED** [review]
utACK ec88817b727b70f138f5d64a515310ee1e8cc03c.
Checked overall diff and that dbb15bea88f5c3e39b1d0dcf7bf077ddb607f9d9 and b1fd336f8f1103d14ef234025a8753f459a2b62d are included.

**Review by str4d — APPROVED** [review]
utACK ec88817b727b70f138f5d64a515310ee1e8cc03c

**Pull request merged**
