### PR TITLE
Document wallet reindexing for z_importkey description in payment-api.md

### PR DESCRIPTION
**Pull request by arcalinea**
Documents how to enable funds for imported keys  #1395

### CODE REVIEW

**Comment by arcalinea** [comment]
@str4d @bitcartel let me know if there are any other places you think this warning should go

**Comment by bitcartel** [comment]
The warning is already in the beta guide so I think we're good.

Btw: There's a line astarting "beta 1 release note: encrypted wallets are not yet fully supported. If the wallet is protected with a passphrase, zkeys will not be persisted to disk." which no longer applies, can you remove that so that we don't have to do another PR?  Thanks.

**Comment by arcalinea** [comment]
@zkbot r+

**Comment by bitcartel** [comment]
ACK
@zkbot r+

**Comment by daira** [comment]
ACK

**Pull request merged**
