### PR TITLE
Bitcoin 0.12 misc PRs 1

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6198
- bitcoin/bitcoin#6206
- bitcoin/bitcoin#5927
- bitcoin/bitcoin#6213
- bitcoin/bitcoin#6061
- bitcoin/bitcoin#6283 (partial, remainder was pulled in #929)
- bitcoin/bitcoin#6272
- bitcoin/bitcoin#6316
- bitcoin/bitcoin#6133
- bitcoin/bitcoin#6387
- bitcoin/bitcoin#6401
- bitcoin/bitcoin#6434
- bitcoin/bitcoin#6372
- bitcoin/bitcoin#6447
- bitcoin/bitcoin#6149
- bitcoin/bitcoin#6468

Part of #2074.

### CODE REVIEW

**Comment by str4d** [comment]
@zkbot try

**Comment by bitcartel** [comment]
Keeping track of my review:

- [ ] bitcoin/bitcoin#6198
- [ ] bitcoin/bitcoin#6206
- [ ] bitcoin/bitcoin#6152
- [ ] bitcoin/bitcoin#5927
- [ ] bitcoin/bitcoin#6213
- [ ] bitcoin/bitcoin#5975
- [ ] bitcoin/bitcoin#6061
- [ ] bitcoin/bitcoin#6283 (partial, remainder was pulled in #929)
- [ ] bitcoin/bitcoin#6272
- [ ] bitcoin/bitcoin#6316
- [ ] bitcoin/bitcoin#6299 (partial, remainder in #2100)
- [ ] bitcoin/bitcoin#6133
- [ ] bitcoin/bitcoin#6361
- [ ] bitcoin/bitcoin#6387
- [ ] bitcoin/bitcoin#6401
- [ ] bitcoin/bitcoin#6370
- [ ] bitcoin/bitcoin#6434
- [ ] bitcoin/bitcoin#6372
- [ ] bitcoin/bitcoin#6447
- [ ] bitcoin/bitcoin#6149
- [ ] bitcoin/bitcoin#6468

**Comment by daira** [comment]
Re: https://github.com/bitcoin/bitcoin/pull/6152 , won't we need ``EraseTransaction`` if we implement transaction expiry (#754)?

**Comment by daira** [comment]
NACK on merging https://github.com/bitcoin/bitcoin/pull/5927 without further discussion. On its own, it introduces potential DoS issues: see https://github.com/bitcoin/bitcoin/pull/5927#issuecomment-84414418 and https://github.com/bitcoin/bitcoin/pull/5927#issuecomment-104665085 .

In Bitcoin Core, this was merged together with https://github.com/bitcoin/bitcoin/pull/5875 . *However*, I believe the latter change is semantically incorrect: it's not sufficient to only process blocks that have more work than the current tip, because it could be the case that a node hasn't yet processed an ancestor of a block that has more work than the current tip (but does not itself have more work). The correct behaviour is described on that ticket (https://github.com/bitcoin/bitcoin/pull/5875#issuecomment-86630759) but I don't believe the PR actually implements it, so it is not sufficient to just merge https://github.com/bitcoin/bitcoin/pull/5927 plus https://github.com/bitcoin/bitcoin/pull/5875.

Please open a ticket to track this.

**Comment by daira** [comment]
Re: https://github.com/bitcoin/bitcoin/pull/6213 , I don't think we have ``-blockversion`` (it's not in init.cpp).

**Comment by sipa** [comment]
@daira #5875 is only about processing of full blocks that arrive without us having requested them. If a chain of non-downloaded blocks exists that overall has more work than the currently active chain, we will still process its headers, and as a result, start requesting the blocks using the normal mechanism.

**Comment by daira** [comment]
Actually I'm not sure the ``-blockversion`` option even makes sense, since it's likely that the block format would change if the block version did. In any case if we added it, it should probably be behind ``-experimentalfeatures``.

**Comment by daira** [comment]
@sipa Thanks for clarifying that. In any case we should not merge https://github.com/bitcoin/bitcoin/pull/5927 without https://github.com/bitcoin/bitcoin/pull/5875 , which this PR currently does.

**Comment by daira** [comment]
I don't understand the motivation for https://github.com/bitcoin/bitcoin/pull/5975 . Conceptually I would think of the check that a block header is not forked from before the last checkpoint, as being part of the contextual block header checks. Some Bitcoin Core devs seem to want to have the option to get rid of checkpoints for some reason, but I like checkpoints and I can't imagine us doing that in Zcash. The effect of this change is that if ``ContextualCheckBlockHeader`` were called from other places, then it wouldn't include the forked-from-before-last-checkpoint check, which seems undesirable to me.

**Comment by daira** [comment]
Tracking progress of my review of the suitability of patches to merge for Zcash:

[ ] bitcoin/bitcoin#6198
[ ] bitcoin/bitcoin#6206
[ ] bitcoin/bitcoin#6152
[ ] bitcoin/bitcoin#5927
[ ] bitcoin/bitcoin#6213
[ ] bitcoin/bitcoin#5975
[ ] bitcoin/bitcoin#6061
[ ] bitcoin/bitcoin#6283 (partial, remainder was pulled in #929)
[ ] bitcoin/bitcoin#6272
[ ] bitcoin/bitcoin#6316
[ ] bitcoin/bitcoin#6299 (partial, remainder in #2100)
[ ] bitcoin/bitcoin#6133
[ ] bitcoin/bitcoin#6361
[ ] bitcoin/bitcoin#6387
[ ] bitcoin/bitcoin#6401
[ ] bitcoin/bitcoin#6370
[ ] bitcoin/bitcoin#6434
[ ] bitcoin/bitcoin#6372
[ ] bitcoin/bitcoin#6447
[ ] bitcoin/bitcoin#6149
[ ] bitcoin/bitcoin#6468

**Comment by sipa** [comment]
The reasoning for wanting to remove checkpoints is because they're no longer necessary after 0.10, and lead many to misunderstand the systems security model ("deep reorganizations are not possible because chrckpoints"). While the latter is a true statement, it's pretty meaningless: if a checkpoint ever prevents a deep reorg from the tip, it means PoW is just totally busted and we should get rid of it.

What checkpoints however did do, was enable a performance trick. Before 0.10, we didn't know what block we were syncing towards before actually reaching it, and therefore restricting what blocks we could synchronize towards was the only way to be sure that validation of old blocks could be skipped. Since headers-first, we do know ahead of time what we're syncing towards, and can just use that knowledge instead of restricting what blocks to accept.

In 0.14, the only effect that checkpoints still have is preventing being DoSsed by receiving a large amount of low-height, low-difficulty headers, but it doesn't need continuous updating. For skipping validation, there is -assumevalid=hash, which just lists the hash of the last block you know to be valid. It doesn't prevent reorgs, but otherwise has the same benefits.

**Comment by daira** [comment]
https://github.com/bitcoin/bitcoin/pull/5975 broke stuff that had to be fixed in https://github.com/bitcoin/bitcoin/pull/6299 , and the result is more complicated code overall. I suggest just not doing either change.

**Comment by daira** [comment]
Re: https://github.com/bitcoin/bitcoin/pull/6361 , since we already depend on Boost 1.62 (https://github.com/zcash/zcash/blob/master/depends/packages/boost.mk), the conditional code for Boost < 1.56 (and the reference in the doc comment) should be removed.

**Comment by daira** [comment]
Note that https://github.com/bitcoin/bitcoin/pull/6387 probably fixes #2108 for zcash-cli.

**Comment by jtimon** [comment]
The goal of https://github.com/bitcoin/bitcoin/pull/5975 / https://github.com/bitcoin/bitcoin/pull/6299 is to decouple that consensus function from the checkpoints, which aren't consensus rules.
Also note that the checkpoint check is a check on the CBlockIndex that you're going to use to check the CBlockHeader, not a check on the CBlockHeader itself.
Honestly I don't think 6299 complicates things that much, it's just adding a check to avoid the check for the genesis block when -reindex.
Regarding the checkpoints, in 0.14 we completely get rid of them and introduce the assumevalid functionality to replace them for saving script checks, see https://github.com/bitcoin/bitcoin/pull/9484

**Comment by str4d** [comment]
> Re: bitcoin/bitcoin#6152 , won't we need EraseTransaction if we implement transaction expiry (#754)?

Good point; that would be an instance of the node logic invalidating a transaction.

> Re: bitcoin/bitcoin#6213 , I don't think we have -blockversion (it's not in init.cpp).

We do have it, inherited from 0.11.2 (look in `miner.cpp`).

> @sipa Thanks for clarifying that. In any case we should not merge bitcoin/bitcoin#5927 without bitcoin/bitcoin#5875 , which this PR currently does.

See #2074: we already have bitcoin/bitcoin#5875 in our repo, as it was backported to the 0.11.X branch. If you still want a ticket opened for further issues, please do so.

> bitcoin/bitcoin#5975 broke stuff that had to be fixed in bitcoin/bitcoin#6299 , and the result is more complicated code overall.

We did the same thing with our genesis block, by forgetting to add `nHeight` to the coinbase transaction and then having to special-case it later. Perhaps there is a better way to handle that overall. I dispute that it is more complicated code though; the diff might look complex, but all it is doing is shifting an if check outwards around some code, and indenting that code appropriately.

**Comment by str4d** [comment]
Summary of reviews:

PR | @daira | @bitcartel
--- | --- | ---
bitcoin/bitcoin#6152 | NACK | ACK
bitcoin/bitcoin#5927 | NACK | NACK
bitcoin/bitcoin#6213 | NACK (but we do have that option) | ACK
bitcoin/bitcoin#5975 | NACK | NACK
bitcoin/bitcoin#6061 | ACK | NACK
bitcoin/bitcoin#6272 | ACK | NACK
bitcoin/bitcoin#6299 (partial) | NACK | NACK
bitcoin/bitcoin#6133 | ACK | NACK
bitcoin/bitcoin#6361 | ACK | NACK
bitcoin/bitcoin#6401 | ACK | NACK
bitcoin/bitcoin#6468 | ACK | NACK

**Comment by str4d** [comment]
- @daira will re-consider bitcoin/bitcoin#5927

**Comment by str4d** [comment]
Rebased, PRs trimmed down.

**Comment by arcalinea** [comment]
@zkbot try

**Comment by arcalinea** [comment]
@zkbot r+

**Comment by arcalinea** [comment]
@zkbot retry

**Comment by daira** [comment]
https://github.com/bitcoin/bitcoin/pull/6172 fixes a DoS problem with https://github.com/bitcoin/bitcoin/pull/5927 (see https://github.com/bitcoin/bitcoin/pull/6172#issuecomment-110752459). Either include both in this PR, or extract both to a new PR.

**Comment by daira** [comment]
Actually, this needs further discussion -- see https://github.com/bitcoin/bitcoin/pull/9061 . I recommend extracting to a separate PR.

**Comment by daira** [comment]
Oh, this was already merged. In that case, we need to also merge https://github.com/bitcoin/bitcoin/pull/6172 , https://github.com/bitcoin/bitcoin/pull/6974, and optionally https://github.com/bitcoin/bitcoin/pull/9061 (which Bitcoin Core rejected, but I disagree with their reasoning).

**Comment by str4d** [comment]
@daira you're not confused; bitcoin/bitcoin#5975 was removed, not bitcoin/bitcoin#5927. I'll open a new PR with the additional upstream PRs.

**Comment by str4d** [comment]
For future reference: bitcoin/bitcoin#6172 was already present in the 0.11 branch.

**Pull request merged**
