### PR TITLE
Add ZeroMQ notifications

### LINKED ISSUE #2020: zmq feature like bitcoin
Zcash cut the zmq feature of bitcoin?

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6103
- bitcoin/bitcoin#6684
- bitcoin/bitcoin#6686
- bitcoin/bitcoin#6736
- bitcoin/bitcoin#6739
- bitcoin/bitcoin#6743
- bitcoin/bitcoin#6768
- bitcoin/bitcoin#6779
- bitcoin/bitcoin#6810
- bitcoin/bitcoin#6927
- bitcoin/bitcoin#6980 (only upgrading zeromq)
- bitcoin/bitcoin#6680
- bitcoin/bitcoin#7058
- bitcoin/bitcoin#7621
- bitcoin/bitcoin#7335 (only parts affecting `zmq_test.py`)
- bitcoin/bitcoin#7853 (only parts affecting `zmq_test.py`)
- bitcoin/bitcoin#7762
- bitcoin/bitcoin#7993 (only upgrading zeromq)
- bitcoin/bitcoin#8238
- bitcoin/bitcoin#8701
- bitcoin/bitcoin#6685

Closes #2020.

### CODE REVIEW

**Comment by str4d** [comment]
Before merging this, Buildbot needs to be updated to `pip install zmq` before running the RPC tests, as that is now a dependency.

**Comment by daira** [comment]
``contrib/debian/copyright`` needs an entry for ``depends/sources/zeromq-*.tar.gz``.

**Comment by daira** [comment]
```
Files: depends/sources/zeromq-*.tar.gz
Copyright: 1994, 1995, 1996, 1999, 2000, 2001, 2002, 2004, 2005,
 2006, 2007 Free Software Foundation, Inc.
License: LGPL
```

**Comment by daira** [comment]
... and add ``libzmq3-dev`` to ``Build-Depends`` in ``contrib/debian/control``.

**Comment by daira** [comment]
The ``package.mk`` for libzmq builds it with the ``--without-libsodium --disable-curve`` options, which disables security and authentication features (I'm not sure of the exact details of what is disabled). Presumably this was intended by Bitcoin upstream because it's not the default, but is it what we want?

**Comment by daira** [comment]
libzmq has a new version 4.1.6. Its release notes since 4.1.5 are:

> 0MQ version 4.1.6 stable, released on 2016/11/01
> ================================================
>
> * Fixed #2051 - getifaddrs can fail with ECONNREFUSED
> * Fixed #2091 - testutil.hpp fails to build on Windows XP
> * Fixed #2096 - add tests/CMakeLists.in and version.rc.in to dist tar
> * Fixed #2107 - zmq_connect with IPv6 "source:port;dest:port" broken
> * Fixed #2117 - ctx_term assert with inproc zmq_router connect-before-bind
> * Fixed #2158 - Socket monitor uses internal Pair from multiple threads
> * Fixed #2161 - messages dropped due to HWM race
> * Fixed #1325 - alignment issue with zmq_msg_t causes SIGBUS on SPARC and ARM

Some of these look like significant correctness issues.

**Comment by daira** [comment]
https://github.com/zeromq/libzmq/issues/2158 looks like undefined behaviour.

**Comment by daira** [comment]
Oh, the [current libzmq version](https://github.com/zeromq/libzmq/tags) is actually 4.2.1 ([release notes](https://github.com/zeromq/libzmq/releases/tag/v4.2.1)). In any case we should upgrade. I'm not sure whether there were API changes between 4.1.x and 4.2.x.

**Comment by str4d** [comment]
@daira wrote:
> ... and add libzmq3-dev libzmq5-dev (see here) to Build-Depends in contrib/debian/control.

The link doesn't make sense to me - could you elaborate?

> Edit: I'm not sure this is necessary. If it is not, then remove the reference to libzmq*-dev from doc/zmq.md.

The impression I got from that section was that it was listed so if a downstream packager wants to use provided dependencies instead of the `depends/` system, they know which package to use. So I'm +0 on removing the reference.

**Comment by str4d** [comment]
@daira wrote:
> The `package.mk` for libzmq builds it with the `--without-libsodium --disable-curve` options, which disables security and authentication features (I'm not sure of the exact details of what is disabled). Presumably this was intended by Bitcoin upstream because it's not the default, but is it what we want?

`--without-libsodium` was added while upgrading from 4.0.7 to 4.1.4 (https://github.com/bitcoin/bitcoin/pull/7993) to fix a build error.

`--disable-curve` was added while upgrading to 4.1.5 (https://github.com/bitcoin/bitcoin/pull/8238). Upstream did not need it enabled because they don't have libsodium as a dependency, and thus before 4.2 could not use CURVE security. The default security is [null](https://github.com/zeromq/libzmq/blob/master/doc/zmq_null.txt) (no security), and upstream didn't enable [plain](https://github.com/zeromq/libzmq/blob/master/doc/zmq_plain.txt) (password-based).

From 4.2.0 `--without-libsodium` is the default, as tweetnacl is used instead.

Now, we *could* enable CURVE security, but I expect it's not really necessary because the ZMQ interface is generally used from an internal network.

**Comment by daira** [comment]
ACK 4a8159343b0e1db2ff16dd138ab84271d2146774 and b418aa9027d3003a55089bdbcf2e6f55b46950f0.

**Comment by daira** [comment]
@str4d wrote:
> @daira wrote:
> > ... and add ~~libzmq3-dev~~ libzmq5-dev (see here) to Build-Depends in contrib/debian/control.
>
> The link doesn't make sense to me - could you elaborate?

Sorry, cut-and-paste error. The intended link was http://zeromq.org/distro:debian .

I think we should update doc/zmq.md to say libzmq5-dev and to make it clearer that this is only needed when not using the depends system.

**Comment by daira** [comment]
@str4d wrote:
> Now, we could enable CURVE security, but I expect it's not really necessary because the ZMQ interface is generally used from an internal network.

Hmm. Maybe we should just document (both in doc/zmq.md and doc/security-warnings.md) that ZMQ provides no authentication by default.

**Comment by bitcartel** [comment]
Upstream still on 4.1.5.  Maybe they'll upgrade to 4.2.1. https://github.com/bitcoin/bitcoin/issues/8639

**Comment by str4d** [comment]
Rebased on master to fix merge conflict, and addressed @daira's comments.

> Hmm. Maybe we should just document (both in doc/zmq.md and doc/security-warnings.md) that ZMQ provides no authentication by default.

This is already documented in `doc/zmq.md` by upstream (see [here](https://github.com/zcash/zcash/pull/2050/files#diff-d8e6fe13399f13c42a93ec8326c60614R21) and [here](https://github.com/zcash/zcash/pull/2050/files#diff-d8e6fe13399f13c42a93ec8326c60614R95)).

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@str4d See above:=== Running testscript --mineblock ===
./qa/pull-tester/rpc-tests.sh: line 77: /home/admin/bbs/zcash/build/qa/rpc-tests/--mineblock: No such file or directory
!!! FAIL: --mineblock !!!

**Comment by str4d** [comment]
@bitcartel there was an upstream PR I missed that fixed it.

@zkbot try

**Comment by bitcartel** [comment]
ACK

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
