### PR TITLE
Add `unsafe_speedup` to speed up tests

### PR DESCRIPTION
**Pull request by ebfull**
**This is *temporarily* useful to me personally, and perhaps it will be useful to the project if we feel more comfortable with it later. I don't know yet. This is definitely not ok to merge.**

This PR is meant to address #803 by bypassing SHA256's internal constraints and variables when a flag is explicitly set to the libsnark protoboard. Right now, I enable the flag for `zerocashTest` and `transaction_tests`, and I even increase the test tree-depth in `zerocashTest` to 32, and it runs quite a bit faster.

Many of the constructions we test, outside of the direct circuit tests, will use a fixed-depth tree, so the time for playing with various depths to avoid performance issues in tests needs to come to an end, whether we go with this PR or not.

I think eventually we'll want this to be a compiler flag of some kind, but since libsnark's headers leak everywhere in the project, it was simpler to make this an explicit runtime change in specific binaries and avoid changing the build system. (I want some tests and binaries to compile with the efficient circuit and the rest to be secure.)

I also originally meant to simply disable the constraints, but realized we also need to avoid allocating the variables. Thus, inside of the SHA256 compression function gadget I invoke SHA256 directly, however, I create an internal constraint to avoid the outside digest from being overwritten. (This *can* happen, but the constraint is there to prevent it just as if the hash evaluation were correctly constrained.)

### CODE REVIEW

**Comment by ebfull** [comment]
@zkbot try

**Comment by ebfull** [comment]
Ah yes, this commit does require the SHA256 padding changes, which are made in the ECIES pull.

I think I'll bring those in the tree in a separate PR anyway; hopefully we can get that merged ASAP.

**Comment by defuse** [comment]
I really like having faster tests so I think we should merge this (after reviewing it to make sure there are barriers to accidentally deploying it.)

**Comment by ebfull** [comment]
This PR is polluted by commits that it is not introducing to the trunk because I've merged them in another PR.

Until our rebase policy is settled, I'm superseding this with #818.

**Pull request closed without merging**
