### PR TITLE
Update copyright year to 2023

### PR DESCRIPTION
**Pull request by sandakersmann**
Update copyright year to 2023

### CODE REVIEW

**Comment by nuttycom** [comment]
Thank you for the contribution! We prefer to make these kind of changes via scripted-diffs; see https://github.com/zcash/zcash/pull/5950/commits/5ae1772d2b690a67c761c41601121ddd3bf04de4 (or more broadly https://github.com/zcash/zcash/pull/5950) for an example of how to make this change.

**Comment by sandakersmann** [comment]
We discussed this last year: https://github.com/zcash/zcash/pull/5438

**Comment by sandakersmann** [comment]
Can we get this into v5.4.0?

**Comment by str4d** [comment]
I would prefer that this be done with a scripted diff like #5950, so that we are consistently updating the copyright year in a single PR rather than across several PRs. But as crafting scripted diffs is not exactly trivial, we should really rebase #4926 and get it to produce the same effect (and in fact, it could also generate the equivalent scripted diff to add to the commit message).

In the interim, this PR would need to be rebased on, and target, the `version-5.4.0` branch if it were to be included in 5.4.0.

**Comment by nuttycom** [comment]
I have created a proposed alternative: https://github.com/zcash/zcash/pull/6362

**Comment by str4d** [comment]
Closed in favour of #6362.

**Pull request closed without merging**
