### PR TITLE
Upstream: Prevent possible DoS in logging

### PR DESCRIPTION
**Pull request by bitcartel**
bitcoin/bitcoin#8427

### CODE REVIEW

**Comment by bitcartel** [comment]
Ping @daira - there are a bunch of pull requests (derived from security backport ticket) tagged for rc2 and ready for review.

**Comment by daira** [comment]
ACK, matches upstream PR (modulo whitespace). @zkbot r+

**Comment by bitcartel** [comment]
@daira Fixed.  Ready for zkbot.

**Comment by daira** [comment]
ACK. @zkbot r+

**Pull request merged**
