### PR TITLE
Added security warning about DNS rebinding attack.

### PR DESCRIPTION
**Pull request by zebambam**

### CODE REVIEW

**Comment by mdr0id** [comment]
utACK

**Comment by mdr0id** [comment]
utACK

**Comment by zebambam** [comment]
Sorry, didn't realize that this didn't merge, now I've added the notice from ticket #3869 too.

**Comment by ioptio** [comment]
General question: should these docs live in source or on RTDs?

**Comment by zebambam** [comment]
Wherever you want. But wherever they live, let's make sure they have these additions until we fix the problem.

**Comment by mdr0id** [comment]
@zebambam Can you please squash commits?

Then I will `r+`.

**Comment by zebambam** [comment]
I've closed this and opened https://github.com/zcash/zcash/pull/3890 and https://github.com/zcash/zcash/pull/3892 instead.

**Pull request closed without merging**
