### PR TITLE
update libsodium to v1.0.18

### PR DESCRIPTION
**Pull request by ca333**
fixes https://github.com/zcash/zcash/issues/4238

### CODE REVIEW

**Comment by ca333** [comment]
We updated libsodium to 1.0.18 in Komodo and tested it with our codebase to ensure backwards compatibility - i just replicated https://github.com/KomodoPlatform/komodo/commit/5bb0bdffac7331e41baa40b563d342071df69110 in https://github.com/zcash/zcash/pull/4239/commits/934cdade3e6f2c04ff8f715fd5440c90721ff9ad

**Comment by daira** [comment]
What did you test exactly? The risk is of unintended consensus changes in the verification of signatures that libsodium does not itself produce.

**Comment by daira** [comment]
Due to it affecting cryptographic code and the risk of unintended consensus changes, this requires 3 reviews; at least 2 from ECC engineers.

**Comment by str4d** [comment]
Superceded by #4359.

**Pull request closed without merging**
