### PR TITLE
Update dependencies for 6.0.0

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Review by daira — DISMISSED** [review]
utACK

**Comment by str4d** [comment]
This Rust test in CI is failing:
https://github.com/zcash/zcash/blob/bfaaf1c468ff47ece3e7370a77febba6cd29eca8/src/rust/src/tests/zip339.rs#L42-L50
https://github.com/zcash/zcash/blob/bfaaf1c468ff47ece3e7370a77febba6cd29eca8/src/rust/src/zip339_ffi.rs#L87-L94

Upgrading from Rust 1.80.1 to Rust 1.81.0 is causing `#[should_panic]` to stop capturing the `assert!()` panic.

**Comment by str4d** [comment]
Opened https://github.com/rust-lang/rust/issues/130864.

**Review by nuttycom — COMMENTED** [review]
utACK 31ffb08e90fa97d3bf20c74983e78e01880f745e

**Review by nuttycom — APPROVED** [review]

**Pull request merged**
