### PR TITLE
option to disable building libraries (zcutil/build.sh)

### PR DESCRIPTION
**Pull request by kozyilmaz**
option to disable building libraries (zcutil/build.sh)

### CODE REVIEW

**Comment by aayanl** [comment]
:+1: My nightly build has at least a thousand `building boost`s in there now

**Comment by daira** [comment]
@aayanl That's not what this patch does; it only affects building output libraries, not dependencies.

```
If --disable-libs is passed, Zcash is configured to not build any libraries like 'libzcashconsensus'.
```

utACK. @zkbot try

**Comment by daira** [comment]
Needs another ACK + smoke-testing the case where the option is set.

**Comment by daira** [comment]
Note that this is just exposing an existing option in the Makefiles via build.sh.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
