### PR TITLE
Use manual serialization for Merkle frontiers rather than bincode.

### PR DESCRIPTION
**Pull request by nuttycom**

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK (modulo changes to librustzcash).

**Review by daira — APPROVED** [review]
re-utACK

**Review by str4d — APPROVED** [review]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Transient CI failure.

@zkbot retry

**Comment by str4d** [comment]
Transient CI networking failure.

@zkbot retry

**Comment by str4d** [comment]
Yet another CI networking failure. I am so looking forward to being able to just retry individual builders and not have failures block other PRs as heavily.

@zkbot retry

**Pull request merged**
