### PR TITLE
Fix stale comment referencing upstream block interval

### PR DESCRIPTION
**Pull request by bitcartel**

### CODE REVIEW

**Comment by bitcartel** [comment]
@daira

**Comment by bitcartel** [comment]
Are you referring to this comment?  I left it as 288 blocks takes ~12 hours (24 per hour).

```    // If our best fork is no longer within 288 blocks (+/- 12 hours if no one mines it)
    // of our head, drop it
    if (pindexBestForkTip && chainActive.Height() - pindexBestForkTip->nHeight >= 288)
        pindexBestForkTip = NULL;
```

**Comment by daira** [comment]
ACK

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
