### PR TITLE
C++17 and clang

### PR DESCRIPTION
**Pull request by daira**

### CODE REVIEW

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
Hmm:
```
Building boost...
clang++: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by clang++)
```
(on Debian 9).

This doesn't seem insurmountable. We should be statically linking libm, anyway.

**Comment by daira** [comment]
Also this on some platforms:
```
Building boost...
clang++: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
I think libtinfo is part of ncurses.

**Comment by daira** [comment]
Those errors are the same ones as in https://github.com/zcash/zcash/pull/4613#issuecomment-659756727 , so I think we actually have made progress by combining the C++17 and clang PRs, because we only have those errors now rather than also the GCC-version-related ones.

**Comment by daira** [comment]
@zkbot try (testing a theory).

**Comment by daira** [comment]
Using clang 9.0.1 was more successful than it seems. The depends check is easily fixed, and I bet that clang++ is only failing on some platforms (e.g. https://ci.z.cash/#/builders/3/builds/412/steps/5/logs/stdio) because `ax_cxx_compile_stdcxx.m4` is being too strict.

**Comment by daira** [comment]
@zkbot cancel

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
@zkbot try

**Comment by rex4539** [comment]
Native macOS fails here:
```
  CXX      crypto/libbitcoin_crypto_a-sha256.o
  CXX      crypto/libbitcoin_crypto_a-sha512.o
  CXX      zcash/libzcash_a-IncrementalMerkleTree.o
  CXX      zcash/libzcash_a-NoteEncryption.o
wallet/wallet.cpp:3289:5: error: use of undeclared identifier 'random_shuffle'
    random_shuffle(vCoins.begin(), vCoins.end(), GetRandInt);
    ^
1 error generated.
make[2]: *** [wallet/libbitcoin_wallet_a-wallet.o] Error 1
```

**Comment by daira** [comment]
> Native macOS fails here:
> 
> ```
>   CXX      crypto/libbitcoin_crypto_a-sha256.o
>   CXX      crypto/libbitcoin_crypto_a-sha512.o
>   CXX      zcash/libzcash_a-IncrementalMerkleTree.o
>   CXX      zcash/libzcash_a-NoteEncryption.o
> wallet/wallet.cpp:3289:5: error: use of undeclared identifier 'random_shuffle'
>     random_shuffle(vCoins.begin(), vCoins.end(), GetRandInt);
>     ^
> 1 error generated.
> make[2]: *** [wallet/libbitcoin_wallet_a-wallet.o] Error 1
> ```

That should be fixed by ec2d0f715686d1a793db576b5f2dd1a8b44ddf16. It uncovers another error due to failing to find univalue symbols, though. That problem occurs for both cross builds and native builds, so I think we're making progress.

**Comment by rex4539** [comment]
`zcashd` actually compiles on native macOS Catalina :)

**Comment by rex4539** [comment]
The univalue error is probably related to https://github.com/zcash/zcash/issues/4309.

**Comment by daira** [comment]
@zkbot try

**Comment by rex4539** [comment]
After the latest merges and changes, it fails to compile on native macOS Catalina with

```
Building boost...
/Users/rex/rex4539-clang/depends/work/build/x86_64-apple-darwin19.6.0/boost/1_70_0-82af337d6ee/tools/build/src/build/feature.jam:491: in feature.validate-value-string from module feature
error: "clang" is not a known value of feature <toolset>
error: legal values: "darwin" "gcc"
```

**Comment by daira** [comment]
Thanks for checking that, @rex4539 .

**Comment by daira** [comment]
This is obsolete.

**Pull request closed without merging**
