### PR TITLE
Merge in 2.1.2-2 hotfix

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by daira** [comment]
This needs updating to merge in 2.1.2-3 instead.

**Comment by ebfull** [comment]
I will merge them separately @daira.

**Comment by ebfull** [comment]
See https://github.com/zcash/zcash/pull/4513

**Comment by ebfull** [comment]
@zkbot r+

**Comment by daira** [comment]
Superceded by #4513.

**Comment by daira** [comment]
@zkbot r-

**Comment by daira** [comment]
Sorry I didn't see your comment @ebfull. Feel free to r+ again if needed.

**Comment by nuttycom** [comment]
@zkbot r+

**Pull request merged**
