### PR TITLE
3604 fix sapling default memo - 0xF6 plus zeros

### LINKED ISSUE #3604: sapling; z_sendmany default memo is zeros, should be 0xF6
### Describe the issue
Sending to a Sapling output using `z_sendmany` without specifying a memo results in the memo being set to all zeros. It should be "no memo"; see section 5.5 of the protocol specification.

@str4d recently fixed this for `change` transactions here: https://github.com/zcash/zcash/pull/3518/commits/ba63dacbbbc647e4a84824a7aee5838c5bcabab4

### Can you reliably reproduce the issue?
Yes, it's easy to reproduce manually using the cli on testnet (not mainnet, as Sapling has not yet activated on mainnet). It is also easy to reproduce using the rpc tests.

#### If so, please list the steps to reproduce below:
1. Start `zcashd` on testnet
1. Create a Sapling address (`src/zcash-cli z_getnewaddress sapling`)
1. Send a payment to this Sapling zaddr without specifying a memo
1. Wait for the transaction to complete
1. Display the transaction using `z_listunspent` or `z_listreceivedbyaddress`

### Expected behaviour
The first byte of memo field of the transaction should be 0xF6 followed by 1023 bytes of zeros. This works correctly for Sprout output addresses.

### Actual behaviour + errors
The memo field shows as all zeros. (No errors are reported.)

### The version of Zcash you were using:
v2.0.1-rc1

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #3604. For Sapling outputs, set the default memo to `no_memo` instead of all zeros. (See section 5.5 of the Sapling protocol specification.)

### CODE REVIEW

**Comment by str4d** [comment]
Aaand in looking for the test that needs updating, I discovered why my original fix was able to get the test to pass:

https://github.com/zcash/zcash/blob/master/qa/rpc-tests/wallet_listreceived.py#L82

Copy-paste bug in the test: it's checking the change output's memo field twice, rather than checking the non-change output's memo field.

Fixing that should give you a test that fails before your fix, and passes afterwards.

**Comment by str4d** [comment]
https://github.com/zcash/zcash/blob/master/qa/rpc-tests/wallet_listreceived.py#L82 is the test that needs updating. There's a bug in the referenced line (it should be checking `r[1]['memo']` against `my_memo`, otherwise it's just doubling-up a previous check), but it isn't the bug I thought it was a moment ago (in a deleted comment I thought it was a bug that, when fixed, would test this change).

**Comment by LarryRuane** [comment]
@str4d, I pushed a fix for the test (it fails without the zcashd fix, succeeds with it), thanks for noticing that, good catch! I'm actually planning to replace that test (unify it with another test) in #3553 but it's good to keep this PR self-consistent.

**Comment by Eirik0** [comment]
ACK

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
