### PR TITLE
Add vjoinsplit to JSON output of RPC call gettransaction

### LINKED ISSUE #1446: RPC command gettransaction does not currently show joinsplits
Gettransaction provides contextual information about a tx and how it relates to the user's wallet.
Related to #1427

### PR DESCRIPTION
**Pull request by bitcartel**
Closes #1446.

### CODE REVIEW

**Comment by daira** [comment]
utACK.

**Comment by defuse** [comment]
ACK

**Comment by ebfull** [comment]
git's diff is annoying here, perhaps you can trick it by placing the new function after the wrapper function. Anyway, ACK.

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
