### PR TITLE
depends: Revert to using upstreams as primary download paths

### PR DESCRIPTION
**Pull request by str4d**
We use the depends system for vendoring `zcashd` dependencies, pinning them
with SHA-256 hashes. It supports fetching dependencies from both their
upstream archive source, and a mirror operated by ECC.

In #816, we switched to the ECC mirror as the primary source, due to an
unreliable upstream (SourceForge). However, this only addressed the symptom
(that dependency builds would reliably fail with an unreliable upstream that
was serving incorrect files). In particular, if the ECC mirror were to become
similarly unreliable, the issue would return.

This PR fixes the core problem, by downloading dependencies and checking
their hashes as an atomic operation. This gives us greater resiliency, as
both the primary and fallback would need to fail in order to halt the build.
Having addressed this problem, we also switch back to using upstreams as
primary download paths.

### CODE REVIEW

**Comment by str4d** [comment]
Here is the current set of upstreams for our dependencies:
```
❯ rg download_path depends/packages | parse "download_path={url}/" | sort-by url | uniq
────┬───────────────────────────────────────────────────────────────────────────
 #  │ url 
────┼───────────────────────────────────────────────────────────────────────────
  0 │ https://dl.bintray.com/boostorg/release/1.70.0 
  1 │ https://download.libsodium.org/libsodium/releases 
  2 │ https://download.oracle.com 
  3 │ https://github.com/google/$(package)/archive 
  4 │ https://github.com/libevent/libevent/archive 
  5 │ https://github.com/nemtrif/$(package)/archive 
  6 │ https://github.com/theuni/cctools-port 
  7 │ https://github.com/zeromq/libzmq/releases/download/v$($(package)_version) 
  8 │ https://llvm.org/releases 
  9 │ https://static.crates.io/crates 
 10 │ https://static.rust-lang.org 
 11 │ https://www.openssl.org/source/old 
 12 │ https://www.samba.org/ftp 
────┴───────────────────────────────────────────────────────────────────────────
```

**Comment by str4d** [comment]
I've replaced the `check-depends` step (which checks that all dependencies are on our mirror) with an `update-check` step (which checks that all dependencies are in `updatecheck.py`).

**Comment by ebfull** [comment]
utACK

**Comment by str4d** [comment]
@zkbot r+

**Comment by daira** [comment]
Hang on. IIRC, one of the reasons we changed the primary download URLs was that some upstream URLs would hang in a such a way that curl wouldn't time out. I don't see where this PR addresses that.

**Comment by str4d** [comment]
No, the reason was specifically this (https://github.com/zcash/zcash/pull/816#issuecomment-204156442):
> The test failed because sourceforge isn't serving this URL: http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2. If you put that in your browser right now you'll see a 404 page, but the HTTP status code is 200 OK, not 404. So the wget in the depends system succeeds and it doesn't fall back to using our mirror.

Where was the curl issue documented?

**Comment by daira** [comment]
I misremembered slightly. It was that curl was downloading an error page without the server reporting it as an error (#2431). That immediate issue was fixed in #2435, but see https://github.com/zcash/zcash/pull/2435#issuecomment-309596269 .

**Comment by str4d** [comment]
I removed the `update-check` addition because it failed due to hitting the crates.io API too hard.

@zkbot r+

**Comment by daira** [comment]
Post-hoc ACK

**Pull request merged**
