### PR TITLE
Use ed25519-zebra from crates.io.

### LINKED ISSUE #4592: Switch to ed25519-zebra 2.0.0
Currently we bring in a fork of `ed25519-zebra`, but this fork can be replaced with the new `2.0.0` release of `ed25519-zebra` which has the same behavior.

Steps:

1. Change the `./depends/packages/crate_ed25519_zebra.mk` file to point to `ed25519-zebra` from `crates.io`.
2. Update `Cargo.toml` to point to the `crates.io` version of `ed25519-zebra` version 2 or above.
3. Remove the git branch source replacement logic from `./.cargo/config.offline` as this is now obviated.
4. Compile in online mode (`CONFIGURE_FLAGS="--enable-online-rust" ./zcutil/build.sh -j8`) to make updates to `Cargo.lock`
5. Make sure your changes worked by compiling in offline mode.

### PR DESCRIPTION
**Pull request by nuttycom**
Closes #4592

### CODE REVIEW

**Comment by daira** [comment]
This affects consensus code (even though it *should* not be a consensus change), so it needs 3 ACKs.

**Comment by therealyingtong** [comment]
@zkbot r+

**Comment by str4d** [comment]
Dependency has been uploaded.

@zkbot retry

**Comment by str4d** [comment]
@zkbot retry

**Comment by str4d** [comment]
Hopefully the caches have expired now...

@zkbot retry

**Comment by therealyingtong** [comment]
@zkbot retry

**Comment by mdr0id** [comment]
@zkbot retry

**Pull request merged**
