### PR TITLE
Remove OSX and Windows files from Makefile + share directory.

### LINKED ISSUE #2169: Remove /share, /src/obj, and /src/obj-test
``/share`` looks to have only Bitcoin icons and other left-overs that we don't use.

### PR DESCRIPTION
**Pull request by syd0**
These are stale holdovers from bitcoin.

This closes #2169.

### CODE REVIEW

**Comment by syd0** [comment]
Btw @daira I decided to leave the BUILD_DATE in `genbuild.sh`. Upon closer inspection, it only modifies the BUILD_DATE if the git info changes. Since it seems useful to have the git and build info printed out (it gets printed out by the wallet code for example), and this doesn't change on every single build, I figure we can keep it in there. Let me know if you feel otherwise.

**Comment by daira** [comment]
@zkbot try

**Comment by daira** [comment]
git update problem. @zkbot retry

**Comment by str4d** [comment]
Needs rebase.

**Comment by str4d** [comment]
Rebased this on master (fixing trivial merge conflict in `Makefile.am`).

@zkbot r+

**Pull request merged**
