### PR TITLE
Update links

### PR DESCRIPTION
**Pull request by rex4539**
Updates numerous insecure or outdated links, plus a few minor typo fixes.

### CODE REVIEW

**Review by nuttycom — APPROVED** [review]

**Comment by nuttycom** [comment]
@zkbot r+

**Comment by str4d** [comment]
Hmm, I would have NACKed some of these changes:
- The changes to the git subtrees `src/leveldb`, `src/secp256k1`, and `src/univalue` (which should be fixed in their upstreams).
- The changes to M4 files that are cached dependencies (we should pull in the latest versions of these instead, which (from what I've seen of newer ones I've pulled) generally have these fixes).

But that mostly amounts to preventing extra work when updating the git subtrees, so isn't a hard blocker 🤷

**Review by daira — CHANGES_REQUESTED** [review]
NACK. From the COPYING file:
```
Contributors should understand licensing implications before modifying the
following files in build-aux/m4 (see https://github.com/zcash/zcash/issues/2827):

 * ax_check_compile_flag.m4
 * ax_check_link_flag.m4
 * ax_check_preproc_flag.m4
 * ax_pthread.m4
```

@zkbot r-

**Comment by daira** [comment]
Briefly, the problem is that these files are not licensed as MIT. In #2827, the authors disagree with me on the implications, but do not dispute that point. In my interpretation, this means that it is questionable whether we can make even trivial changes to these files, because we're relying on the fact that including them in the Zcash source counts as "mere aggregation" under the terms of the GPL.

**Comment by daira** [comment]
Apparently my r- didn't work. I will file a PR that reverts the changes to the Autoconf macros and the subtrees.

**Pull request merged**
