### PR TITLE
Update chainparams.cpp

### PR DESCRIPTION
**Pull request by ITH4Coinomia**
[Bug Fix] : Added Genesis Block

### CODE REVIEW

**Comment by ebfull** [comment]
Let's hardcode the hashes. :)

**Comment by amitkumarj441** [comment]
@ebfull Are you talking about #1335 ? Please let me know where to initiate the PR(which file) !

**Comment by ITH4Coinomia** [comment]
@ebfull Are you talking about #1335 ? Please provide me  an outliner as in how to proceed.

**Comment by daira** [comment]
I don't see how this PR helps. If there's a problem with uint256S and ToString

**Comment by str4d** [comment]
NACK, the changes here are a no-op as far as `chainparams.cpp` is concerned.

@ITH4Coinomia, what is your goal with this PR? What is the bug you are referring to?

**Pull request closed without merging**
