### PR TITLE
Remove the RC 1 block index error message

### LINKED ISSUE #1548: Remove tag from CDiskBlockIndex serialisation
https://github.com/zcash/zcash/pull/1526#discussion_r83571282

### PR DESCRIPTION
**Pull request by str4d**
Reverts 85457ddec13bc74bdf68e6739f2258044b06c611

Closes #1548

### CODE REVIEW

**Comment by daira** [comment]
This assumes that the testnet will be reset for rc2. Will it?

**Comment by defuse** [comment]
ACK

**Comment by str4d** [comment]
@daira given we will be changing the network params again in RC 2, we will be resetting the testnet.

**Comment by daira** [comment]
utACK, does not change coverage. @zkbot r+

**Pull request merged**
