### PR TITLE
Link with ntdll library on Windows

### LINKED ISSUE #5051: Windows Cross Compile Regression
8482ed63565021924db59c571d8b57848cd9640a introduces a regression into the Windows cross compile on Ubuntu 20.04:

```
make[1]: Leaving directory '/home/zcash/depends/work/build/x86_64-w64-mingw32/bdb/6.2.23-66f6d2aaa01/build_unix'
Postprocessing bdb...
Caching bdb...
copying packages: native_clang native_ccache native_rust native_b2 boost libevent zeromq libsodium utfcpp googletest libcxx bdb
to: /home/zcash/depends/x86_64-w64-mingw32
Vendoring crates...
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  the lock file /home/zcash/Cargo.lock needs to be updated but --locked was passed to prevent this
  If you want to try to generate the lock file without accessing the network, use the --offline flag.
make: *** [Makefile:129: /home/zcash/depends/x86_64-w64-mingw32/.stamp_886ad9a3c31] Error 101
make: Leaving directory '/home/zcash/depends'
```

### PR DESCRIPTION
**Pull request by daira**
This fixes a regression for builds targeting Windows introduced in #4947. It also includes a minor cleanup to fix a build warning.
closes #5051

### CODE REVIEW

**Comment by daira** [comment]
@zkbot try

**Review by mdr0id — APPROVED** [review]
Tested ACK

**Comment by daira** [comment]
We don't appear to have working CI for Windows cross-builds on either Tekton or Building, I think due to insufficient versions of the MinGW libraries. That's independent of this fix though. Only one review required since this doesn't affect consensus code (or non-Windows platforms).

**Comment by daira** [comment]
@zkbot r+

**Pull request merged**
