### PR TITLE
Bitcoin 0.12+ dbwrapper improvements

### LINKED ISSUE #2046: Educate Windows users to configure anti-virus software to exclude the Zcash data folder
Zcash does not obfuscate database files.  This means that someone can include the signature for a virus into a transaction, triggering anti-virus tools to quarantine the file.

Quarantining typically involves moving the file to a new location, which can lead to undefined behaviour and crashes. https://github.com/bitcoin/bitcoin/issues/4069

Obfuscation so that AV software cannot see the signatures was added upstream in 2016, by xoring data stored in leveldb: https://github.com/bitcoin/bitcoin/issues/6613

Note that such a change means that the leveldb database cannot be deciphered using standard tools.  Also, it's not impossible that the obfuscation itself leads to data looking like a virus signature, although this is highly unlikely.

A solution for now is to advise users running ports of Zcashd on Windows to configure their anti-virus software to exclude the Zcash folder from being checked. This would include the default (bundled) Windows Defender as well as third party software such as Norton, McAfee, etc.

The data folder on Windows should be located here:
`C:\Documents and Settings\YourUserName\Application data\Zcash`
or
`C:\Users\YourUserName\Appdata\Roaming\Zcash`

### PR DESCRIPTION
**Pull request by str4d**
Cherry-picked from the following upstream PRs:

- bitcoin/bitcoin#6650
  - Only refactor - excludes obfuscation
- bitcoin/bitcoin#6777
  - Excluding obfuscation-related changes
- bitcoin/bitcoin#6865
- bitcoin/bitcoin#6823
- bitcoin/bitcoin#6873
- bitcoin/bitcoin#7927
  - Excluding first commit (already included) and second commit (obfuscation-related)
- bitcoin/bitcoin#8467

Part of #2074.

### CODE REVIEW

**Comment by str4d** [comment]
The first three PRs implement database obfuscation for new databases (and for existing users that `-reindex`). The remaining PRs are genericism of `dbwrapper` to support more databases than leveldb, and some cleanups.

I pulled in PRs beyond 0.12 that touched `dbwrapper` up to bitcoin/bitcoin#9039 (which we cannot easily pull in yet because it touches a lot of the codebase). PRs beyond this had various merge conflicts.

**Comment by str4d** [comment]
Rebased on 1.0.12 to handle changes that were pulled in early in #2545.

**Comment by daira** [comment]
Concept ACK on including all of these upstream PRs.

**Comment by bitcartel** [comment]
Concept NACK.  I am not convinced that the database should be obfuscated by xoring data!  Imagine if this policy were adopted by other applications and their embedded databases and what it would mean for third-party tools used to inspect databases. Original reason for this was that upstream had some data embedded in the blockchain which matches anti-virus signatures on Windows, causing some AV programs to quarantine the datadir folder.  The solution is simple: tell Windows users to add the datadir folder to the AV software whitelist.  If this step is tricky, than the Windows installer or some other tool should be developed to check and prompt users to do this for the most popular AV programs on Windows.

**Comment by radix42** [comment]
I am very much an ACK on the dbwrapper stuff, way too much of the underlying database's abstractions leak up where they shouldn't. NACK on that obfuscation stuff too, it is not difficult to add exceptions to Windows Defender, which is bundled, free, and the best AV for it, and current zcash datadirs are NOT being flagged by it.

**Comment by bitcartel** [comment]
Just to clarify, I am concept ACK on dbwrapper.

**Comment by str4d** [comment]
Consensus from commenters is leaning towards leaving out obfuscation. I will wear the merge conflicts for that and split this PR in two, but it won't make 1.0.14.

**Comment by str4d** [comment]
Rebased on master and removed obfuscation content.

@zkbot try

**Comment by str4d** [comment]
Looks like a transient timeout in an unrelated test on one builder - the full test suite passed on other builders.

**Comment by str4d** [comment]
The `BatchWriteNullifier` refactor is the following (from [here](https://github.com/zcash/zcash/pull/2598/files#diff-81e4f16a1b5d5b7ca25351a63d07cb80L46) and [here](https://github.com/zcash/zcash/pull/2598/files#diff-81e4f16a1b5d5b7ca25351a63d07cb80L145)):

```diff
-void static BatchWriteNullifier(CLevelDBBatch &batch, const uint256 &nf, const bool &entered) {
-    if (!entered)
-        batch.Erase(make_pair(DB_NULLIFIER, nf));
-    else
-        batch.Write(make_pair(DB_NULLIFIER, nf), true);
-}
@@ -142,23 +116,26 @@ bool CCoinsViewDB::BatchWrite(CCoinsMap &mapCoins,
 
     for (CNullifiersMap::iterator it = mapNullifiers.begin(); it != mapNullifiers.end();) {
         if (it->second.flags & CNullifiersCacheEntry::DIRTY) {
-            BatchWriteNullifier(batch, it->first, it->second.entered);
+            if (!it->second.entered)
+                batch.Erase(make_pair(DB_NULLIFIER, it->first));
+            else
+                batch.Write(make_pair(DB_NULLIFIER, it->first), true);
             // TODO: changed++?
         }
         CNullifiersMap::iterator itOld = it++;
         mapNullifiers.erase(itOld);
     }
```
I'm satisfied it is a no-op.

**Comment by str4d** [comment]
@zkbot r+

**Comment by str4d** [comment]
Failed because we merged #3132 into master first, which didn't create a merge conflict but *did* introduce a new txdb function that needs to be migrated in here.

**Comment by str4d** [comment]
Rebased on master, and then pushed a commit to update the new function.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
