### PR TITLE
Return JoinSplit and JoinSplitOutput indexes in z_listreceivedbyaddress

### PR DESCRIPTION
**Pull request by leto**
This implements a feature request by @nathan-at-least in https://github.com/zcash/zcash/issues/2932 and I wanted to ask for feedback about the exact form of the data returned before updating tests and docs.

### CODE REVIEW

**Comment by leto** [comment]
I have successfully used this patch to inspect a vary large Hush transaction with 54 zaddr receivers, and it seems to correctly identify each: https://gist.github.com/leto/bbc3f797db9b09d728cdc69611e69a99

**Comment by leto** [comment]
@bitcartel please see @daira's comments in https://github.com/zcash/zcash/issues/2932 about how to name these indexes in a future-proof way. I don't have a horse in the race for the actual names of the keys, but I like Daira's suggestions.

I will start working on tests, thanks for the feedback!

**Comment by bitcartel** [comment]
I'm going to use `jsindex` and `jsoutindex`.

**Comment by bitcartel** [comment]
@leto This looks good.  Can you squash the commits down into one?  Thanks!

**Comment by leto** [comment]
@bitcartel I squashed those commits into 1 commit, cheers :+1:

**Comment by bitcartel** [comment]
@zkbot try

**Comment by bitcartel** [comment]
@zkbot r+

**Pull request merged**
