### PR TITLE
Added libtinfo5 to ci builder containers

### PR DESCRIPTION
**Pull request by benzcash**
- Updated apt list for Debian and Ubuntu images.
- made the image creation script executable
- Fixed `bbworker-buildbot.tac` in Centos Dockerfile

This is to support Clang 8  https://github.com/zcash/zcash/pull/4613

You can test it with the images on Docker Hub now something like:
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-debian9
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-debian10
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-ubuntu18.04
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-ubuntu20.04
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-centos8
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```
```
docker run --rm -ti --entrypoint bash electriccoinco/zcashd-bbworker-arch
git clone https://github.com/str4d/zcash.git
cd zcash/
git checkout claaaaaang
./zcutil/build.sh -j4
```

### CODE REVIEW

**Comment by str4d** [comment]
Confirmed that `debian10` and `centos8` can build the Clang 8 branch. I can't check the Arm64 and Windows cross-compiles on Debian 10 (that CI runs) because I can't figure out how to install additional packages inside the running image (e.g. `mingw-w64`).

**Comment by benzcash** [comment]
`electriccoinco/zcashd-bbworker` images run as the buildbot user and can't become root. But they're built off the `electriccoinco/zcashd-build` images. Those run as root an setup the base container.

Besides `mingw-w64` any other packages we should add the the image?

I have this list in CI for the OSX images `libcap-dev libz-dev libbz2-dev`, but I have no idea if they are really needed.

**Comment by str4d** [comment]
- Whichever image you use to run the Windows cross-compile build needs to have `mingw-w64` 6.0.0 or later.
- Whichever image you use to run the aarch64 cross-compile build needs to have `g++-aarch64-linux-gnu`.

**Review by str4d — APPROVED** [review]
ACK. The CI workers deployed from these scripts are successfully running the Clang 8 branch.

**Comment by str4d** [comment]
@zkbot r+

**Pull request merged**
